//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Address: Sendable, Codable, Hashable {

    public var country: String
    public var city: String
    public var address: String

    public init(country: String, city: String, address: String) {
        self.country = country
        self.city = city
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case city
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(country, forKey: .country)
        try container.encode(city, forKey: .city)
        try container.encode(address, forKey: .address)
    }
}

