//
// ApiError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Unified error contract for client SDKs. */
public struct ApiError: Sendable, Codable, Hashable {

    /** Application or HTTP status code as string (e.g. \"400\", \"VALIDATION_ERROR\"). */
    public var code: String
    /** Human-readable error message. */
    public var message: String
    /** Additional payload for validation fields or debug metadata. */
    public var details: [String: JSONValue]?

    public init(code: String, message: String, details: [String: JSONValue]? = nil) {
        self.code = code
        self.message = message
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

