//
// AuthParametersAppleToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthParametersAppleToken: Sendable, Codable, Hashable {

    public var token: String
    public var email: String?
    public var firstName: String?
    public var emailVerified: Bool?
    public var lastName: String?

    public init(token: String, email: String? = nil, firstName: String? = nil, emailVerified: Bool? = nil, lastName: String? = nil) {
        self.token = token
        self.email = email
        self.firstName = firstName
        self.emailVerified = emailVerified
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case email
        case firstName
        case emailVerified
        case lastName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(emailVerified, forKey: .emailVerified)
        try container.encodeIfPresent(lastName, forKey: .lastName)
    }
}

