//
// AuthParametersGoogleToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthParametersGoogleToken: Sendable, Codable, Hashable {

    public var lastName: String?
    public var token: String
    public var firstName: String?

    public init(lastName: String? = nil, token: String, firstName: String? = nil) {
        self.lastName = lastName
        self.token = token
        self.firstName = firstName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lastName
        case token
        case firstName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(firstName, forKey: .firstName)
    }
}

