//
// ClientInternalUserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClientInternalUserInfo: Sendable, Codable, Hashable {

    public var nickname: String
    public var avatar: String

    public init(nickname: String, avatar: String) {
        self.nickname = nickname
        self.avatar = avatar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nickname
        case avatar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nickname, forKey: .nickname)
        try container.encode(avatar, forKey: .avatar)
    }
}

