//
// ComplexParametersCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComplexParametersCreate: Sendable, Codable, Hashable {

    public var priceShift: ComplexHelpersPriceShift
    public var chunks: [ComplexHelpersCreateChunkRequest]
    public var alias: String?
    public var description: String?

    public init(priceShift: ComplexHelpersPriceShift, chunks: [ComplexHelpersCreateChunkRequest], alias: String? = nil, description: String? = nil) {
        self.priceShift = priceShift
        self.chunks = chunks
        self.alias = alias
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case priceShift
        case chunks
        case alias
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(priceShift, forKey: .priceShift)
        try container.encode(chunks, forKey: .chunks)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

