//
// ComplexResponsesAll.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComplexResponsesAll: Sendable, Codable, Hashable {

    public var complexes: [ComplexHelpersComplexResponse]

    public init(complexes: [ComplexHelpersComplexResponse]) {
        self.complexes = complexes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case complexes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(complexes, forKey: .complexes)
    }
}

