//
// ComplexHelpersPriceShift.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComplexHelpersPriceShift: Sendable, Codable, Hashable {

    public var percent: Double

    public init(percent: Double) {
        self.percent = percent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(percent, forKey: .percent)
    }
}

