//
// ContactType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ContactType: String, Sendable, Codable, CaseIterable {
    case phone = "phone"
    case email = "email"
    case telegram = "telegram"
    case instagram = "instagram"
}
