//
// CredentialsSet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CredentialsSet: Sendable, Codable, Hashable {

    public var salaryCreds: [String]
    public var statisticCreds: [String]
    public var employeeCreds: [String]
    public var clientCreds: [String]
    public var appointmentCreds: [String]
    public var positionCreds: [String]
    public var notifyCreds: [String]
    public var procedureCreds: [String]
    public var salonCreds: [String]
    public var worktimeCreds: [String]
    public var financeCreds: [String]

    public init(salaryCreds: [String], statisticCreds: [String], employeeCreds: [String], clientCreds: [String], appointmentCreds: [String], positionCreds: [String], notifyCreds: [String], procedureCreds: [String], salonCreds: [String], worktimeCreds: [String], financeCreds: [String]) {
        self.salaryCreds = salaryCreds
        self.statisticCreds = statisticCreds
        self.employeeCreds = employeeCreds
        self.clientCreds = clientCreds
        self.appointmentCreds = appointmentCreds
        self.positionCreds = positionCreds
        self.notifyCreds = notifyCreds
        self.procedureCreds = procedureCreds
        self.salonCreds = salonCreds
        self.worktimeCreds = worktimeCreds
        self.financeCreds = financeCreds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case salaryCreds
        case statisticCreds
        case employeeCreds
        case clientCreds
        case appointmentCreds
        case positionCreds
        case notifyCreds
        case procedureCreds
        case salonCreds
        case worktimeCreds
        case financeCreds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(salaryCreds, forKey: .salaryCreds)
        try container.encode(statisticCreds, forKey: .statisticCreds)
        try container.encode(employeeCreds, forKey: .employeeCreds)
        try container.encode(clientCreds, forKey: .clientCreds)
        try container.encode(appointmentCreds, forKey: .appointmentCreds)
        try container.encode(positionCreds, forKey: .positionCreds)
        try container.encode(notifyCreds, forKey: .notifyCreds)
        try container.encode(procedureCreds, forKey: .procedureCreds)
        try container.encode(salonCreds, forKey: .salonCreds)
        try container.encode(worktimeCreds, forKey: .worktimeCreds)
        try container.encode(financeCreds, forKey: .financeCreds)
    }
}

