//
// CursorPageMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CursorPageMeta: Sendable, Codable, Hashable {

    public var nextCursor: String?
    public var hasMore: Bool

    public init(nextCursor: String? = nil, hasMore: Bool) {
        self.nextCursor = nextCursor
        self.hasMore = hasMore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nextCursor
        case hasMore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nextCursor, forKey: .nextCursor)
        try container.encode(hasMore, forKey: .hasMore)
    }
}

