//
// DeviceResponsesFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceResponsesFull: Sendable, Codable, Hashable {

    public var id: UUID
    public var version: VersionType?

    public init(id: UUID, version: VersionType? = nil) {
        self.id = id
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(version, forKey: .version)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DeviceResponsesFull: Identifiable {}
