//
// DeviceParametersSystem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceParametersSystem: Sendable, Codable, Hashable {

    public var manufacturer: String?
    public var system: [String: ModelAny]?
    public var appVersion: String?
    public var country: String?
    public var fcmToken: String?
    public var model: String?

    public init(manufacturer: String? = nil, system: [String: ModelAny]? = nil, appVersion: String? = nil, country: String? = nil, fcmToken: String? = nil, model: String? = nil) {
        self.manufacturer = manufacturer
        self.system = system
        self.appVersion = appVersion
        self.country = country
        self.fcmToken = fcmToken
        self.model = model
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case manufacturer
        case system
        case appVersion
        case country
        case fcmToken
        case model
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(manufacturer, forKey: .manufacturer)
        try container.encodeIfPresent(system, forKey: .system)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(fcmToken, forKey: .fcmToken)
        try container.encodeIfPresent(model, forKey: .model)
    }
}

