//
// EmployeeInternalUserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmployeeInternalUserInfo: Sendable, Codable, Hashable {

    public var nickname: String
    public var avatar: String
    public var id: UUID

    public init(nickname: String, avatar: String, id: UUID) {
        self.nickname = nickname
        self.avatar = avatar
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nickname
        case avatar
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nickname, forKey: .nickname)
        try container.encode(avatar, forKey: .avatar)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmployeeInternalUserInfo: Identifiable {}
