//
// EmployeeResponsesFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmployeeResponsesFull: Sendable, Codable, Hashable {

    public var user: EmployeeInternalUserInfo?
    public var salonId: UUID
    public var id: UUID
    public var contacts: [ContactSharedPrimaryContact]
    public var position: PositionResponsesFull

    public init(user: EmployeeInternalUserInfo? = nil, salonId: UUID, id: UUID, contacts: [ContactSharedPrimaryContact], position: PositionResponsesFull) {
        self.user = user
        self.salonId = salonId
        self.id = id
        self.contacts = contacts
        self.position = position
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case salonId
        case id
        case contacts
        case position
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encode(salonId, forKey: .salonId)
        try container.encode(id, forKey: .id)
        try container.encode(contacts, forKey: .contacts)
        try container.encode(position, forKey: .position)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmployeeResponsesFull: Identifiable {}
