//
// EmployeeResponsesPartial.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmployeeResponsesPartial: Sendable, Codable, Hashable {

    public var position: PositionResponsesPartial
    public var avatar: String
    public var id: UUID
    public var nickname: String
    public var contacts: [ContactSharedPrimaryContact]

    public init(position: PositionResponsesPartial, avatar: String, id: UUID, nickname: String, contacts: [ContactSharedPrimaryContact]) {
        self.position = position
        self.avatar = avatar
        self.id = id
        self.nickname = nickname
        self.contacts = contacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case position
        case avatar
        case id
        case nickname
        case contacts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(position, forKey: .position)
        try container.encode(avatar, forKey: .avatar)
        try container.encode(id, forKey: .id)
        try container.encode(nickname, forKey: .nickname)
        try container.encode(contacts, forKey: .contacts)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmployeeResponsesPartial: Identifiable {}
