//
// FavoriteResponsesSalon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FavoriteResponsesSalon: Sendable, Codable, Hashable {

    public var address: Address
    public var isActive: Bool
    public var point: CoordinatePoint
    public var id: UUID
    public var logo: String
    public var name: String
    public var type: SalonType

    public init(address: Address, isActive: Bool, point: CoordinatePoint, id: UUID, logo: String, name: String, type: SalonType) {
        self.address = address
        self.isActive = isActive
        self.point = point
        self.id = id
        self.logo = logo
        self.name = name
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case isActive
        case point
        case id
        case logo
        case name
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(point, forKey: .point)
        try container.encode(id, forKey: .id)
        try container.encode(logo, forKey: .logo)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension FavoriteResponsesSalon: Identifiable {}
