//
// File.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct File: Sendable, Codable, Hashable {

    public var data: Data
    public var filename: String

    public init(data: Data, filename: String) {
        self.data = data
        self.filename = filename
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case filename
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(filename, forKey: .filename)
    }
}

