//
// GetSearchCursorPageResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum GetSearchCursorPageResponseDataInner: Sendable, Codable, Hashable {
    case typeSearchResponsesHelpersSalon(SearchResponsesHelpersSalon)
    case typeSearchResponsesHelpersSuggest(SearchResponsesHelpersSuggest)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSearchResponsesHelpersSalon(let value):
            try container.encode(value)
        case .typeSearchResponsesHelpersSuggest(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SearchResponsesHelpersSalon.self) {
            self = .typeSearchResponsesHelpersSalon(value)
        } else if let value = try? container.decode(SearchResponsesHelpersSuggest.self) {
            self = .typeSearchResponsesHelpersSuggest(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetSearchCursorPageResponseDataInner"))
        }
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetSearchCursorPageResponseDataInner: Identifiable {}
