//
// GetWorkspaceClientsCursorPageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetWorkspaceClientsCursorPageResponse: Sendable, Codable, Hashable {

    public var data: [ClientResponsesClientInfo]
    public var meta: CursorPageMeta

    public init(data: [ClientResponsesClientInfo], meta: CursorPageMeta) {
        self.data = data
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(meta, forKey: .meta)
    }
}

