//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Transition error envelope. During migration clients should support both legacy and new formats. */
public enum ModelErrorResponse: Sendable, Codable, Hashable {
    case typeApiError(ApiError)
    case typeLegacyErrorResponse(LegacyErrorResponse)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeApiError(let value):
            try container.encode(value)
        case .typeLegacyErrorResponse(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(ApiError.self) {
            self = .typeApiError(value)
        } else if let value = try? container.decode(LegacyErrorResponse.self) {
            self = .typeLegacyErrorResponse(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ModelErrorResponse"))
        }
    }
}

