//
// NoticeResponsesFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NoticeResponsesFull: Sendable, Codable, Hashable {

    public var date: Date?
    public var messageKey: String
    public var titleKey: String
    public var parameters: [String: String]
    public var id: UUID
    public var isRead: Bool
    public var category: String

    public init(date: Date? = nil, messageKey: String, titleKey: String, parameters: [String: String], id: UUID, isRead: Bool, category: String) {
        self.date = date
        self.messageKey = messageKey
        self.titleKey = titleKey
        self.parameters = parameters
        self.id = id
        self.isRead = isRead
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case messageKey
        case titleKey
        case parameters
        case id
        case isRead
        case category
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encode(messageKey, forKey: .messageKey)
        try container.encode(titleKey, forKey: .titleKey)
        try container.encode(parameters, forKey: .parameters)
        try container.encode(id, forKey: .id)
        try container.encode(isRead, forKey: .isRead)
        try container.encode(category, forKey: .category)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension NoticeResponsesFull: Identifiable {}
