//
// Pagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Pagination: Sendable, Codable, Hashable {

    public var page: Int64
    public var per: Int64

    public init(page: Int64, per: Int64) {
        self.page = page
        self.per = per
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case per
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(per, forKey: .per)
    }
}

