//
// PaymentSubscriptionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaymentSubscriptionResponse: Sendable, Codable, Hashable {

    public var yearlyPayURL: String
    public var description: String
    public var monthlyPrice: Double
    public var monthlyPayURL: String
    public var yearlyPrice: Double
    public var logoURL: String
    public var title: String

    public init(yearlyPayURL: String, description: String, monthlyPrice: Double, monthlyPayURL: String, yearlyPrice: Double, logoURL: String, title: String) {
        self.yearlyPayURL = yearlyPayURL
        self.description = description
        self.monthlyPrice = monthlyPrice
        self.monthlyPayURL = monthlyPayURL
        self.yearlyPrice = yearlyPrice
        self.logoURL = logoURL
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case yearlyPayURL
        case description
        case monthlyPrice
        case monthlyPayURL
        case yearlyPrice
        case logoURL
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(yearlyPayURL, forKey: .yearlyPayURL)
        try container.encode(description, forKey: .description)
        try container.encode(monthlyPrice, forKey: .monthlyPrice)
        try container.encode(monthlyPayURL, forKey: .monthlyPayURL)
        try container.encode(yearlyPrice, forKey: .yearlyPrice)
        try container.encode(logoURL, forKey: .logoURL)
        try container.encode(title, forKey: .title)
    }
}

