//
// PhoneTypes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PhoneTypes: String, Sendable, Codable, CaseIterable {
    case whatsapp = "whatsapp"
    case message = "message"
    case call = "call"
}
