//
// PositionParametersPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PositionParametersPatch: Sendable, Codable, Hashable {

    public var title: String?
    public var makeOwner: Bool?
    public var creds: CredentialsSet?
    public var salary: SalaryParametersRulesCreate?

    public init(title: String? = nil, makeOwner: Bool? = nil, creds: CredentialsSet? = nil, salary: SalaryParametersRulesCreate? = nil) {
        self.title = title
        self.makeOwner = makeOwner
        self.creds = creds
        self.salary = salary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case makeOwner
        case creds
        case salary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(makeOwner, forKey: .makeOwner)
        try container.encodeIfPresent(creds, forKey: .creds)
        try container.encodeIfPresent(salary, forKey: .salary)
    }
}

