//
// PositionResponsesFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PositionResponsesFull: Sendable, Codable, Hashable {

    public var owner: Bool
    public var title: String
    public var creds: CredentialsSet
    public var id: UUID
    public var salary: SalaryResponsesRulesFull

    public init(owner: Bool, title: String, creds: CredentialsSet, id: UUID, salary: SalaryResponsesRulesFull) {
        self.owner = owner
        self.title = title
        self.creds = creds
        self.id = id
        self.salary = salary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case owner
        case title
        case creds
        case id
        case salary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(owner, forKey: .owner)
        try container.encode(title, forKey: .title)
        try container.encode(creds, forKey: .creds)
        try container.encode(id, forKey: .id)
        try container.encode(salary, forKey: .salary)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PositionResponsesFull: Identifiable {}
