//
// PositionParametersCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PositionParametersCreate: Sendable, Codable, Hashable {

    public var salary: SalaryParametersRulesCreate
    public var title: String
    public var creds: CredentialsSet
    public var makeOwner: Bool

    public init(salary: SalaryParametersRulesCreate, title: String, creds: CredentialsSet, makeOwner: Bool) {
        self.salary = salary
        self.title = title
        self.creds = creds
        self.makeOwner = makeOwner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case salary
        case title
        case creds
        case makeOwner
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(salary, forKey: .salary)
        try container.encode(title, forKey: .title)
        try container.encode(creds, forKey: .creds)
        try container.encode(makeOwner, forKey: .makeOwner)
    }
}

