//
// PostTimetablesSearchSlotsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PostTimetablesSearchSlotsRequest: Sendable, Codable, Hashable {
    case typeTimetableParametersSearchSlotComplex(TimetableParametersSearchSlotComplex)
    case typeTimetableParametersSearchSlotProcedure(TimetableParametersSearchSlotProcedure)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTimetableParametersSearchSlotComplex(let value):
            try container.encode(value)
        case .typeTimetableParametersSearchSlotProcedure(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TimetableParametersSearchSlotComplex.self) {
            self = .typeTimetableParametersSearchSlotComplex(value)
        } else if let value = try? container.decode(TimetableParametersSearchSlotProcedure.self) {
            self = .typeTimetableParametersSearchSlotProcedure(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PostTimetablesSearchSlotsRequest"))
        }
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PostTimetablesSearchSlotsRequest: Identifiable {}
