//
// ProcedureResponsesAll.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcedureResponsesAll: Sendable, Codable, Hashable {

    public var procedures: [ProcedureHelpersAllProcedureResponse]

    public init(procedures: [ProcedureHelpersAllProcedureResponse]) {
        self.procedures = procedures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case procedures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(procedures, forKey: .procedures)
    }
}

