//
// ProcedureParametersCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcedureParametersCreate: Sendable, Codable, Hashable {

    public var price: Price
    public var alias: String?
    public var serviceId: UUID
    public var employeeIds: [UUID]
    public var duration: Int64
    public var description: String?
    public var parameters: [ProcedureHelpersCreateParameterRequest]

    public init(price: Price, alias: String? = nil, serviceId: UUID, employeeIds: [UUID], duration: Int64, description: String? = nil, parameters: [ProcedureHelpersCreateParameterRequest]) {
        self.price = price
        self.alias = alias
        self.serviceId = serviceId
        self.employeeIds = employeeIds
        self.duration = duration
        self.description = description
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case price
        case alias
        case serviceId
        case employeeIds
        case duration
        case description
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(price, forKey: .price)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encode(serviceId, forKey: .serviceId)
        try container.encode(employeeIds, forKey: .employeeIds)
        try container.encode(duration, forKey: .duration)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(parameters, forKey: .parameters)
    }
}

