//
// ProcedureHelpersParameterResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProcedureHelpersParameterResponse: Sendable, Codable, Hashable {

    public var id: UUID
    public var _optional: Bool
    public var title: String
    public var cases: [ProcedureHelpersCaseResponse]

    public init(id: UUID, _optional: Bool, title: String, cases: [ProcedureHelpersCaseResponse]) {
        self.id = id
        self._optional = _optional
        self.title = title
        self.cases = cases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case _optional = "optional"
        case title
        case cases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(_optional, forKey: ._optional)
        try container.encode(title, forKey: .title)
        try container.encode(cases, forKey: .cases)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProcedureHelpersParameterResponse: Identifiable {}
