//
// SafeDateInterval.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SafeDateInterval: Sendable, Codable, Hashable {

    public var end: Date
    public var start: Date

    public init(end: Date, start: Date) {
        self.end = end
        self.start = start
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case end
        case start
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(end, forKey: .end)
        try container.encode(start, forKey: .start)
    }
}

