//
// SalaryParametersRulesCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SalaryParametersRulesCreate: Sendable, Codable, Hashable {

    public var grid: [SalaryPaymentType]?
    public var percent: Int64?
    public var wage: Wage?

    public init(grid: [SalaryPaymentType]? = nil, percent: Int64? = nil, wage: Wage? = nil) {
        self.grid = grid
        self.percent = percent
        self.wage = wage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case grid
        case percent
        case wage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(grid, forKey: .grid)
        try container.encodeIfPresent(percent, forKey: .percent)
        try container.encodeIfPresent(wage, forKey: .wage)
    }
}

