//
// SalonType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SalonType: String, Sendable, Codable, CaseIterable {
    case individual = "individual"
    case chain = "chain"
    case master = "master"
}
