//
// ScheduleDay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleDay: Sendable, Codable, Hashable {

    public var workTime: String
    public var offTime: [String]

    public init(workTime: String, offTime: [String]) {
        self.workTime = workTime
        self.offTime = offTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workTime
        case offTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workTime, forKey: .workTime)
        try container.encode(offTime, forKey: .offTime)
    }
}

