//
// SchedulePattern.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SchedulePattern: Sendable, Codable, Hashable {

    public var weekly: ScheduleWeek

    public init(weekly: ScheduleWeek) {
        self.weekly = weekly
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case weekly
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(weekly, forKey: .weekly)
    }
}

