//
// ServiceTags.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** • barbershop → barbershop • nails → nails • massage → massage • spa → spa • cosmetology → cosmetology • hairdressing → hairdressing • epilation → epilation • permanent makeup → permanentMakeup • piercing → piercing • makeup → makeup • brows → brows • lashes → lashes */
public enum ServiceTags: String, Sendable, Codable, CaseIterable {
    case barbershop = "barbershop"
    case nails = "nails"
    case massage = "massage"
    case spa = "spa"
    case cosmetology = "cosmetology"
    case hairdressing = "hairdressing"
    case epilation = "epilation"
    case permanentMakeup = "permanent makeup"
    case piercing = "piercing"
    case makeup = "makeup"
    case brows = "brows"
    case lashes = "lashes"
}
