//
// ServiceHelpersParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServiceHelpersParameter: Sendable, Codable, Hashable {

    public var title: String
    public var cases: [ServiceHelpersCase]
    public var id: UUID

    public init(title: String, cases: [ServiceHelpersCase], id: UUID) {
        self.title = title
        self.cases = cases
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case cases
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(cases, forKey: .cases)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceHelpersParameter: Identifiable {}
