//
// ServiceResponsesAll.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServiceResponsesAll: Sendable, Codable, Hashable {

    public var services: [ServiceHelpersServiceResponse]

    public init(services: [ServiceHelpersServiceResponse]) {
        self.services = services
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case services
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(services, forKey: .services)
    }
}

