//
// TimetableResponsesComplexSlots.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimetableResponsesComplexSlots: Sendable, Codable, Hashable {

    public var timeZoneId: String
    public var slots: [TimetableResponsesComplexSlotsSlot]

    public init(timeZoneId: String, slots: [TimetableResponsesComplexSlotsSlot]) {
        self.timeZoneId = timeZoneId
        self.slots = slots
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeZoneId
        case slots
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeZoneId, forKey: .timeZoneId)
        try container.encode(slots, forKey: .slots)
    }
}

