//
// TimetableResponsesSchedule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimetableResponsesSchedule: Sendable, Codable, Hashable {

    public var timeZoneId: String
    public var owner: String
    public var intervals: [SafeDateInterval]

    public init(timeZoneId: String, owner: String, intervals: [SafeDateInterval]) {
        self.timeZoneId = timeZoneId
        self.owner = owner
        self.intervals = intervals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeZoneId
        case owner
        case intervals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeZoneId, forKey: .timeZoneId)
        try container.encode(owner, forKey: .owner)
        try container.encode(intervals, forKey: .intervals)
    }
}

