//
// TimetableResponsesComplexSlotsSlot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimetableResponsesComplexSlotsSlot: Sendable, Codable, Hashable {

    public var total: SafeDateInterval
    public var chunks: [TimetableResponsesComplexSlotsSlotChunk]

    public init(total: SafeDateInterval, chunks: [TimetableResponsesComplexSlotsSlotChunk]) {
        self.total = total
        self.chunks = chunks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case chunks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(chunks, forKey: .chunks)
    }
}

