//
// UserParametersPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserParametersPatch: Sendable, Codable, Hashable {

    public var avatar: String?
    public var nickname: String?

    public init(avatar: String? = nil, nickname: String? = nil) {
        self.avatar = avatar
        self.nickname = nickname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avatar
        case nickname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(nickname, forKey: .nickname)
    }
}

