//
// VersionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum VersionType: String, Sendable, Codable, CaseIterable {
    case latest = "latest"
    case stable = "stable"
    case unsupported = "unsupported"
}
