//
// AuthResponsesRefresh.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthResponsesRefresh: Codable, JSONEncodable, Hashable {

    public var accessToken: Token
    public var refreshToken: Token?

    public init(accessToken: Token, refreshToken: Token? = nil) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken
        case refreshToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
    }
}

