//
// AuthResponsesSuccessAuth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthResponsesSuccessAuth: Codable, JSONEncodable, Hashable {

    public var user: AuthInternalUserInfo
    public var accessToken: Token
    public var refreshToken: Token

    public init(user: AuthInternalUserInfo, accessToken: Token, refreshToken: Token) {
        self.user = user
        self.accessToken = accessToken
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case accessToken
        case refreshToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(user, forKey: .user)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(refreshToken, forKey: .refreshToken)
    }
}

