//
// ClientResponsesClientInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientResponsesClientInfo: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var user: ClientInternalUserInfo?
    public var alias: String?
    public var contacts: [ContactSharedPrimaryContact]

    public init(id: UUID, user: ClientInternalUserInfo? = nil, alias: String? = nil, contacts: [ContactSharedPrimaryContact]) {
        self.id = id
        self.user = user
        self.alias = alias
        self.contacts = contacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case alias
        case contacts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encode(contacts, forKey: .contacts)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ClientResponsesClientInfo: Identifiable {}
