//
// ClientParametersCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientParametersCreate: Codable, JSONEncodable, Hashable {

    public var alias: String
    public var contact: ClientInternalContact?

    public init(alias: String, contact: ClientInternalContact? = nil) {
        self.alias = alias
        self.contact = contact
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alias
        case contact
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(alias, forKey: .alias)
        try container.encodeIfPresent(contact, forKey: .contact)
    }
}

