//
// ComplexHelpersChunkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComplexHelpersChunkResponse: Codable, JSONEncodable, Hashable {

    public var serviceId: UUID
    public var serviceTags: [TranslatedServiceTag]
    public var id: UUID
    public var serviceTitle: String
    public var order: Int64
    public var procedures: [ComplexHelpersProcedureResponse]

    public init(serviceId: UUID, serviceTags: [TranslatedServiceTag], id: UUID, serviceTitle: String, order: Int64, procedures: [ComplexHelpersProcedureResponse]) {
        self.serviceId = serviceId
        self.serviceTags = serviceTags
        self.id = id
        self.serviceTitle = serviceTitle
        self.order = order
        self.procedures = procedures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case serviceId
        case serviceTags
        case id
        case serviceTitle
        case order
        case procedures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(serviceId, forKey: .serviceId)
        try container.encode(serviceTags, forKey: .serviceTags)
        try container.encode(id, forKey: .id)
        try container.encode(serviceTitle, forKey: .serviceTitle)
        try container.encode(order, forKey: .order)
        try container.encode(procedures, forKey: .procedures)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ComplexHelpersChunkResponse: Identifiable {}
