//
// ComplexHelpersProcedureResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComplexHelpersProcedureResponse: Codable, JSONEncodable, Hashable {

    public var masterId: UUID
    public var masterNickname: String
    public var id: UUID
    public var description: String?
    public var price: Price
    public var duration: Int64
    public var alias: String?
    public var masterAvatar: String

    public init(masterId: UUID, masterNickname: String, id: UUID, description: String? = nil, price: Price, duration: Int64, alias: String? = nil, masterAvatar: String) {
        self.masterId = masterId
        self.masterNickname = masterNickname
        self.id = id
        self.description = description
        self.price = price
        self.duration = duration
        self.alias = alias
        self.masterAvatar = masterAvatar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case masterId
        case masterNickname
        case id
        case description
        case price
        case duration
        case alias
        case masterAvatar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(masterId, forKey: .masterId)
        try container.encode(masterNickname, forKey: .masterNickname)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(price, forKey: .price)
        try container.encode(duration, forKey: .duration)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encode(masterAvatar, forKey: .masterAvatar)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ComplexHelpersProcedureResponse: Identifiable {}
