//
// ComplexHelpersCreateChunkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComplexHelpersCreateChunkRequest: Codable, JSONEncodable, Hashable {

    public var proceduresIds: [UUID]
    public var order: Int64

    public init(proceduresIds: [UUID], order: Int64) {
        self.proceduresIds = proceduresIds
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case proceduresIds
        case order
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(proceduresIds, forKey: .proceduresIds)
        try container.encode(order, forKey: .order)
    }
}

