//
// ComplexHelpersComplexResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComplexHelpersComplexResponse: Codable, JSONEncodable, Hashable {

    public var priceShift: ComplexHelpersPriceShift
    public var id: UUID
    public var alias: String?
    public var chunks: [ComplexHelpersChunkResponse]
    public var description: String?

    public init(priceShift: ComplexHelpersPriceShift, id: UUID, alias: String? = nil, chunks: [ComplexHelpersChunkResponse], description: String? = nil) {
        self.priceShift = priceShift
        self.id = id
        self.alias = alias
        self.chunks = chunks
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case priceShift
        case id
        case alias
        case chunks
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(priceShift, forKey: .priceShift)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encode(chunks, forKey: .chunks)
        try container.encodeIfPresent(description, forKey: .description)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ComplexHelpersComplexResponse: Identifiable {}
