//
// ContactParametersCreatePrimary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContactParametersCreatePrimary: Codable, JSONEncodable, Hashable {

    public var phoneTypes: [PhoneTypes]?
    public var type: ContactType
    public var value: String

    public init(phoneTypes: [PhoneTypes]? = nil, type: ContactType, value: String) {
        self.phoneTypes = phoneTypes
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phoneTypes
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(phoneTypes, forKey: .phoneTypes)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}

