//
// ContactSharedPrimaryContact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContactSharedPrimaryContact: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var phoneTypes: [PhoneTypes]?
    public var type: ContactType
    public var value: String

    public init(id: UUID, phoneTypes: [PhoneTypes]? = nil, type: ContactType, value: String) {
        self.id = id
        self.phoneTypes = phoneTypes
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case phoneTypes
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(phoneTypes, forKey: .phoneTypes)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ContactSharedPrimaryContact: Identifiable {}
