//
// ContactSharedRecoveryContact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContactSharedRecoveryContact: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var value: String
    public var type: ContactType

    public init(id: UUID, value: String, type: ContactType) {
        self.id = id
        self.value = value
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case value
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(value, forKey: .value)
        try container.encode(type, forKey: .type)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ContactSharedRecoveryContact: Identifiable {}
