//
// CustomerResponsesRegistration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerResponsesRegistration: Codable, JSONEncodable, Hashable {

    public var accessToken: Token

    public init(accessToken: Token) {
        self.accessToken = accessToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
    }
}

