//
// CustomerParametersRegistration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerParametersRegistration: Codable, JSONEncodable, Hashable {

    public var contact: CustomerInternalContact?

    public init(contact: CustomerInternalContact? = nil) {
        self.contact = contact
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contact
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contact, forKey: .contact)
    }
}

