//
// EmployeeParametersPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeParametersPatch: Codable, JSONEncodable, Hashable {

    public var positionId: UUID?

    public init(positionId: UUID? = nil) {
        self.positionId = positionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case positionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(positionId, forKey: .positionId)
    }
}

