//
// EmployeeParametersInvite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeParametersInvite: Codable, JSONEncodable, Hashable {

    public var contact: EmployeeInternalContact?
    public var nickname: String?
    public var salonId: UUID
    public var timetable: TimetableParametersCreatePattern?
    public var positionId: UUID

    public init(contact: EmployeeInternalContact? = nil, nickname: String? = nil, salonId: UUID, timetable: TimetableParametersCreatePattern? = nil, positionId: UUID) {
        self.contact = contact
        self.nickname = nickname
        self.salonId = salonId
        self.timetable = timetable
        self.positionId = positionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contact
        case nickname
        case salonId
        case timetable
        case positionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contact, forKey: .contact)
        try container.encodeIfPresent(nickname, forKey: .nickname)
        try container.encode(salonId, forKey: .salonId)
        try container.encodeIfPresent(timetable, forKey: .timetable)
        try container.encode(positionId, forKey: .positionId)
    }
}

