//
// LegacyErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Legacy runtime error payload from ErrorMiddlewareCustom. Deprecated in favor of ApiError. Planned sunset date: 2026-06-30. */
@available(*, deprecated, message: "This schema is deprecated.")
public struct LegacyErrorResponse: Codable, JSONEncodable, Hashable {

    public var error: Bool
    public var reason: String

    public init(error: Bool, reason: String) {
        self.error = error
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encode(reason, forKey: .reason)
    }
}

