//
// ModelAny.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelAny: Codable, JSONEncodable, Hashable {

    public var version: String

    public init(version: String) {
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
    }
}

