//
// OfftimeResponsesFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OfftimeResponsesFull: Codable, JSONEncodable, Hashable {

    public var coefficient: Double
    public var reason: String?
    public var timeZoneId: String
    public var id: UUID
    public var interval: SafeDateInterval

    public init(coefficient: Double, reason: String? = nil, timeZoneId: String, id: UUID, interval: SafeDateInterval) {
        self.coefficient = coefficient
        self.reason = reason
        self.timeZoneId = timeZoneId
        self.id = id
        self.interval = interval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case coefficient
        case reason
        case timeZoneId
        case id
        case interval
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(coefficient, forKey: .coefficient)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encode(timeZoneId, forKey: .timeZoneId)
        try container.encode(id, forKey: .id)
        try container.encode(interval, forKey: .interval)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OfftimeResponsesFull: Identifiable {}
