//
// OfftimeParametersCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OfftimeParametersCreate: Codable, JSONEncodable, Hashable {

    public var reason: String?
    public var interval: SafeDateInterval
    public var coefficient: Double

    public init(reason: String? = nil, interval: SafeDateInterval, coefficient: Double) {
        self.reason = reason
        self.interval = interval
        self.coefficient = coefficient
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
        case interval
        case coefficient
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encode(interval, forKey: .interval)
        try container.encode(coefficient, forKey: .coefficient)
    }
}

