//
// PhoneTypes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PhoneTypes: String, Codable, CaseIterable {
    case whatsapp = "whatsapp"
    case message = "message"
    case call = "call"
}
