//
// PostTimetablesSearchSlots200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PostTimetablesSearchSlots200Response: Codable, JSONEncodable, Hashable {
    case typeTimetableResponsesComplexSlots(TimetableResponsesComplexSlots)
    case typeTimetableResponsesProcedureSlots(TimetableResponsesProcedureSlots)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTimetableResponsesComplexSlots(let value):
            try container.encode(value)
        case .typeTimetableResponsesProcedureSlots(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TimetableResponsesComplexSlots.self) {
            self = .typeTimetableResponsesComplexSlots(value)
        } else if let value = try? container.decode(TimetableResponsesProcedureSlots.self) {
            self = .typeTimetableResponsesProcedureSlots(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PostTimetablesSearchSlots200Response"))
        }
    }
}

