//
// Price.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Price: Codable, JSONEncodable, Hashable {

    public var currency: String
    public var amount: Double

    public init(currency: String, amount: Double) {
        self.currency = currency
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(amount, forKey: .amount)
    }
}

