//
// ProcedureHelpersCreateParameterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcedureHelpersCreateParameterRequest: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var _optional: Bool
    public var cases: [ProcedureHelpersCreateCaseRequest]

    public init(id: UUID, _optional: Bool, cases: [ProcedureHelpersCreateCaseRequest]) {
        self.id = id
        self._optional = _optional
        self.cases = cases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case _optional = "optional"
        case cases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(_optional, forKey: ._optional)
        try container.encode(cases, forKey: .cases)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProcedureHelpersCreateParameterRequest: Identifiable {}
