//
// ProcedureHelpersCasePrice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcedureHelpersCasePrice: Codable, JSONEncodable, Hashable {

    public var fixedValue: Double

    public init(fixedValue: Double) {
        self.fixedValue = fixedValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fixedValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fixedValue, forKey: .fixedValue)
    }
}

