//
// ProcedureHelpersCreateProcedureResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcedureHelpersCreateProcedureResponse: Codable, JSONEncodable, Hashable {

    public var price: Price
    public var serviceTitle: String
    public var masterId: UUID
    public var parameters: [ProcedureHelpersParameterResponse]
    public var masterNickname: String
    public var duration: Int64
    public var alias: String?
    public var serviceTags: [TranslatedServiceTag]
    public var id: UUID
    public var serviceId: UUID
    public var masterAvatar: String
    public var description: String?

    public init(price: Price, serviceTitle: String, masterId: UUID, parameters: [ProcedureHelpersParameterResponse], masterNickname: String, duration: Int64, alias: String? = nil, serviceTags: [TranslatedServiceTag], id: UUID, serviceId: UUID, masterAvatar: String, description: String? = nil) {
        self.price = price
        self.serviceTitle = serviceTitle
        self.masterId = masterId
        self.parameters = parameters
        self.masterNickname = masterNickname
        self.duration = duration
        self.alias = alias
        self.serviceTags = serviceTags
        self.id = id
        self.serviceId = serviceId
        self.masterAvatar = masterAvatar
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case price
        case serviceTitle
        case masterId
        case parameters
        case masterNickname
        case duration
        case alias
        case serviceTags
        case id
        case serviceId
        case masterAvatar
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(price, forKey: .price)
        try container.encode(serviceTitle, forKey: .serviceTitle)
        try container.encode(masterId, forKey: .masterId)
        try container.encode(parameters, forKey: .parameters)
        try container.encode(masterNickname, forKey: .masterNickname)
        try container.encode(duration, forKey: .duration)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encode(serviceTags, forKey: .serviceTags)
        try container.encode(id, forKey: .id)
        try container.encode(serviceId, forKey: .serviceId)
        try container.encode(masterAvatar, forKey: .masterAvatar)
        try container.encodeIfPresent(description, forKey: .description)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProcedureHelpersCreateProcedureResponse: Identifiable {}
