//
// ProcedureHelpersCaseResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcedureHelpersCaseResponse: Codable, JSONEncodable, Hashable {

    public var duration: ProcedureHelpersCaseDuration?
    public var title: String
    public var id: Int64
    public var price: ProcedureHelpersCasePrice?

    public init(duration: ProcedureHelpersCaseDuration? = nil, title: String, id: Int64, price: ProcedureHelpersCasePrice? = nil) {
        self.duration = duration
        self.title = title
        self.id = id
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case duration
        case title
        case id
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encode(title, forKey: .title)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(price, forKey: .price)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProcedureHelpersCaseResponse: Identifiable {}
