//
// ProcedureParametersUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcedureParametersUpdate: Codable, JSONEncodable, Hashable {

    public var duration: Int64?
    public var description: UpdateString?
    public var price: Price?
    public var alias: UpdateString?

    public init(duration: Int64? = nil, description: UpdateString? = nil, price: Price? = nil, alias: UpdateString? = nil) {
        self.duration = duration
        self.description = description
        self.price = price
        self.alias = alias
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case duration
        case description
        case price
        case alias
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(alias, forKey: .alias)
    }
}

