//
// ProcedureHelpersCreateCaseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcedureHelpersCreateCaseRequest: Codable, JSONEncodable, Hashable {

    public var casePrice: ProcedureHelpersCasePrice?
    public var caseDuration: ProcedureHelpersCaseDuration?
    public var id: Int64

    public init(casePrice: ProcedureHelpersCasePrice? = nil, caseDuration: ProcedureHelpersCaseDuration? = nil, id: Int64) {
        self.casePrice = casePrice
        self.caseDuration = caseDuration
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case casePrice
        case caseDuration
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(casePrice, forKey: .casePrice)
        try container.encodeIfPresent(caseDuration, forKey: .caseDuration)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ProcedureHelpersCreateCaseRequest: Identifiable {}
