//
// SalaryPaymentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SalaryPaymentType: Codable, JSONEncodable, Hashable {

    public var percent: Int64

    public init(percent: Int64) {
        self.percent = percent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(percent, forKey: .percent)
    }
}

