//
// SalaryResponsesHelpersService.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SalaryResponsesHelpersService: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var title: String
    public var category: [ServiceTags]
    public var description: String

    public init(id: UUID, title: String, category: [ServiceTags], description: String) {
        self.id = id
        self.title = title
        self.category = category
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case category
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(category, forKey: .category)
        try container.encode(description, forKey: .description)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SalaryResponsesHelpersService: Identifiable {}
