//
// SalaryResponsesHelpersServiceWithPaymentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SalaryResponsesHelpersServiceWithPaymentType: Codable, JSONEncodable, Hashable {

    public var service: SalaryResponsesHelpersService
    public var paymentType: SalaryPaymentType

    public init(service: SalaryResponsesHelpersService, paymentType: SalaryPaymentType) {
        self.service = service
        self.paymentType = paymentType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case service
        case paymentType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(service, forKey: .service)
        try container.encode(paymentType, forKey: .paymentType)
    }
}

