//
// SalonType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SalonType: String, Codable, CaseIterable {
    case individual = "individual"
    case chain = "chain"
    case master = "master"
}
