//
// ScheduleWeek.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScheduleWeek: Codable, JSONEncodable, Hashable {

    public var sunday: ScheduleDay?
    public var friday: ScheduleDay?
    public var thursday: ScheduleDay?
    public var tuesday: ScheduleDay?
    public var monday: ScheduleDay?
    public var saturday: ScheduleDay?
    public var wednesday: ScheduleDay?

    public init(sunday: ScheduleDay? = nil, friday: ScheduleDay? = nil, thursday: ScheduleDay? = nil, tuesday: ScheduleDay? = nil, monday: ScheduleDay? = nil, saturday: ScheduleDay? = nil, wednesday: ScheduleDay? = nil) {
        self.sunday = sunday
        self.friday = friday
        self.thursday = thursday
        self.tuesday = tuesday
        self.monday = monday
        self.saturday = saturday
        self.wednesday = wednesday
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sunday
        case friday
        case thursday
        case tuesday
        case monday
        case saturday
        case wednesday
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sunday, forKey: .sunday)
        try container.encodeIfPresent(friday, forKey: .friday)
        try container.encodeIfPresent(thursday, forKey: .thursday)
        try container.encodeIfPresent(tuesday, forKey: .tuesday)
        try container.encodeIfPresent(monday, forKey: .monday)
        try container.encodeIfPresent(saturday, forKey: .saturday)
        try container.encodeIfPresent(wednesday, forKey: .wednesday)
    }
}

