//
// SearchResponsesHelpersSalon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResponsesHelpersSalon: Codable, JSONEncodable, Hashable {

    public var name: String
    public var point: CoordinatePoint
    public var type: SalonType
    public var isFavorite: Bool
    public var address: Address
    public var id: UUID
    public var logo: String

    public init(name: String, point: CoordinatePoint, type: SalonType, isFavorite: Bool, address: Address, id: UUID, logo: String) {
        self.name = name
        self.point = point
        self.type = type
        self.isFavorite = isFavorite
        self.address = address
        self.id = id
        self.logo = logo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case point
        case type
        case isFavorite
        case address
        case id
        case logo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(point, forKey: .point)
        try container.encode(type, forKey: .type)
        try container.encode(isFavorite, forKey: .isFavorite)
        try container.encode(address, forKey: .address)
        try container.encode(id, forKey: .id)
        try container.encode(logo, forKey: .logo)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SearchResponsesHelpersSalon: Identifiable {}
