//
// ServiceHelpersServiceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceHelpersServiceResponse: Codable, JSONEncodable, Hashable {

    public var tags: [TranslatedServiceTag]
    public var title: String
    public var id: UUID

    public init(tags: [TranslatedServiceTag], title: String, id: UUID) {
        self.tags = tags
        self.title = title
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tags
        case title
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tags, forKey: .tags)
        try container.encode(title, forKey: .title)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceHelpersServiceResponse: Identifiable {}
