//
// ServiceParametersCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceParametersCreate: Codable, JSONEncodable, Hashable {

    public var title: String
    public var tags: [ServiceTags]

    public init(title: String, tags: [ServiceTags]) {
        self.title = title
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(tags, forKey: .tags)
    }
}

