//
// ServiceResponsesRetrieve.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceResponsesRetrieve: Codable, JSONEncodable, Hashable {

    public var title: String
    public var id: UUID
    public var tags: [TranslatedServiceTag]
    public var parameters: [ServiceHelpersParameter]

    public init(title: String, id: UUID, tags: [TranslatedServiceTag], parameters: [ServiceHelpersParameter]) {
        self.title = title
        self.id = id
        self.tags = tags
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case id
        case tags
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(id, forKey: .id)
        try container.encode(tags, forKey: .tags)
        try container.encode(parameters, forKey: .parameters)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceResponsesRetrieve: Identifiable {}
