//
// SubscriptionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionResponse: Codable, JSONEncodable, Hashable {

    public var stripeId: String?
    public var id: UUID
    public var price: Price
    public var title: String
    public var startDate: Date
    public var endDate: Date

    public init(stripeId: String? = nil, id: UUID, price: Price, title: String, startDate: Date, endDate: Date) {
        self.stripeId = stripeId
        self.id = id
        self.price = price
        self.title = title
        self.startDate = startDate
        self.endDate = endDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stripeId
        case id
        case price
        case title
        case startDate
        case endDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(stripeId, forKey: .stripeId)
        try container.encode(id, forKey: .id)
        try container.encode(price, forKey: .price)
        try container.encode(title, forKey: .title)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SubscriptionResponse: Identifiable {}
