//
// TimetableResponsesComplexSlotsSlotChunk.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimetableResponsesComplexSlotsSlotChunk: Codable, JSONEncodable, Hashable {

    public var procedureId: UUID
    public var time: SafeDateInterval
    public var id: UUID

    public init(procedureId: UUID, time: SafeDateInterval, id: UUID) {
        self.procedureId = procedureId
        self.time = time
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case procedureId
        case time
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(procedureId, forKey: .procedureId)
        try container.encode(time, forKey: .time)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TimetableResponsesComplexSlotsSlotChunk: Identifiable {}
