//
// TimetableParametersCreatePattern.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimetableParametersCreatePattern: Codable, JSONEncodable, Hashable {

    public var startAt: Date
    public var endAt: Date?
    public var schedule: SchedulePattern

    public init(startAt: Date, endAt: Date? = nil, schedule: SchedulePattern) {
        self.startAt = startAt
        self.endAt = endAt
        self.schedule = schedule
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startAt
        case endAt
        case schedule
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(startAt, forKey: .startAt)
        try container.encodeIfPresent(endAt, forKey: .endAt)
        try container.encode(schedule, forKey: .schedule)
    }
}

