//
// TimetableResponsesProcedureSlots.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimetableResponsesProcedureSlots: Codable, JSONEncodable, Hashable {

    public var timeZoneId: String
    public var intervals: [SafeDateInterval]

    public init(timeZoneId: String, intervals: [SafeDateInterval]) {
        self.timeZoneId = timeZoneId
        self.intervals = intervals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeZoneId
        case intervals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeZoneId, forKey: .timeZoneId)
        try container.encode(intervals, forKey: .intervals)
    }
}

