//
// TimetableParametersSearchSlotComplex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimetableParametersSearchSlotComplex: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var chunks: [UUID]

    public init(id: UUID, chunks: [UUID]) {
        self.id = id
        self.chunks = chunks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case chunks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(chunks, forKey: .chunks)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TimetableParametersSearchSlotComplex: Identifiable {}
