//
// Token.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Token: Codable, JSONEncodable, Hashable {

    public var value: String
    public var expiration: Date

    public init(value: String, expiration: Date) {
        self.value = value
        self.expiration = expiration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case expiration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(expiration, forKey: .expiration)
    }
}

