//
// TranslatedServiceTag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TranslatedServiceTag: Codable, JSONEncodable, Hashable {

    public var tag: ServiceTags
    public var translate: String

    public init(tag: ServiceTags, translate: String) {
        self.tag = tag
        self.translate = translate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tag
        case translate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tag, forKey: .tag)
        try container.encode(translate, forKey: .translate)
    }
}

