//
// UploadRouterV1Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UploadRouterV1Input: Codable, JSONEncodable, Hashable {

    public var image: File

    public init(image: File) {
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
    }
}

