//
// UserResponsesUserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserResponsesUserInfo: Codable, JSONEncodable, Hashable {

    public var avatar: String
    public var haveCustomer: Bool
    public var haveEmployee: Bool
    public var nickname: String
    public var id: UUID

    public init(avatar: String, haveCustomer: Bool, haveEmployee: Bool, nickname: String, id: UUID) {
        self.avatar = avatar
        self.haveCustomer = haveCustomer
        self.haveEmployee = haveEmployee
        self.nickname = nickname
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avatar
        case haveCustomer
        case haveEmployee
        case nickname
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(avatar, forKey: .avatar)
        try container.encode(haveCustomer, forKey: .haveCustomer)
        try container.encode(haveEmployee, forKey: .haveEmployee)
        try container.encode(nickname, forKey: .nickname)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserResponsesUserInfo: Identifiable {}
