//
// VersionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum VersionType: String, Codable, CaseIterable {
    case latest = "latest"
    case stable = "stable"
    case unsupported = "unsupported"
}
