//
// Wage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Wage: Codable, JSONEncodable, Hashable {

    public var price: Price
    public var period: String

    public init(price: Price, period: String) {
        self.price = price
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case price
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(price, forKey: .price)
        try container.encode(period, forKey: .period)
    }
}

