//
// WorkspaceResponsesFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkspaceResponsesFull: Codable, JSONEncodable, Hashable {

    public var address: Address
    public var isActive: Bool
    public var timeZoneId: String
    public var description: String?
    public var point: CoordinatePoint
    public var name: String
    public var localeId: String
    public var id: UUID
    public var employeeToken: Token
    public var type: SalonType
    public var logo: String

    public init(address: Address, isActive: Bool, timeZoneId: String, description: String? = nil, point: CoordinatePoint, name: String, localeId: String, id: UUID, employeeToken: Token, type: SalonType, logo: String) {
        self.address = address
        self.isActive = isActive
        self.timeZoneId = timeZoneId
        self.description = description
        self.point = point
        self.name = name
        self.localeId = localeId
        self.id = id
        self.employeeToken = employeeToken
        self.type = type
        self.logo = logo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case isActive
        case timeZoneId
        case description
        case point
        case name
        case localeId
        case id
        case employeeToken
        case type
        case logo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(timeZoneId, forKey: .timeZoneId)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(point, forKey: .point)
        try container.encode(name, forKey: .name)
        try container.encode(localeId, forKey: .localeId)
        try container.encode(id, forKey: .id)
        try container.encode(employeeToken, forKey: .employeeToken)
        try container.encode(type, forKey: .type)
        try container.encode(logo, forKey: .logo)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension WorkspaceResponsesFull: Identifiable {}
