//
// WorkspaceParametersCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkspaceParametersCreate: Codable, JSONEncodable, Hashable {

    public var timeZoneId: String
    public var timetable: TimetableParametersCreatePattern?
    public var localeId: String
    public var logo: String?
    public var contact: WorkspaceInternalContact?
    public var address: Address
    public var name: String
    public var description: String?
    public var type: SalonType
    public var point: CoordinatePoint

    public init(timeZoneId: String, timetable: TimetableParametersCreatePattern? = nil, localeId: String, logo: String? = nil, contact: WorkspaceInternalContact? = nil, address: Address, name: String, description: String? = nil, type: SalonType, point: CoordinatePoint) {
        self.timeZoneId = timeZoneId
        self.timetable = timetable
        self.localeId = localeId
        self.logo = logo
        self.contact = contact
        self.address = address
        self.name = name
        self.description = description
        self.type = type
        self.point = point
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeZoneId
        case timetable
        case localeId
        case logo
        case contact
        case address
        case name
        case description
        case type
        case point
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeZoneId, forKey: .timeZoneId)
        try container.encodeIfPresent(timetable, forKey: .timetable)
        try container.encode(localeId, forKey: .localeId)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encodeIfPresent(contact, forKey: .contact)
        try container.encode(address, forKey: .address)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(type, forKey: .type)
        try container.encode(point, forKey: .point)
    }
}

