//
// WorkspaceParametersPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkspaceParametersPatch: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var logo: String?
    public var type: SalonType?

    public init(name: String? = nil, description: String? = nil, logo: String? = nil, type: SalonType? = nil) {
        self.name = name
        self.description = description
        self.logo = logo
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case logo
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

