/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Any
 */
export interface Any {
    /**
     * 
     * @type {string}
     * @memberof Any
     */
    version: string;
}

/**
 * Check if a given object implements the Any interface.
 */
export function instanceOfAny(value: object): value is Any {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function AnyFromJSON(json: any): Any {
    return AnyFromJSONTyped(json, false);
}

export function AnyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Any {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
    };
}

export function AnyToJSON(json: any): Any {
    return AnyToJSONTyped(json, false);
}

export function AnyToJSONTyped(value?: Any | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
    };
}

