/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthInternalUserInfo } from './AuthInternalUserInfo';
import {
    AuthInternalUserInfoFromJSON,
    AuthInternalUserInfoFromJSONTyped,
    AuthInternalUserInfoToJSON,
    AuthInternalUserInfoToJSONTyped,
} from './AuthInternalUserInfo';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface AuthResponsesSuccessAuth
 */
export interface AuthResponsesSuccessAuth {
    /**
     * 
     * @type {AuthInternalUserInfo}
     * @memberof AuthResponsesSuccessAuth
     */
    user: AuthInternalUserInfo;
    /**
     * 
     * @type {Token}
     * @memberof AuthResponsesSuccessAuth
     */
    accessToken: Token;
    /**
     * 
     * @type {Token}
     * @memberof AuthResponsesSuccessAuth
     */
    refreshToken: Token;
}

/**
 * Check if a given object implements the AuthResponsesSuccessAuth interface.
 */
export function instanceOfAuthResponsesSuccessAuth(value: object): value is AuthResponsesSuccessAuth {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function AuthResponsesSuccessAuthFromJSON(json: any): AuthResponsesSuccessAuth {
    return AuthResponsesSuccessAuthFromJSONTyped(json, false);
}

export function AuthResponsesSuccessAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponsesSuccessAuth {
    if (json == null) {
        return json;
    }
    return {
        
        'user': AuthInternalUserInfoFromJSON(json['user']),
        'accessToken': TokenFromJSON(json['accessToken']),
        'refreshToken': TokenFromJSON(json['refreshToken']),
    };
}

export function AuthResponsesSuccessAuthToJSON(json: any): AuthResponsesSuccessAuth {
    return AuthResponsesSuccessAuthToJSONTyped(json, false);
}

export function AuthResponsesSuccessAuthToJSONTyped(value?: AuthResponsesSuccessAuth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': AuthInternalUserInfoToJSON(value['user']),
        'accessToken': TokenToJSON(value['accessToken']),
        'refreshToken': TokenToJSON(value['refreshToken']),
    };
}

