/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthParametersRefreshingToken
 */
export interface AuthParametersRefreshingToken {
    /**
     * 
     * @type {string}
     * @memberof AuthParametersRefreshingToken
     */
    token: string;
}

/**
 * Check if a given object implements the AuthParametersRefreshingToken interface.
 */
export function instanceOfAuthParametersRefreshingToken(value: object): value is AuthParametersRefreshingToken {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthParametersRefreshingTokenFromJSON(json: any): AuthParametersRefreshingToken {
    return AuthParametersRefreshingTokenFromJSONTyped(json, false);
}

export function AuthParametersRefreshingTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthParametersRefreshingToken {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function AuthParametersRefreshingTokenToJSON(json: any): AuthParametersRefreshingToken {
    return AuthParametersRefreshingTokenToJSONTyped(json, false);
}

export function AuthParametersRefreshingTokenToJSONTyped(value?: AuthParametersRefreshingToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

