/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface AuthResponsesRefresh
 */
export interface AuthResponsesRefresh {
    /**
     * 
     * @type {Token}
     * @memberof AuthResponsesRefresh
     */
    accessToken: Token;
    /**
     * 
     * @type {Token}
     * @memberof AuthResponsesRefresh
     */
    refreshToken?: Token;
}

/**
 * Check if a given object implements the AuthResponsesRefresh interface.
 */
export function instanceOfAuthResponsesRefresh(value: object): value is AuthResponsesRefresh {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function AuthResponsesRefreshFromJSON(json: any): AuthResponsesRefresh {
    return AuthResponsesRefreshFromJSONTyped(json, false);
}

export function AuthResponsesRefreshFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponsesRefresh {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': TokenFromJSON(json['accessToken']),
        'refreshToken': json['refreshToken'] == null ? undefined : TokenFromJSON(json['refreshToken']),
    };
}

export function AuthResponsesRefreshToJSON(json: any): AuthResponsesRefresh {
    return AuthResponsesRefreshToJSONTyped(json, false);
}

export function AuthResponsesRefreshToJSONTyped(value?: AuthResponsesRefresh | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': TokenToJSON(value['accessToken']),
        'refreshToken': TokenToJSON(value['refreshToken']),
    };
}

