/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthInternalUserInfo
 */
export interface AuthInternalUserInfo {
    /**
     * 
     * @type {string}
     * @memberof AuthInternalUserInfo
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthInternalUserInfo
     */
    haveCustomer: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthInternalUserInfo
     */
    haveEmployee: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthInternalUserInfo
     */
    haveContact: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthInternalUserInfo
     */
    nickname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthInternalUserInfo
     */
    avatar?: string | null;
}

/**
 * Check if a given object implements the AuthInternalUserInfo interface.
 */
export function instanceOfAuthInternalUserInfo(value: object): value is AuthInternalUserInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('haveCustomer' in value) || value['haveCustomer'] === undefined) return false;
    if (!('haveEmployee' in value) || value['haveEmployee'] === undefined) return false;
    if (!('haveContact' in value) || value['haveContact'] === undefined) return false;
    return true;
}

export function AuthInternalUserInfoFromJSON(json: any): AuthInternalUserInfo {
    return AuthInternalUserInfoFromJSONTyped(json, false);
}

export function AuthInternalUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthInternalUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'haveCustomer': json['haveCustomer'],
        'haveEmployee': json['haveEmployee'],
        'haveContact': json['haveContact'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
    };
}

export function AuthInternalUserInfoToJSON(json: any): AuthInternalUserInfo {
    return AuthInternalUserInfoToJSONTyped(json, false);
}

export function AuthInternalUserInfoToJSONTyped(value?: AuthInternalUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'haveCustomer': value['haveCustomer'],
        'haveEmployee': value['haveEmployee'],
        'haveContact': value['haveContact'],
        'nickname': value['nickname'],
        'avatar': value['avatar'],
    };
}

