/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthParametersGoogleToken
 */
export interface AuthParametersGoogleToken {
    /**
     * 
     * @type {string}
     * @memberof AuthParametersGoogleToken
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthParametersGoogleToken
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof AuthParametersGoogleToken
     */
    firstName?: string | null;
}

/**
 * Check if a given object implements the AuthParametersGoogleToken interface.
 */
export function instanceOfAuthParametersGoogleToken(value: object): value is AuthParametersGoogleToken {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthParametersGoogleTokenFromJSON(json: any): AuthParametersGoogleToken {
    return AuthParametersGoogleTokenFromJSONTyped(json, false);
}

export function AuthParametersGoogleTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthParametersGoogleToken {
    if (json == null) {
        return json;
    }
    return {
        
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'token': json['token'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
    };
}

export function AuthParametersGoogleTokenToJSON(json: any): AuthParametersGoogleToken {
    return AuthParametersGoogleTokenToJSONTyped(json, false);
}

export function AuthParametersGoogleTokenToJSONTyped(value?: AuthParametersGoogleToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lastName': value['lastName'],
        'token': value['token'],
        'firstName': value['firstName'],
    };
}

