/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthParametersAppleToken
 */
export interface AuthParametersAppleToken {
    /**
     * 
     * @type {string}
     * @memberof AuthParametersAppleToken
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof AuthParametersAppleToken
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthParametersAppleToken
     */
    firstName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthParametersAppleToken
     */
    emailVerified?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AuthParametersAppleToken
     */
    lastName?: string | null;
}

/**
 * Check if a given object implements the AuthParametersAppleToken interface.
 */
export function instanceOfAuthParametersAppleToken(value: object): value is AuthParametersAppleToken {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthParametersAppleTokenFromJSON(json: any): AuthParametersAppleToken {
    return AuthParametersAppleTokenFromJSONTyped(json, false);
}

export function AuthParametersAppleTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthParametersAppleToken {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'emailVerified': json['emailVerified'] == null ? undefined : json['emailVerified'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function AuthParametersAppleTokenToJSON(json: any): AuthParametersAppleToken {
    return AuthParametersAppleTokenToJSONTyped(json, false);
}

export function AuthParametersAppleTokenToJSONTyped(value?: AuthParametersAppleToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'email': value['email'],
        'firstName': value['firstName'],
        'emailVerified': value['emailVerified'],
        'lastName': value['lastName'],
    };
}

