/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactSharedPrimaryContact } from './ContactSharedPrimaryContact';
import {
    ContactSharedPrimaryContactFromJSON,
    ContactSharedPrimaryContactFromJSONTyped,
    ContactSharedPrimaryContactToJSON,
    ContactSharedPrimaryContactToJSONTyped,
} from './ContactSharedPrimaryContact';
import type { ClientInternalUserInfo } from './ClientInternalUserInfo';
import {
    ClientInternalUserInfoFromJSON,
    ClientInternalUserInfoFromJSONTyped,
    ClientInternalUserInfoToJSON,
    ClientInternalUserInfoToJSONTyped,
} from './ClientInternalUserInfo';

/**
 * 
 * @export
 * @interface ClientResponsesClientInfo
 */
export interface ClientResponsesClientInfo {
    /**
     * 
     * @type {string}
     * @memberof ClientResponsesClientInfo
     */
    id: string;
    /**
     * 
     * @type {ClientInternalUserInfo}
     * @memberof ClientResponsesClientInfo
     */
    user?: ClientInternalUserInfo;
    /**
     * 
     * @type {string}
     * @memberof ClientResponsesClientInfo
     */
    alias?: string | null;
    /**
     * 
     * @type {Array<ContactSharedPrimaryContact>}
     * @memberof ClientResponsesClientInfo
     */
    contacts: Array<ContactSharedPrimaryContact>;
}

/**
 * Check if a given object implements the ClientResponsesClientInfo interface.
 */
export function instanceOfClientResponsesClientInfo(value: object): value is ClientResponsesClientInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    return true;
}

export function ClientResponsesClientInfoFromJSON(json: any): ClientResponsesClientInfo {
    return ClientResponsesClientInfoFromJSONTyped(json, false);
}

export function ClientResponsesClientInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientResponsesClientInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': json['user'] == null ? undefined : ClientInternalUserInfoFromJSON(json['user']),
        'alias': json['alias'] == null ? undefined : json['alias'],
        'contacts': ((json['contacts'] as Array<any>).map(ContactSharedPrimaryContactFromJSON)),
    };
}

export function ClientResponsesClientInfoToJSON(json: any): ClientResponsesClientInfo {
    return ClientResponsesClientInfoToJSONTyped(json, false);
}

export function ClientResponsesClientInfoToJSONTyped(value?: ClientResponsesClientInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user': ClientInternalUserInfoToJSON(value['user']),
        'alias': value['alias'],
        'contacts': ((value['contacts'] as Array<any>).map(ContactSharedPrimaryContactToJSON)),
    };
}

