/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientInternalUserInfo
 */
export interface ClientInternalUserInfo {
    /**
     * 
     * @type {string}
     * @memberof ClientInternalUserInfo
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof ClientInternalUserInfo
     */
    avatar: string;
}

/**
 * Check if a given object implements the ClientInternalUserInfo interface.
 */
export function instanceOfClientInternalUserInfo(value: object): value is ClientInternalUserInfo {
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    return true;
}

export function ClientInternalUserInfoFromJSON(json: any): ClientInternalUserInfo {
    return ClientInternalUserInfoFromJSONTyped(json, false);
}

export function ClientInternalUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientInternalUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
        'avatar': json['avatar'],
    };
}

export function ClientInternalUserInfoToJSON(json: any): ClientInternalUserInfo {
    return ClientInternalUserInfoToJSONTyped(json, false);
}

export function ClientInternalUserInfoToJSONTyped(value?: ClientInternalUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'avatar': value['avatar'],
    };
}

