/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplexHelpersComplexResponse } from './ComplexHelpersComplexResponse';
import {
    ComplexHelpersComplexResponseFromJSON,
    ComplexHelpersComplexResponseFromJSONTyped,
    ComplexHelpersComplexResponseToJSON,
    ComplexHelpersComplexResponseToJSONTyped,
} from './ComplexHelpersComplexResponse';

/**
 * 
 * @export
 * @interface ComplexResponsesAll
 */
export interface ComplexResponsesAll {
    /**
     * 
     * @type {Array<ComplexHelpersComplexResponse>}
     * @memberof ComplexResponsesAll
     */
    complexes: Array<ComplexHelpersComplexResponse>;
}

/**
 * Check if a given object implements the ComplexResponsesAll interface.
 */
export function instanceOfComplexResponsesAll(value: object): value is ComplexResponsesAll {
    if (!('complexes' in value) || value['complexes'] === undefined) return false;
    return true;
}

export function ComplexResponsesAllFromJSON(json: any): ComplexResponsesAll {
    return ComplexResponsesAllFromJSONTyped(json, false);
}

export function ComplexResponsesAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexResponsesAll {
    if (json == null) {
        return json;
    }
    return {
        
        'complexes': ((json['complexes'] as Array<any>).map(ComplexHelpersComplexResponseFromJSON)),
    };
}

export function ComplexResponsesAllToJSON(json: any): ComplexResponsesAll {
    return ComplexResponsesAllToJSONTyped(json, false);
}

export function ComplexResponsesAllToJSONTyped(value?: ComplexResponsesAll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'complexes': ((value['complexes'] as Array<any>).map(ComplexHelpersComplexResponseToJSON)),
    };
}

