/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TranslatedServiceTag } from './TranslatedServiceTag';
import {
    TranslatedServiceTagFromJSON,
    TranslatedServiceTagFromJSONTyped,
    TranslatedServiceTagToJSON,
    TranslatedServiceTagToJSONTyped,
} from './TranslatedServiceTag';
import type { ComplexHelpersProcedureResponse } from './ComplexHelpersProcedureResponse';
import {
    ComplexHelpersProcedureResponseFromJSON,
    ComplexHelpersProcedureResponseFromJSONTyped,
    ComplexHelpersProcedureResponseToJSON,
    ComplexHelpersProcedureResponseToJSONTyped,
} from './ComplexHelpersProcedureResponse';

/**
 * 
 * @export
 * @interface ComplexHelpersChunkResponse
 */
export interface ComplexHelpersChunkResponse {
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersChunkResponse
     */
    serviceId: string;
    /**
     * 
     * @type {Array<TranslatedServiceTag>}
     * @memberof ComplexHelpersChunkResponse
     */
    serviceTags: Array<TranslatedServiceTag>;
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersChunkResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersChunkResponse
     */
    serviceTitle: string;
    /**
     * 
     * @type {number}
     * @memberof ComplexHelpersChunkResponse
     */
    order: number;
    /**
     * 
     * @type {Array<ComplexHelpersProcedureResponse>}
     * @memberof ComplexHelpersChunkResponse
     */
    procedures: Array<ComplexHelpersProcedureResponse>;
}

/**
 * Check if a given object implements the ComplexHelpersChunkResponse interface.
 */
export function instanceOfComplexHelpersChunkResponse(value: object): value is ComplexHelpersChunkResponse {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('serviceTags' in value) || value['serviceTags'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('serviceTitle' in value) || value['serviceTitle'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('procedures' in value) || value['procedures'] === undefined) return false;
    return true;
}

export function ComplexHelpersChunkResponseFromJSON(json: any): ComplexHelpersChunkResponse {
    return ComplexHelpersChunkResponseFromJSONTyped(json, false);
}

export function ComplexHelpersChunkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexHelpersChunkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['serviceId'],
        'serviceTags': ((json['serviceTags'] as Array<any>).map(TranslatedServiceTagFromJSON)),
        'id': json['id'],
        'serviceTitle': json['serviceTitle'],
        'order': json['order'],
        'procedures': ((json['procedures'] as Array<any>).map(ComplexHelpersProcedureResponseFromJSON)),
    };
}

export function ComplexHelpersChunkResponseToJSON(json: any): ComplexHelpersChunkResponse {
    return ComplexHelpersChunkResponseToJSONTyped(json, false);
}

export function ComplexHelpersChunkResponseToJSONTyped(value?: ComplexHelpersChunkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceId': value['serviceId'],
        'serviceTags': ((value['serviceTags'] as Array<any>).map(TranslatedServiceTagToJSON)),
        'id': value['id'],
        'serviceTitle': value['serviceTitle'],
        'order': value['order'],
        'procedures': ((value['procedures'] as Array<any>).map(ComplexHelpersProcedureResponseToJSON)),
    };
}

