/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplexHelpersCreateChunkRequest } from './ComplexHelpersCreateChunkRequest';
import {
    ComplexHelpersCreateChunkRequestFromJSON,
    ComplexHelpersCreateChunkRequestFromJSONTyped,
    ComplexHelpersCreateChunkRequestToJSON,
    ComplexHelpersCreateChunkRequestToJSONTyped,
} from './ComplexHelpersCreateChunkRequest';
import type { ComplexHelpersPriceShift } from './ComplexHelpersPriceShift';
import {
    ComplexHelpersPriceShiftFromJSON,
    ComplexHelpersPriceShiftFromJSONTyped,
    ComplexHelpersPriceShiftToJSON,
    ComplexHelpersPriceShiftToJSONTyped,
} from './ComplexHelpersPriceShift';

/**
 * 
 * @export
 * @interface ComplexParametersCreate
 */
export interface ComplexParametersCreate {
    /**
     * 
     * @type {ComplexHelpersPriceShift}
     * @memberof ComplexParametersCreate
     */
    priceShift: ComplexHelpersPriceShift;
    /**
     * 
     * @type {Array<ComplexHelpersCreateChunkRequest>}
     * @memberof ComplexParametersCreate
     */
    chunks: Array<ComplexHelpersCreateChunkRequest>;
    /**
     * 
     * @type {string}
     * @memberof ComplexParametersCreate
     */
    alias?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ComplexParametersCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ComplexParametersCreate interface.
 */
export function instanceOfComplexParametersCreate(value: object): value is ComplexParametersCreate {
    if (!('priceShift' in value) || value['priceShift'] === undefined) return false;
    if (!('chunks' in value) || value['chunks'] === undefined) return false;
    return true;
}

export function ComplexParametersCreateFromJSON(json: any): ComplexParametersCreate {
    return ComplexParametersCreateFromJSONTyped(json, false);
}

export function ComplexParametersCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexParametersCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'priceShift': ComplexHelpersPriceShiftFromJSON(json['priceShift']),
        'chunks': ((json['chunks'] as Array<any>).map(ComplexHelpersCreateChunkRequestFromJSON)),
        'alias': json['alias'] == null ? undefined : json['alias'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ComplexParametersCreateToJSON(json: any): ComplexParametersCreate {
    return ComplexParametersCreateToJSONTyped(json, false);
}

export function ComplexParametersCreateToJSONTyped(value?: ComplexParametersCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceShift': ComplexHelpersPriceShiftToJSON(value['priceShift']),
        'chunks': ((value['chunks'] as Array<any>).map(ComplexHelpersCreateChunkRequestToJSON)),
        'alias': value['alias'],
        'description': value['description'],
    };
}

