/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComplexHelpersPriceShift
 */
export interface ComplexHelpersPriceShift {
    /**
     * 
     * @type {number}
     * @memberof ComplexHelpersPriceShift
     */
    percent: number;
}

/**
 * Check if a given object implements the ComplexHelpersPriceShift interface.
 */
export function instanceOfComplexHelpersPriceShift(value: object): value is ComplexHelpersPriceShift {
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function ComplexHelpersPriceShiftFromJSON(json: any): ComplexHelpersPriceShift {
    return ComplexHelpersPriceShiftFromJSONTyped(json, false);
}

export function ComplexHelpersPriceShiftFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexHelpersPriceShift {
    if (json == null) {
        return json;
    }
    return {
        
        'percent': json['percent'],
    };
}

export function ComplexHelpersPriceShiftToJSON(json: any): ComplexHelpersPriceShift {
    return ComplexHelpersPriceShiftToJSONTyped(json, false);
}

export function ComplexHelpersPriceShiftToJSONTyped(value?: ComplexHelpersPriceShift | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percent': value['percent'],
    };
}

