/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplexHelpersPriceShift } from './ComplexHelpersPriceShift';
import {
    ComplexHelpersPriceShiftFromJSON,
    ComplexHelpersPriceShiftFromJSONTyped,
    ComplexHelpersPriceShiftToJSON,
    ComplexHelpersPriceShiftToJSONTyped,
} from './ComplexHelpersPriceShift';
import type { ComplexHelpersChunkResponse } from './ComplexHelpersChunkResponse';
import {
    ComplexHelpersChunkResponseFromJSON,
    ComplexHelpersChunkResponseFromJSONTyped,
    ComplexHelpersChunkResponseToJSON,
    ComplexHelpersChunkResponseToJSONTyped,
} from './ComplexHelpersChunkResponse';

/**
 * 
 * @export
 * @interface ComplexResponsesRetrieve
 */
export interface ComplexResponsesRetrieve {
    /**
     * 
     * @type {ComplexHelpersPriceShift}
     * @memberof ComplexResponsesRetrieve
     */
    priceShift: ComplexHelpersPriceShift;
    /**
     * 
     * @type {string}
     * @memberof ComplexResponsesRetrieve
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ComplexResponsesRetrieve
     */
    alias?: string | null;
    /**
     * 
     * @type {Array<ComplexHelpersChunkResponse>}
     * @memberof ComplexResponsesRetrieve
     */
    chunks: Array<ComplexHelpersChunkResponse>;
    /**
     * 
     * @type {string}
     * @memberof ComplexResponsesRetrieve
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ComplexResponsesRetrieve interface.
 */
export function instanceOfComplexResponsesRetrieve(value: object): value is ComplexResponsesRetrieve {
    if (!('priceShift' in value) || value['priceShift'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('chunks' in value) || value['chunks'] === undefined) return false;
    return true;
}

export function ComplexResponsesRetrieveFromJSON(json: any): ComplexResponsesRetrieve {
    return ComplexResponsesRetrieveFromJSONTyped(json, false);
}

export function ComplexResponsesRetrieveFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexResponsesRetrieve {
    if (json == null) {
        return json;
    }
    return {
        
        'priceShift': ComplexHelpersPriceShiftFromJSON(json['priceShift']),
        'id': json['id'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'chunks': ((json['chunks'] as Array<any>).map(ComplexHelpersChunkResponseFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ComplexResponsesRetrieveToJSON(json: any): ComplexResponsesRetrieve {
    return ComplexResponsesRetrieveToJSONTyped(json, false);
}

export function ComplexResponsesRetrieveToJSONTyped(value?: ComplexResponsesRetrieve | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceShift': ComplexHelpersPriceShiftToJSON(value['priceShift']),
        'id': value['id'],
        'alias': value['alias'],
        'chunks': ((value['chunks'] as Array<any>).map(ComplexHelpersChunkResponseToJSON)),
        'description': value['description'],
    };
}

