/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComplexHelpersCreateChunkRequest
 */
export interface ComplexHelpersCreateChunkRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ComplexHelpersCreateChunkRequest
     */
    proceduresIds: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ComplexHelpersCreateChunkRequest
     */
    order: number;
}

/**
 * Check if a given object implements the ComplexHelpersCreateChunkRequest interface.
 */
export function instanceOfComplexHelpersCreateChunkRequest(value: object): value is ComplexHelpersCreateChunkRequest {
    if (!('proceduresIds' in value) || value['proceduresIds'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ComplexHelpersCreateChunkRequestFromJSON(json: any): ComplexHelpersCreateChunkRequest {
    return ComplexHelpersCreateChunkRequestFromJSONTyped(json, false);
}

export function ComplexHelpersCreateChunkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexHelpersCreateChunkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'proceduresIds': json['proceduresIds'],
        'order': json['order'],
    };
}

export function ComplexHelpersCreateChunkRequestToJSON(json: any): ComplexHelpersCreateChunkRequest {
    return ComplexHelpersCreateChunkRequestToJSONTyped(json, false);
}

export function ComplexHelpersCreateChunkRequestToJSONTyped(value?: ComplexHelpersCreateChunkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proceduresIds': value['proceduresIds'],
        'order': value['order'],
    };
}

