/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';

/**
 * 
 * @export
 * @interface ComplexHelpersProcedureResponse
 */
export interface ComplexHelpersProcedureResponse {
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersProcedureResponse
     */
    masterId: string;
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersProcedureResponse
     */
    masterNickname: string;
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersProcedureResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersProcedureResponse
     */
    description?: string | null;
    /**
     * 
     * @type {Price}
     * @memberof ComplexHelpersProcedureResponse
     */
    price: Price;
    /**
     * 
     * @type {number}
     * @memberof ComplexHelpersProcedureResponse
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersProcedureResponse
     */
    alias?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ComplexHelpersProcedureResponse
     */
    masterAvatar: string;
}

/**
 * Check if a given object implements the ComplexHelpersProcedureResponse interface.
 */
export function instanceOfComplexHelpersProcedureResponse(value: object): value is ComplexHelpersProcedureResponse {
    if (!('masterId' in value) || value['masterId'] === undefined) return false;
    if (!('masterNickname' in value) || value['masterNickname'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('masterAvatar' in value) || value['masterAvatar'] === undefined) return false;
    return true;
}

export function ComplexHelpersProcedureResponseFromJSON(json: any): ComplexHelpersProcedureResponse {
    return ComplexHelpersProcedureResponseFromJSONTyped(json, false);
}

export function ComplexHelpersProcedureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexHelpersProcedureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'masterId': json['masterId'],
        'masterNickname': json['masterNickname'],
        'id': json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': PriceFromJSON(json['price']),
        'duration': json['duration'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'masterAvatar': json['masterAvatar'],
    };
}

export function ComplexHelpersProcedureResponseToJSON(json: any): ComplexHelpersProcedureResponse {
    return ComplexHelpersProcedureResponseToJSONTyped(json, false);
}

export function ComplexHelpersProcedureResponseToJSONTyped(value?: ComplexHelpersProcedureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'masterId': value['masterId'],
        'masterNickname': value['masterNickname'],
        'id': value['id'],
        'description': value['description'],
        'price': PriceToJSON(value['price']),
        'duration': value['duration'],
        'alias': value['alias'],
        'masterAvatar': value['masterAvatar'],
    };
}

