/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhoneTypes } from './PhoneTypes';
import {
    PhoneTypesFromJSON,
    PhoneTypesFromJSONTyped,
    PhoneTypesToJSON,
    PhoneTypesToJSONTyped,
} from './PhoneTypes';

/**
 * 
 * @export
 * @interface ContactParametersUpdateContact
 */
export interface ContactParametersUpdateContact {
    /**
     * 
     * @type {Array<PhoneTypes>}
     * @memberof ContactParametersUpdateContact
     */
    phoneTypes?: Array<PhoneTypes> | null;
}

/**
 * Check if a given object implements the ContactParametersUpdateContact interface.
 */
export function instanceOfContactParametersUpdateContact(value: object): value is ContactParametersUpdateContact {
    return true;
}

export function ContactParametersUpdateContactFromJSON(json: any): ContactParametersUpdateContact {
    return ContactParametersUpdateContactFromJSONTyped(json, false);
}

export function ContactParametersUpdateContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactParametersUpdateContact {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneTypes': json['phoneTypes'] == null ? undefined : ((json['phoneTypes'] as Array<any>).map(PhoneTypesFromJSON)),
    };
}

export function ContactParametersUpdateContactToJSON(json: any): ContactParametersUpdateContact {
    return ContactParametersUpdateContactToJSONTyped(json, false);
}

export function ContactParametersUpdateContactToJSONTyped(value?: ContactParametersUpdateContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneTypes': value['phoneTypes'] == null ? undefined : ((value['phoneTypes'] as Array<any>).map(PhoneTypesToJSON)),
    };
}

