/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactType } from './ContactType';
import {
    ContactTypeFromJSON,
    ContactTypeFromJSONTyped,
    ContactTypeToJSON,
    ContactTypeToJSONTyped,
} from './ContactType';

/**
 * 
 * @export
 * @interface ContactParametersCreateRecovery
 */
export interface ContactParametersCreateRecovery {
    /**
     * 
     * @type {string}
     * @memberof ContactParametersCreateRecovery
     */
    value: string;
    /**
     * 
     * @type {ContactType}
     * @memberof ContactParametersCreateRecovery
     */
    type: ContactType;
}



/**
 * Check if a given object implements the ContactParametersCreateRecovery interface.
 */
export function instanceOfContactParametersCreateRecovery(value: object): value is ContactParametersCreateRecovery {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ContactParametersCreateRecoveryFromJSON(json: any): ContactParametersCreateRecovery {
    return ContactParametersCreateRecoveryFromJSONTyped(json, false);
}

export function ContactParametersCreateRecoveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactParametersCreateRecovery {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'type': ContactTypeFromJSON(json['type']),
    };
}

export function ContactParametersCreateRecoveryToJSON(json: any): ContactParametersCreateRecovery {
    return ContactParametersCreateRecoveryToJSONTyped(json, false);
}

export function ContactParametersCreateRecoveryToJSONTyped(value?: ContactParametersCreateRecovery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'type': ContactTypeToJSON(value['type']),
    };
}

