/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactType } from './ContactType';
import {
    ContactTypeFromJSON,
    ContactTypeFromJSONTyped,
    ContactTypeToJSON,
    ContactTypeToJSONTyped,
} from './ContactType';
import type { PhoneTypes } from './PhoneTypes';
import {
    PhoneTypesFromJSON,
    PhoneTypesFromJSONTyped,
    PhoneTypesToJSON,
    PhoneTypesToJSONTyped,
} from './PhoneTypes';

/**
 * 
 * @export
 * @interface ContactSharedPrimaryContact
 */
export interface ContactSharedPrimaryContact {
    /**
     * 
     * @type {string}
     * @memberof ContactSharedPrimaryContact
     */
    id: string;
    /**
     * 
     * @type {Array<PhoneTypes>}
     * @memberof ContactSharedPrimaryContact
     */
    phoneTypes?: Array<PhoneTypes> | null;
    /**
     * 
     * @type {ContactType}
     * @memberof ContactSharedPrimaryContact
     */
    type: ContactType;
    /**
     * 
     * @type {string}
     * @memberof ContactSharedPrimaryContact
     */
    value: string;
}



/**
 * Check if a given object implements the ContactSharedPrimaryContact interface.
 */
export function instanceOfContactSharedPrimaryContact(value: object): value is ContactSharedPrimaryContact {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ContactSharedPrimaryContactFromJSON(json: any): ContactSharedPrimaryContact {
    return ContactSharedPrimaryContactFromJSONTyped(json, false);
}

export function ContactSharedPrimaryContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactSharedPrimaryContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'phoneTypes': json['phoneTypes'] == null ? undefined : ((json['phoneTypes'] as Array<any>).map(PhoneTypesFromJSON)),
        'type': ContactTypeFromJSON(json['type']),
        'value': json['value'],
    };
}

export function ContactSharedPrimaryContactToJSON(json: any): ContactSharedPrimaryContact {
    return ContactSharedPrimaryContactToJSONTyped(json, false);
}

export function ContactSharedPrimaryContactToJSONTyped(value?: ContactSharedPrimaryContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'phoneTypes': value['phoneTypes'] == null ? undefined : ((value['phoneTypes'] as Array<any>).map(PhoneTypesToJSON)),
        'type': ContactTypeToJSON(value['type']),
        'value': value['value'],
    };
}

