/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ContactType = {
    phone: 'phone',
    email: 'email',
    telegram: 'telegram',
    instagram: 'instagram'
} as const;
export type ContactType = typeof ContactType[keyof typeof ContactType];


export function instanceOfContactType(value: any): boolean {
    for (const key in ContactType) {
        if (Object.prototype.hasOwnProperty.call(ContactType, key)) {
            if (ContactType[key as keyof typeof ContactType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContactTypeFromJSON(json: any): ContactType {
    return ContactTypeFromJSONTyped(json, false);
}

export function ContactTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactType {
    return json as ContactType;
}

export function ContactTypeToJSON(value?: ContactType | null): any {
    return value as any;
}

export function ContactTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ContactType {
    return value as ContactType;
}

