/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactType } from './ContactType';
import {
    ContactTypeFromJSON,
    ContactTypeFromJSONTyped,
    ContactTypeToJSON,
    ContactTypeToJSONTyped,
} from './ContactType';
import type { PhoneTypes } from './PhoneTypes';
import {
    PhoneTypesFromJSON,
    PhoneTypesFromJSONTyped,
    PhoneTypesToJSON,
    PhoneTypesToJSONTyped,
} from './PhoneTypes';

/**
 * 
 * @export
 * @interface ContactParametersCreatePrimary
 */
export interface ContactParametersCreatePrimary {
    /**
     * 
     * @type {Array<PhoneTypes>}
     * @memberof ContactParametersCreatePrimary
     */
    phoneTypes?: Array<PhoneTypes> | null;
    /**
     * 
     * @type {ContactType}
     * @memberof ContactParametersCreatePrimary
     */
    type: ContactType;
    /**
     * 
     * @type {string}
     * @memberof ContactParametersCreatePrimary
     */
    value: string;
}



/**
 * Check if a given object implements the ContactParametersCreatePrimary interface.
 */
export function instanceOfContactParametersCreatePrimary(value: object): value is ContactParametersCreatePrimary {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ContactParametersCreatePrimaryFromJSON(json: any): ContactParametersCreatePrimary {
    return ContactParametersCreatePrimaryFromJSONTyped(json, false);
}

export function ContactParametersCreatePrimaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactParametersCreatePrimary {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneTypes': json['phoneTypes'] == null ? undefined : ((json['phoneTypes'] as Array<any>).map(PhoneTypesFromJSON)),
        'type': ContactTypeFromJSON(json['type']),
        'value': json['value'],
    };
}

export function ContactParametersCreatePrimaryToJSON(json: any): ContactParametersCreatePrimary {
    return ContactParametersCreatePrimaryToJSONTyped(json, false);
}

export function ContactParametersCreatePrimaryToJSONTyped(value?: ContactParametersCreatePrimary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneTypes': value['phoneTypes'] == null ? undefined : ((value['phoneTypes'] as Array<any>).map(PhoneTypesToJSON)),
        'type': ContactTypeToJSON(value['type']),
        'value': value['value'],
    };
}

