/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactType } from './ContactType';
import {
    ContactTypeFromJSON,
    ContactTypeFromJSONTyped,
    ContactTypeToJSON,
    ContactTypeToJSONTyped,
} from './ContactType';

/**
 * 
 * @export
 * @interface ContactSharedRecoveryContact
 */
export interface ContactSharedRecoveryContact {
    /**
     * 
     * @type {string}
     * @memberof ContactSharedRecoveryContact
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContactSharedRecoveryContact
     */
    value: string;
    /**
     * 
     * @type {ContactType}
     * @memberof ContactSharedRecoveryContact
     */
    type: ContactType;
}



/**
 * Check if a given object implements the ContactSharedRecoveryContact interface.
 */
export function instanceOfContactSharedRecoveryContact(value: object): value is ContactSharedRecoveryContact {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ContactSharedRecoveryContactFromJSON(json: any): ContactSharedRecoveryContact {
    return ContactSharedRecoveryContactFromJSONTyped(json, false);
}

export function ContactSharedRecoveryContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactSharedRecoveryContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
        'type': ContactTypeFromJSON(json['type']),
    };
}

export function ContactSharedRecoveryContactToJSON(json: any): ContactSharedRecoveryContact {
    return ContactSharedRecoveryContactToJSONTyped(json, false);
}

export function ContactSharedRecoveryContactToJSONTyped(value?: ContactSharedRecoveryContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
        'type': ContactTypeToJSON(value['type']),
    };
}

