/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatePoint
 */
export interface CoordinatePoint {
    /**
     * 
     * @type {number}
     * @memberof CoordinatePoint
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinatePoint
     */
    latitude: number;
}

/**
 * Check if a given object implements the CoordinatePoint interface.
 */
export function instanceOfCoordinatePoint(value: object): value is CoordinatePoint {
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    return true;
}

export function CoordinatePointFromJSON(json: any): CoordinatePoint {
    return CoordinatePointFromJSONTyped(json, false);
}

export function CoordinatePointFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatePoint {
    if (json == null) {
        return json;
    }
    return {
        
        'longitude': json['longitude'],
        'latitude': json['latitude'],
    };
}

export function CoordinatePointToJSON(json: any): CoordinatePoint {
    return CoordinatePointToJSONTyped(json, false);
}

export function CoordinatePointToJSONTyped(value?: CoordinatePoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'longitude': value['longitude'],
        'latitude': value['latitude'],
    };
}

