/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CredentialsSet
 */
export interface CredentialsSet {
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    salaryCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    statisticCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    employeeCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    clientCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    appointmentCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    positionCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    notifyCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    procedureCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    salonCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    worktimeCreds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialsSet
     */
    financeCreds: Array<string>;
}

/**
 * Check if a given object implements the CredentialsSet interface.
 */
export function instanceOfCredentialsSet(value: object): value is CredentialsSet {
    if (!('salaryCreds' in value) || value['salaryCreds'] === undefined) return false;
    if (!('statisticCreds' in value) || value['statisticCreds'] === undefined) return false;
    if (!('employeeCreds' in value) || value['employeeCreds'] === undefined) return false;
    if (!('clientCreds' in value) || value['clientCreds'] === undefined) return false;
    if (!('appointmentCreds' in value) || value['appointmentCreds'] === undefined) return false;
    if (!('positionCreds' in value) || value['positionCreds'] === undefined) return false;
    if (!('notifyCreds' in value) || value['notifyCreds'] === undefined) return false;
    if (!('procedureCreds' in value) || value['procedureCreds'] === undefined) return false;
    if (!('salonCreds' in value) || value['salonCreds'] === undefined) return false;
    if (!('worktimeCreds' in value) || value['worktimeCreds'] === undefined) return false;
    if (!('financeCreds' in value) || value['financeCreds'] === undefined) return false;
    return true;
}

export function CredentialsSetFromJSON(json: any): CredentialsSet {
    return CredentialsSetFromJSONTyped(json, false);
}

export function CredentialsSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialsSet {
    if (json == null) {
        return json;
    }
    return {
        
        'salaryCreds': json['salaryCreds'],
        'statisticCreds': json['statisticCreds'],
        'employeeCreds': json['employeeCreds'],
        'clientCreds': json['clientCreds'],
        'appointmentCreds': json['appointmentCreds'],
        'positionCreds': json['positionCreds'],
        'notifyCreds': json['notifyCreds'],
        'procedureCreds': json['procedureCreds'],
        'salonCreds': json['salonCreds'],
        'worktimeCreds': json['worktimeCreds'],
        'financeCreds': json['financeCreds'],
    };
}

export function CredentialsSetToJSON(json: any): CredentialsSet {
    return CredentialsSetToJSONTyped(json, false);
}

export function CredentialsSetToJSONTyped(value?: CredentialsSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'salaryCreds': value['salaryCreds'],
        'statisticCreds': value['statisticCreds'],
        'employeeCreds': value['employeeCreds'],
        'clientCreds': value['clientCreds'],
        'appointmentCreds': value['appointmentCreds'],
        'positionCreds': value['positionCreds'],
        'notifyCreds': value['notifyCreds'],
        'procedureCreds': value['procedureCreds'],
        'salonCreds': value['salonCreds'],
        'worktimeCreds': value['worktimeCreds'],
        'financeCreds': value['financeCreds'],
    };
}

