/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CursorPageMeta
 */
export interface CursorPageMeta {
    /**
     * 
     * @type {string}
     * @memberof CursorPageMeta
     */
    nextCursor?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CursorPageMeta
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the CursorPageMeta interface.
 */
export function instanceOfCursorPageMeta(value: object): value is CursorPageMeta {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function CursorPageMetaFromJSON(json: any): CursorPageMeta {
    return CursorPageMetaFromJSONTyped(json, false);
}

export function CursorPageMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function CursorPageMetaToJSON(json: any): CursorPageMeta {
    return CursorPageMetaToJSONTyped(json, false);
}

export function CursorPageMetaToJSONTyped(value?: CursorPageMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

