/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface CustomerResponsesRegistration
 */
export interface CustomerResponsesRegistration {
    /**
     * 
     * @type {Token}
     * @memberof CustomerResponsesRegistration
     */
    accessToken: Token;
}

/**
 * Check if a given object implements the CustomerResponsesRegistration interface.
 */
export function instanceOfCustomerResponsesRegistration(value: object): value is CustomerResponsesRegistration {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function CustomerResponsesRegistrationFromJSON(json: any): CustomerResponsesRegistration {
    return CustomerResponsesRegistrationFromJSONTyped(json, false);
}

export function CustomerResponsesRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerResponsesRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': TokenFromJSON(json['accessToken']),
    };
}

export function CustomerResponsesRegistrationToJSON(json: any): CustomerResponsesRegistration {
    return CustomerResponsesRegistrationToJSONTyped(json, false);
}

export function CustomerResponsesRegistrationToJSONTyped(value?: CustomerResponsesRegistration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': TokenToJSON(value['accessToken']),
    };
}

