/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerInternalContact } from './CustomerInternalContact';
import {
    CustomerInternalContactFromJSON,
    CustomerInternalContactFromJSONTyped,
    CustomerInternalContactToJSON,
    CustomerInternalContactToJSONTyped,
} from './CustomerInternalContact';

/**
 * 
 * @export
 * @interface CustomerParametersRegistration
 */
export interface CustomerParametersRegistration {
    /**
     * 
     * @type {CustomerInternalContact}
     * @memberof CustomerParametersRegistration
     */
    contact?: CustomerInternalContact;
}

/**
 * Check if a given object implements the CustomerParametersRegistration interface.
 */
export function instanceOfCustomerParametersRegistration(value: object): value is CustomerParametersRegistration {
    return true;
}

export function CustomerParametersRegistrationFromJSON(json: any): CustomerParametersRegistration {
    return CustomerParametersRegistrationFromJSONTyped(json, false);
}

export function CustomerParametersRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerParametersRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'contact': json['contact'] == null ? undefined : CustomerInternalContactFromJSON(json['contact']),
    };
}

export function CustomerParametersRegistrationToJSON(json: any): CustomerParametersRegistration {
    return CustomerParametersRegistrationToJSONTyped(json, false);
}

export function CustomerParametersRegistrationToJSONTyped(value?: CustomerParametersRegistration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact': CustomerInternalContactToJSON(value['contact']),
    };
}

