/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionType } from './VersionType';
import {
    VersionTypeFromJSON,
    VersionTypeFromJSONTyped,
    VersionTypeToJSON,
    VersionTypeToJSONTyped,
} from './VersionType';

/**
 * 
 * @export
 * @interface DeviceResponsesFull
 */
export interface DeviceResponsesFull {
    /**
     * 
     * @type {string}
     * @memberof DeviceResponsesFull
     */
    id: string;
    /**
     * 
     * @type {VersionType}
     * @memberof DeviceResponsesFull
     */
    version?: VersionType;
}



/**
 * Check if a given object implements the DeviceResponsesFull interface.
 */
export function instanceOfDeviceResponsesFull(value: object): value is DeviceResponsesFull {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeviceResponsesFullFromJSON(json: any): DeviceResponsesFull {
    return DeviceResponsesFullFromJSONTyped(json, false);
}

export function DeviceResponsesFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceResponsesFull {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'version': json['version'] == null ? undefined : VersionTypeFromJSON(json['version']),
    };
}

export function DeviceResponsesFullToJSON(json: any): DeviceResponsesFull {
    return DeviceResponsesFullToJSONTyped(json, false);
}

export function DeviceResponsesFullToJSONTyped(value?: DeviceResponsesFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': VersionTypeToJSON(value['version']),
    };
}

