/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Any } from './Any';
import {
    AnyFromJSON,
    AnyFromJSONTyped,
    AnyToJSON,
    AnyToJSONTyped,
} from './Any';

/**
 * 
 * @export
 * @interface DeviceParametersSystem
 */
export interface DeviceParametersSystem {
    /**
     * 
     * @type {string}
     * @memberof DeviceParametersSystem
     */
    manufacturer?: string | null;
    /**
     * 
     * @type {{ [key: string]: Any; }}
     * @memberof DeviceParametersSystem
     */
    system?: { [key: string]: Any; };
    /**
     * 
     * @type {string}
     * @memberof DeviceParametersSystem
     */
    appVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceParametersSystem
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceParametersSystem
     */
    fcmToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceParametersSystem
     */
    model?: string | null;
}

/**
 * Check if a given object implements the DeviceParametersSystem interface.
 */
export function instanceOfDeviceParametersSystem(value: object): value is DeviceParametersSystem {
    return true;
}

export function DeviceParametersSystemFromJSON(json: any): DeviceParametersSystem {
    return DeviceParametersSystemFromJSONTyped(json, false);
}

export function DeviceParametersSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceParametersSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'manufacturer': json['manufacturer'] == null ? undefined : json['manufacturer'],
        'system': json['system'] == null ? undefined : (mapValues(json['system'], AnyFromJSON)),
        'appVersion': json['appVersion'] == null ? undefined : json['appVersion'],
        'country': json['country'] == null ? undefined : json['country'],
        'fcmToken': json['fcmToken'] == null ? undefined : json['fcmToken'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function DeviceParametersSystemToJSON(json: any): DeviceParametersSystem {
    return DeviceParametersSystemToJSONTyped(json, false);
}

export function DeviceParametersSystemToJSONTyped(value?: DeviceParametersSystem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'manufacturer': value['manufacturer'],
        'system': value['system'] == null ? undefined : (mapValues(value['system'], AnyToJSON)),
        'appVersion': value['appVersion'],
        'country': value['country'],
        'fcmToken': value['fcmToken'],
        'model': value['model'],
    };
}

