/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeParametersPatch
 */
export interface EmployeeParametersPatch {
    /**
     * 
     * @type {string}
     * @memberof EmployeeParametersPatch
     */
    positionId?: string | null;
}

/**
 * Check if a given object implements the EmployeeParametersPatch interface.
 */
export function instanceOfEmployeeParametersPatch(value: object): value is EmployeeParametersPatch {
    return true;
}

export function EmployeeParametersPatchFromJSON(json: any): EmployeeParametersPatch {
    return EmployeeParametersPatchFromJSONTyped(json, false);
}

export function EmployeeParametersPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeParametersPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'positionId': json['positionId'] == null ? undefined : json['positionId'],
    };
}

export function EmployeeParametersPatchToJSON(json: any): EmployeeParametersPatch {
    return EmployeeParametersPatchToJSONTyped(json, false);
}

export function EmployeeParametersPatchToJSONTyped(value?: EmployeeParametersPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'positionId': value['positionId'],
    };
}

