/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmployeeInternalContact } from './EmployeeInternalContact';
import {
    EmployeeInternalContactFromJSON,
    EmployeeInternalContactFromJSONTyped,
    EmployeeInternalContactToJSON,
    EmployeeInternalContactToJSONTyped,
} from './EmployeeInternalContact';
import type { TimetableParametersCreatePattern } from './TimetableParametersCreatePattern';
import {
    TimetableParametersCreatePatternFromJSON,
    TimetableParametersCreatePatternFromJSONTyped,
    TimetableParametersCreatePatternToJSON,
    TimetableParametersCreatePatternToJSONTyped,
} from './TimetableParametersCreatePattern';

/**
 * 
 * @export
 * @interface EmployeeParametersInvite
 */
export interface EmployeeParametersInvite {
    /**
     * 
     * @type {EmployeeInternalContact}
     * @memberof EmployeeParametersInvite
     */
    contact?: EmployeeInternalContact;
    /**
     * 
     * @type {string}
     * @memberof EmployeeParametersInvite
     */
    nickname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmployeeParametersInvite
     */
    salonId: string;
    /**
     * 
     * @type {TimetableParametersCreatePattern}
     * @memberof EmployeeParametersInvite
     */
    timetable?: TimetableParametersCreatePattern;
    /**
     * 
     * @type {string}
     * @memberof EmployeeParametersInvite
     */
    positionId: string;
}

/**
 * Check if a given object implements the EmployeeParametersInvite interface.
 */
export function instanceOfEmployeeParametersInvite(value: object): value is EmployeeParametersInvite {
    if (!('salonId' in value) || value['salonId'] === undefined) return false;
    if (!('positionId' in value) || value['positionId'] === undefined) return false;
    return true;
}

export function EmployeeParametersInviteFromJSON(json: any): EmployeeParametersInvite {
    return EmployeeParametersInviteFromJSONTyped(json, false);
}

export function EmployeeParametersInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeParametersInvite {
    if (json == null) {
        return json;
    }
    return {
        
        'contact': json['contact'] == null ? undefined : EmployeeInternalContactFromJSON(json['contact']),
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'salonId': json['salonId'],
        'timetable': json['timetable'] == null ? undefined : TimetableParametersCreatePatternFromJSON(json['timetable']),
        'positionId': json['positionId'],
    };
}

export function EmployeeParametersInviteToJSON(json: any): EmployeeParametersInvite {
    return EmployeeParametersInviteToJSONTyped(json, false);
}

export function EmployeeParametersInviteToJSONTyped(value?: EmployeeParametersInvite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact': EmployeeInternalContactToJSON(value['contact']),
        'nickname': value['nickname'],
        'salonId': value['salonId'],
        'timetable': TimetableParametersCreatePatternToJSON(value['timetable']),
        'positionId': value['positionId'],
    };
}

