/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeInternalUserInfo
 */
export interface EmployeeInternalUserInfo {
    /**
     * 
     * @type {string}
     * @memberof EmployeeInternalUserInfo
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeInternalUserInfo
     */
    avatar: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeInternalUserInfo
     */
    id: string;
}

/**
 * Check if a given object implements the EmployeeInternalUserInfo interface.
 */
export function instanceOfEmployeeInternalUserInfo(value: object): value is EmployeeInternalUserInfo {
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function EmployeeInternalUserInfoFromJSON(json: any): EmployeeInternalUserInfo {
    return EmployeeInternalUserInfoFromJSONTyped(json, false);
}

export function EmployeeInternalUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeInternalUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
        'avatar': json['avatar'],
        'id': json['id'],
    };
}

export function EmployeeInternalUserInfoToJSON(json: any): EmployeeInternalUserInfo {
    return EmployeeInternalUserInfoToJSONTyped(json, false);
}

export function EmployeeInternalUserInfoToJSONTyped(value?: EmployeeInternalUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'avatar': value['avatar'],
        'id': value['id'],
    };
}

