/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PositionResponsesFull } from './PositionResponsesFull';
import {
    PositionResponsesFullFromJSON,
    PositionResponsesFullFromJSONTyped,
    PositionResponsesFullToJSON,
    PositionResponsesFullToJSONTyped,
} from './PositionResponsesFull';
import type { ContactSharedPrimaryContact } from './ContactSharedPrimaryContact';
import {
    ContactSharedPrimaryContactFromJSON,
    ContactSharedPrimaryContactFromJSONTyped,
    ContactSharedPrimaryContactToJSON,
    ContactSharedPrimaryContactToJSONTyped,
} from './ContactSharedPrimaryContact';
import type { EmployeeInternalUserInfo } from './EmployeeInternalUserInfo';
import {
    EmployeeInternalUserInfoFromJSON,
    EmployeeInternalUserInfoFromJSONTyped,
    EmployeeInternalUserInfoToJSON,
    EmployeeInternalUserInfoToJSONTyped,
} from './EmployeeInternalUserInfo';

/**
 * 
 * @export
 * @interface EmployeeResponsesFull
 */
export interface EmployeeResponsesFull {
    /**
     * 
     * @type {EmployeeInternalUserInfo}
     * @memberof EmployeeResponsesFull
     */
    user?: EmployeeInternalUserInfo;
    /**
     * 
     * @type {string}
     * @memberof EmployeeResponsesFull
     */
    salonId: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeResponsesFull
     */
    id: string;
    /**
     * 
     * @type {Array<ContactSharedPrimaryContact>}
     * @memberof EmployeeResponsesFull
     */
    contacts: Array<ContactSharedPrimaryContact>;
    /**
     * 
     * @type {PositionResponsesFull}
     * @memberof EmployeeResponsesFull
     */
    position: PositionResponsesFull;
}

/**
 * Check if a given object implements the EmployeeResponsesFull interface.
 */
export function instanceOfEmployeeResponsesFull(value: object): value is EmployeeResponsesFull {
    if (!('salonId' in value) || value['salonId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function EmployeeResponsesFullFromJSON(json: any): EmployeeResponsesFull {
    return EmployeeResponsesFullFromJSONTyped(json, false);
}

export function EmployeeResponsesFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeResponsesFull {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : EmployeeInternalUserInfoFromJSON(json['user']),
        'salonId': json['salonId'],
        'id': json['id'],
        'contacts': ((json['contacts'] as Array<any>).map(ContactSharedPrimaryContactFromJSON)),
        'position': PositionResponsesFullFromJSON(json['position']),
    };
}

export function EmployeeResponsesFullToJSON(json: any): EmployeeResponsesFull {
    return EmployeeResponsesFullToJSONTyped(json, false);
}

export function EmployeeResponsesFullToJSONTyped(value?: EmployeeResponsesFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': EmployeeInternalUserInfoToJSON(value['user']),
        'salonId': value['salonId'],
        'id': value['id'],
        'contacts': ((value['contacts'] as Array<any>).map(ContactSharedPrimaryContactToJSON)),
        'position': PositionResponsesFullToJSON(value['position']),
    };
}

