/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactSharedPrimaryContact } from './ContactSharedPrimaryContact';
import {
    ContactSharedPrimaryContactFromJSON,
    ContactSharedPrimaryContactFromJSONTyped,
    ContactSharedPrimaryContactToJSON,
    ContactSharedPrimaryContactToJSONTyped,
} from './ContactSharedPrimaryContact';
import type { PositionResponsesPartial } from './PositionResponsesPartial';
import {
    PositionResponsesPartialFromJSON,
    PositionResponsesPartialFromJSONTyped,
    PositionResponsesPartialToJSON,
    PositionResponsesPartialToJSONTyped,
} from './PositionResponsesPartial';

/**
 * 
 * @export
 * @interface EmployeeResponsesPartial
 */
export interface EmployeeResponsesPartial {
    /**
     * 
     * @type {PositionResponsesPartial}
     * @memberof EmployeeResponsesPartial
     */
    position: PositionResponsesPartial;
    /**
     * 
     * @type {string}
     * @memberof EmployeeResponsesPartial
     */
    avatar: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeResponsesPartial
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeResponsesPartial
     */
    nickname: string;
    /**
     * 
     * @type {Array<ContactSharedPrimaryContact>}
     * @memberof EmployeeResponsesPartial
     */
    contacts: Array<ContactSharedPrimaryContact>;
}

/**
 * Check if a given object implements the EmployeeResponsesPartial interface.
 */
export function instanceOfEmployeeResponsesPartial(value: object): value is EmployeeResponsesPartial {
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    return true;
}

export function EmployeeResponsesPartialFromJSON(json: any): EmployeeResponsesPartial {
    return EmployeeResponsesPartialFromJSONTyped(json, false);
}

export function EmployeeResponsesPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeResponsesPartial {
    if (json == null) {
        return json;
    }
    return {
        
        'position': PositionResponsesPartialFromJSON(json['position']),
        'avatar': json['avatar'],
        'id': json['id'],
        'nickname': json['nickname'],
        'contacts': ((json['contacts'] as Array<any>).map(ContactSharedPrimaryContactFromJSON)),
    };
}

export function EmployeeResponsesPartialToJSON(json: any): EmployeeResponsesPartial {
    return EmployeeResponsesPartialToJSONTyped(json, false);
}

export function EmployeeResponsesPartialToJSONTyped(value?: EmployeeResponsesPartial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'position': PositionResponsesPartialToJSON(value['position']),
        'avatar': value['avatar'],
        'id': value['id'],
        'nickname': value['nickname'],
        'contacts': ((value['contacts'] as Array<any>).map(ContactSharedPrimaryContactToJSON)),
    };
}

