/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ApiError } from './ApiError';
import {
    instanceOfApiError,
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
} from './ApiError';
import type { LegacyErrorResponse } from './LegacyErrorResponse';
import {
    instanceOfLegacyErrorResponse,
    LegacyErrorResponseFromJSON,
    LegacyErrorResponseFromJSONTyped,
    LegacyErrorResponseToJSON,
} from './LegacyErrorResponse';

/**
 * @type ErrorResponse
 * Transition error envelope. During migration clients should support both legacy and new formats.
 * @export
 */
export type ErrorResponse = ApiError | LegacyErrorResponse;

export function ErrorResponseFromJSON(json: any): ErrorResponse {
    return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfApiError(json)) {
        return ApiErrorFromJSONTyped(json, true);
    }
    if (instanceOfLegacyErrorResponse(json)) {
        return LegacyErrorResponseFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ErrorResponseToJSON(json: any): any {
    return ErrorResponseToJSONTyped(json, false);
}

export function ErrorResponseToJSONTyped(value?: ErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfApiError(value)) {
        return ApiErrorToJSON(value as ApiError);
    }
    if (instanceOfLegacyErrorResponse(value)) {
        return LegacyErrorResponseToJSON(value as LegacyErrorResponse);
    }
    return {};
}

