/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinatePoint } from './CoordinatePoint';
import {
    CoordinatePointFromJSON,
    CoordinatePointFromJSONTyped,
    CoordinatePointToJSON,
    CoordinatePointToJSONTyped,
} from './CoordinatePoint';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { SalonType } from './SalonType';
import {
    SalonTypeFromJSON,
    SalonTypeFromJSONTyped,
    SalonTypeToJSON,
    SalonTypeToJSONTyped,
} from './SalonType';

/**
 * 
 * @export
 * @interface FavoriteResponsesSalon
 */
export interface FavoriteResponsesSalon {
    /**
     * 
     * @type {Address}
     * @memberof FavoriteResponsesSalon
     */
    address: Address;
    /**
     * 
     * @type {boolean}
     * @memberof FavoriteResponsesSalon
     */
    isActive: boolean;
    /**
     * 
     * @type {CoordinatePoint}
     * @memberof FavoriteResponsesSalon
     */
    point: CoordinatePoint;
    /**
     * 
     * @type {string}
     * @memberof FavoriteResponsesSalon
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FavoriteResponsesSalon
     */
    logo: string;
    /**
     * 
     * @type {string}
     * @memberof FavoriteResponsesSalon
     */
    name: string;
    /**
     * 
     * @type {SalonType}
     * @memberof FavoriteResponsesSalon
     */
    type: SalonType;
}



/**
 * Check if a given object implements the FavoriteResponsesSalon interface.
 */
export function instanceOfFavoriteResponsesSalon(value: object): value is FavoriteResponsesSalon {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('point' in value) || value['point'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('logo' in value) || value['logo'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FavoriteResponsesSalonFromJSON(json: any): FavoriteResponsesSalon {
    return FavoriteResponsesSalonFromJSONTyped(json, false);
}

export function FavoriteResponsesSalonFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteResponsesSalon {
    if (json == null) {
        return json;
    }
    return {
        
        'address': AddressFromJSON(json['address']),
        'isActive': json['isActive'],
        'point': CoordinatePointFromJSON(json['point']),
        'id': json['id'],
        'logo': json['logo'],
        'name': json['name'],
        'type': SalonTypeFromJSON(json['type']),
    };
}

export function FavoriteResponsesSalonToJSON(json: any): FavoriteResponsesSalon {
    return FavoriteResponsesSalonToJSONTyped(json, false);
}

export function FavoriteResponsesSalonToJSONTyped(value?: FavoriteResponsesSalon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': AddressToJSON(value['address']),
        'isActive': value['isActive'],
        'point': CoordinatePointToJSON(value['point']),
        'id': value['id'],
        'logo': value['logo'],
        'name': value['name'],
        'type': SalonTypeToJSON(value['type']),
    };
}

