/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CursorPageMeta } from './CursorPageMeta';
import {
    CursorPageMetaFromJSON,
    CursorPageMetaFromJSONTyped,
    CursorPageMetaToJSON,
    CursorPageMetaToJSONTyped,
} from './CursorPageMeta';
import type { FavoriteResponsesSalon } from './FavoriteResponsesSalon';
import {
    FavoriteResponsesSalonFromJSON,
    FavoriteResponsesSalonFromJSONTyped,
    FavoriteResponsesSalonToJSON,
    FavoriteResponsesSalonToJSONTyped,
} from './FavoriteResponsesSalon';

/**
 * 
 * @export
 * @interface GetFavoritesCursorPageResponse
 */
export interface GetFavoritesCursorPageResponse {
    /**
     * 
     * @type {Array<FavoriteResponsesSalon>}
     * @memberof GetFavoritesCursorPageResponse
     */
    data: Array<FavoriteResponsesSalon>;
    /**
     * 
     * @type {CursorPageMeta}
     * @memberof GetFavoritesCursorPageResponse
     */
    meta: CursorPageMeta;
}

/**
 * Check if a given object implements the GetFavoritesCursorPageResponse interface.
 */
export function instanceOfGetFavoritesCursorPageResponse(value: object): value is GetFavoritesCursorPageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetFavoritesCursorPageResponseFromJSON(json: any): GetFavoritesCursorPageResponse {
    return GetFavoritesCursorPageResponseFromJSONTyped(json, false);
}

export function GetFavoritesCursorPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFavoritesCursorPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(FavoriteResponsesSalonFromJSON)),
        'meta': CursorPageMetaFromJSON(json['meta']),
    };
}

export function GetFavoritesCursorPageResponseToJSON(json: any): GetFavoritesCursorPageResponse {
    return GetFavoritesCursorPageResponseToJSONTyped(json, false);
}

export function GetFavoritesCursorPageResponseToJSONTyped(value?: GetFavoritesCursorPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(FavoriteResponsesSalonToJSON)),
        'meta': CursorPageMetaToJSON(value['meta']),
    };
}

