/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CursorPageMeta } from './CursorPageMeta';
import {
    CursorPageMetaFromJSON,
    CursorPageMetaFromJSONTyped,
    CursorPageMetaToJSON,
    CursorPageMetaToJSONTyped,
} from './CursorPageMeta';
import type { NoticeResponsesFull } from './NoticeResponsesFull';
import {
    NoticeResponsesFullFromJSON,
    NoticeResponsesFullFromJSONTyped,
    NoticeResponsesFullToJSON,
    NoticeResponsesFullToJSONTyped,
} from './NoticeResponsesFull';

/**
 * 
 * @export
 * @interface GetNotificationsCursorPageResponse
 */
export interface GetNotificationsCursorPageResponse {
    /**
     * 
     * @type {Array<NoticeResponsesFull>}
     * @memberof GetNotificationsCursorPageResponse
     */
    data: Array<NoticeResponsesFull>;
    /**
     * 
     * @type {CursorPageMeta}
     * @memberof GetNotificationsCursorPageResponse
     */
    meta: CursorPageMeta;
}

/**
 * Check if a given object implements the GetNotificationsCursorPageResponse interface.
 */
export function instanceOfGetNotificationsCursorPageResponse(value: object): value is GetNotificationsCursorPageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetNotificationsCursorPageResponseFromJSON(json: any): GetNotificationsCursorPageResponse {
    return GetNotificationsCursorPageResponseFromJSONTyped(json, false);
}

export function GetNotificationsCursorPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNotificationsCursorPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(NoticeResponsesFullFromJSON)),
        'meta': CursorPageMetaFromJSON(json['meta']),
    };
}

export function GetNotificationsCursorPageResponseToJSON(json: any): GetNotificationsCursorPageResponse {
    return GetNotificationsCursorPageResponseToJSONTyped(json, false);
}

export function GetNotificationsCursorPageResponseToJSONTyped(value?: GetNotificationsCursorPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(NoticeResponsesFullToJSON)),
        'meta': CursorPageMetaToJSON(value['meta']),
    };
}

