/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSearchCursorPageResponseDataInner } from './GetSearchCursorPageResponseDataInner';
import {
    GetSearchCursorPageResponseDataInnerFromJSON,
    GetSearchCursorPageResponseDataInnerFromJSONTyped,
    GetSearchCursorPageResponseDataInnerToJSON,
    GetSearchCursorPageResponseDataInnerToJSONTyped,
} from './GetSearchCursorPageResponseDataInner';
import type { CursorPageMeta } from './CursorPageMeta';
import {
    CursorPageMetaFromJSON,
    CursorPageMetaFromJSONTyped,
    CursorPageMetaToJSON,
    CursorPageMetaToJSONTyped,
} from './CursorPageMeta';

/**
 * 
 * @export
 * @interface GetSearchCursorPageResponse
 */
export interface GetSearchCursorPageResponse {
    /**
     * 
     * @type {Array<GetSearchCursorPageResponseDataInner>}
     * @memberof GetSearchCursorPageResponse
     */
    data: Array<GetSearchCursorPageResponseDataInner>;
    /**
     * 
     * @type {CursorPageMeta}
     * @memberof GetSearchCursorPageResponse
     */
    meta: CursorPageMeta;
}

/**
 * Check if a given object implements the GetSearchCursorPageResponse interface.
 */
export function instanceOfGetSearchCursorPageResponse(value: object): value is GetSearchCursorPageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetSearchCursorPageResponseFromJSON(json: any): GetSearchCursorPageResponse {
    return GetSearchCursorPageResponseFromJSONTyped(json, false);
}

export function GetSearchCursorPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSearchCursorPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetSearchCursorPageResponseDataInnerFromJSON)),
        'meta': CursorPageMetaFromJSON(json['meta']),
    };
}

export function GetSearchCursorPageResponseToJSON(json: any): GetSearchCursorPageResponse {
    return GetSearchCursorPageResponseToJSONTyped(json, false);
}

export function GetSearchCursorPageResponseToJSONTyped(value?: GetSearchCursorPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(GetSearchCursorPageResponseDataInnerToJSON)),
        'meta': CursorPageMetaToJSON(value['meta']),
    };
}

