/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SearchResponsesHelpersSalon } from './SearchResponsesHelpersSalon';
import {
    instanceOfSearchResponsesHelpersSalon,
    SearchResponsesHelpersSalonFromJSON,
    SearchResponsesHelpersSalonFromJSONTyped,
    SearchResponsesHelpersSalonToJSON,
} from './SearchResponsesHelpersSalon';
import type { SearchResponsesHelpersSuggest } from './SearchResponsesHelpersSuggest';
import {
    instanceOfSearchResponsesHelpersSuggest,
    SearchResponsesHelpersSuggestFromJSON,
    SearchResponsesHelpersSuggestFromJSONTyped,
    SearchResponsesHelpersSuggestToJSON,
} from './SearchResponsesHelpersSuggest';

/**
 * @type GetSearchCursorPageResponseDataInner
 * 
 * @export
 */
export type GetSearchCursorPageResponseDataInner = SearchResponsesHelpersSalon | SearchResponsesHelpersSuggest;

export function GetSearchCursorPageResponseDataInnerFromJSON(json: any): GetSearchCursorPageResponseDataInner {
    return GetSearchCursorPageResponseDataInnerFromJSONTyped(json, false);
}

export function GetSearchCursorPageResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSearchCursorPageResponseDataInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfSearchResponsesHelpersSalon(json)) {
        return SearchResponsesHelpersSalonFromJSONTyped(json, true);
    }
    if (instanceOfSearchResponsesHelpersSuggest(json)) {
        return SearchResponsesHelpersSuggestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function GetSearchCursorPageResponseDataInnerToJSON(json: any): any {
    return GetSearchCursorPageResponseDataInnerToJSONTyped(json, false);
}

export function GetSearchCursorPageResponseDataInnerToJSONTyped(value?: GetSearchCursorPageResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfSearchResponsesHelpersSalon(value)) {
        return SearchResponsesHelpersSalonToJSON(value as SearchResponsesHelpersSalon);
    }
    if (instanceOfSearchResponsesHelpersSuggest(value)) {
        return SearchResponsesHelpersSuggestToJSON(value as SearchResponsesHelpersSuggest);
    }
    return {};
}

