/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CursorPageMeta } from './CursorPageMeta';
import {
    CursorPageMetaFromJSON,
    CursorPageMetaFromJSONTyped,
    CursorPageMetaToJSON,
    CursorPageMetaToJSONTyped,
} from './CursorPageMeta';

/**
 * 
 * @export
 * @interface GetWorkspaceBookingsCursorPageResponse
 */
export interface GetWorkspaceBookingsCursorPageResponse {
    /**
     * 
     * @type {Array<object>}
     * @memberof GetWorkspaceBookingsCursorPageResponse
     */
    data: Array<object>;
    /**
     * 
     * @type {CursorPageMeta}
     * @memberof GetWorkspaceBookingsCursorPageResponse
     */
    meta: CursorPageMeta;
}

/**
 * Check if a given object implements the GetWorkspaceBookingsCursorPageResponse interface.
 */
export function instanceOfGetWorkspaceBookingsCursorPageResponse(value: object): value is GetWorkspaceBookingsCursorPageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetWorkspaceBookingsCursorPageResponseFromJSON(json: any): GetWorkspaceBookingsCursorPageResponse {
    return GetWorkspaceBookingsCursorPageResponseFromJSONTyped(json, false);
}

export function GetWorkspaceBookingsCursorPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceBookingsCursorPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'meta': CursorPageMetaFromJSON(json['meta']),
    };
}

export function GetWorkspaceBookingsCursorPageResponseToJSON(json: any): GetWorkspaceBookingsCursorPageResponse {
    return GetWorkspaceBookingsCursorPageResponseToJSONTyped(json, false);
}

export function GetWorkspaceBookingsCursorPageResponseToJSONTyped(value?: GetWorkspaceBookingsCursorPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'meta': CursorPageMetaToJSON(value['meta']),
    };
}

