/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CursorPageMeta } from './CursorPageMeta';
import {
    CursorPageMetaFromJSON,
    CursorPageMetaFromJSONTyped,
    CursorPageMetaToJSON,
    CursorPageMetaToJSONTyped,
} from './CursorPageMeta';
import type { ClientResponsesClientInfo } from './ClientResponsesClientInfo';
import {
    ClientResponsesClientInfoFromJSON,
    ClientResponsesClientInfoFromJSONTyped,
    ClientResponsesClientInfoToJSON,
    ClientResponsesClientInfoToJSONTyped,
} from './ClientResponsesClientInfo';

/**
 * 
 * @export
 * @interface GetWorkspaceClientsCursorPageResponse
 */
export interface GetWorkspaceClientsCursorPageResponse {
    /**
     * 
     * @type {Array<ClientResponsesClientInfo>}
     * @memberof GetWorkspaceClientsCursorPageResponse
     */
    data: Array<ClientResponsesClientInfo>;
    /**
     * 
     * @type {CursorPageMeta}
     * @memberof GetWorkspaceClientsCursorPageResponse
     */
    meta: CursorPageMeta;
}

/**
 * Check if a given object implements the GetWorkspaceClientsCursorPageResponse interface.
 */
export function instanceOfGetWorkspaceClientsCursorPageResponse(value: object): value is GetWorkspaceClientsCursorPageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetWorkspaceClientsCursorPageResponseFromJSON(json: any): GetWorkspaceClientsCursorPageResponse {
    return GetWorkspaceClientsCursorPageResponseFromJSONTyped(json, false);
}

export function GetWorkspaceClientsCursorPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceClientsCursorPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClientResponsesClientInfoFromJSON)),
        'meta': CursorPageMetaFromJSON(json['meta']),
    };
}

export function GetWorkspaceClientsCursorPageResponseToJSON(json: any): GetWorkspaceClientsCursorPageResponse {
    return GetWorkspaceClientsCursorPageResponseToJSONTyped(json, false);
}

export function GetWorkspaceClientsCursorPageResponseToJSONTyped(value?: GetWorkspaceClientsCursorPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ClientResponsesClientInfoToJSON)),
        'meta': CursorPageMetaToJSON(value['meta']),
    };
}

