/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Legacy runtime error payload from ErrorMiddlewareCustom. Deprecated in favor of ApiError. Planned sunset date: 2026-06-30.
 * @export
 * @interface LegacyErrorResponse
 */
export interface LegacyErrorResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LegacyErrorResponse
     */
    error: boolean;
    /**
     * 
     * @type {string}
     * @memberof LegacyErrorResponse
     */
    reason: string;
}

/**
 * Check if a given object implements the LegacyErrorResponse interface.
 */
export function instanceOfLegacyErrorResponse(value: object): value is LegacyErrorResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function LegacyErrorResponseFromJSON(json: any): LegacyErrorResponse {
    return LegacyErrorResponseFromJSONTyped(json, false);
}

export function LegacyErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'reason': json['reason'],
    };
}

export function LegacyErrorResponseToJSON(json: any): LegacyErrorResponse {
    return LegacyErrorResponseToJSONTyped(json, false);
}

export function LegacyErrorResponseToJSONTyped(value?: LegacyErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'reason': value['reason'],
    };
}

