/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoticeResponsesFull
 */
export interface NoticeResponsesFull {
    /**
     * 
     * @type {Date}
     * @memberof NoticeResponsesFull
     */
    date?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof NoticeResponsesFull
     */
    messageKey: string;
    /**
     * 
     * @type {string}
     * @memberof NoticeResponsesFull
     */
    titleKey: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof NoticeResponsesFull
     */
    parameters: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof NoticeResponsesFull
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof NoticeResponsesFull
     */
    isRead: boolean;
    /**
     * 
     * @type {string}
     * @memberof NoticeResponsesFull
     */
    category: string;
}

/**
 * Check if a given object implements the NoticeResponsesFull interface.
 */
export function instanceOfNoticeResponsesFull(value: object): value is NoticeResponsesFull {
    if (!('messageKey' in value) || value['messageKey'] === undefined) return false;
    if (!('titleKey' in value) || value['titleKey'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function NoticeResponsesFullFromJSON(json: any): NoticeResponsesFull {
    return NoticeResponsesFullFromJSONTyped(json, false);
}

export function NoticeResponsesFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoticeResponsesFull {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'messageKey': json['messageKey'],
        'titleKey': json['titleKey'],
        'parameters': json['parameters'],
        'id': json['id'],
        'isRead': json['isRead'],
        'category': json['category'],
    };
}

export function NoticeResponsesFullToJSON(json: any): NoticeResponsesFull {
    return NoticeResponsesFullToJSONTyped(json, false);
}

export function NoticeResponsesFullToJSONTyped(value?: NoticeResponsesFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'messageKey': value['messageKey'],
        'titleKey': value['titleKey'],
        'parameters': value['parameters'],
        'id': value['id'],
        'isRead': value['isRead'],
        'category': value['category'],
    };
}

