/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeDateInterval } from './SafeDateInterval';
import {
    SafeDateIntervalFromJSON,
    SafeDateIntervalFromJSONTyped,
    SafeDateIntervalToJSON,
    SafeDateIntervalToJSONTyped,
} from './SafeDateInterval';

/**
 * 
 * @export
 * @interface OfftimeResponsesFull
 */
export interface OfftimeResponsesFull {
    /**
     * 
     * @type {number}
     * @memberof OfftimeResponsesFull
     */
    coefficient: number;
    /**
     * 
     * @type {string}
     * @memberof OfftimeResponsesFull
     */
    reason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OfftimeResponsesFull
     */
    timeZoneId: string;
    /**
     * 
     * @type {string}
     * @memberof OfftimeResponsesFull
     */
    id: string;
    /**
     * 
     * @type {SafeDateInterval}
     * @memberof OfftimeResponsesFull
     */
    interval: SafeDateInterval;
}

/**
 * Check if a given object implements the OfftimeResponsesFull interface.
 */
export function instanceOfOfftimeResponsesFull(value: object): value is OfftimeResponsesFull {
    if (!('coefficient' in value) || value['coefficient'] === undefined) return false;
    if (!('timeZoneId' in value) || value['timeZoneId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    return true;
}

export function OfftimeResponsesFullFromJSON(json: any): OfftimeResponsesFull {
    return OfftimeResponsesFullFromJSONTyped(json, false);
}

export function OfftimeResponsesFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfftimeResponsesFull {
    if (json == null) {
        return json;
    }
    return {
        
        'coefficient': json['coefficient'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'timeZoneId': json['timeZoneId'],
        'id': json['id'],
        'interval': SafeDateIntervalFromJSON(json['interval']),
    };
}

export function OfftimeResponsesFullToJSON(json: any): OfftimeResponsesFull {
    return OfftimeResponsesFullToJSONTyped(json, false);
}

export function OfftimeResponsesFullToJSONTyped(value?: OfftimeResponsesFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coefficient': value['coefficient'],
        'reason': value['reason'],
        'timeZoneId': value['timeZoneId'],
        'id': value['id'],
        'interval': SafeDateIntervalToJSON(value['interval']),
    };
}

