/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeDateInterval } from './SafeDateInterval';
import {
    SafeDateIntervalFromJSON,
    SafeDateIntervalFromJSONTyped,
    SafeDateIntervalToJSON,
    SafeDateIntervalToJSONTyped,
} from './SafeDateInterval';

/**
 * 
 * @export
 * @interface OfftimeParametersCreate
 */
export interface OfftimeParametersCreate {
    /**
     * 
     * @type {string}
     * @memberof OfftimeParametersCreate
     */
    reason?: string | null;
    /**
     * 
     * @type {SafeDateInterval}
     * @memberof OfftimeParametersCreate
     */
    interval: SafeDateInterval;
    /**
     * 
     * @type {number}
     * @memberof OfftimeParametersCreate
     */
    coefficient: number;
}

/**
 * Check if a given object implements the OfftimeParametersCreate interface.
 */
export function instanceOfOfftimeParametersCreate(value: object): value is OfftimeParametersCreate {
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if (!('coefficient' in value) || value['coefficient'] === undefined) return false;
    return true;
}

export function OfftimeParametersCreateFromJSON(json: any): OfftimeParametersCreate {
    return OfftimeParametersCreateFromJSONTyped(json, false);
}

export function OfftimeParametersCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfftimeParametersCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
        'interval': SafeDateIntervalFromJSON(json['interval']),
        'coefficient': json['coefficient'],
    };
}

export function OfftimeParametersCreateToJSON(json: any): OfftimeParametersCreate {
    return OfftimeParametersCreateToJSONTyped(json, false);
}

export function OfftimeParametersCreateToJSONTyped(value?: OfftimeParametersCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'interval': SafeDateIntervalToJSON(value['interval']),
        'coefficient': value['coefficient'],
    };
}

