/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentSubscriptionResponse
 */
export interface PaymentSubscriptionResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentSubscriptionResponse
     */
    yearlyPayURL: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentSubscriptionResponse
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentSubscriptionResponse
     */
    monthlyPrice: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentSubscriptionResponse
     */
    monthlyPayURL: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentSubscriptionResponse
     */
    yearlyPrice: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentSubscriptionResponse
     */
    logoURL: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentSubscriptionResponse
     */
    title: string;
}

/**
 * Check if a given object implements the PaymentSubscriptionResponse interface.
 */
export function instanceOfPaymentSubscriptionResponse(value: object): value is PaymentSubscriptionResponse {
    if (!('yearlyPayURL' in value) || value['yearlyPayURL'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('monthlyPrice' in value) || value['monthlyPrice'] === undefined) return false;
    if (!('monthlyPayURL' in value) || value['monthlyPayURL'] === undefined) return false;
    if (!('yearlyPrice' in value) || value['yearlyPrice'] === undefined) return false;
    if (!('logoURL' in value) || value['logoURL'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function PaymentSubscriptionResponseFromJSON(json: any): PaymentSubscriptionResponse {
    return PaymentSubscriptionResponseFromJSONTyped(json, false);
}

export function PaymentSubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentSubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'yearlyPayURL': json['yearlyPayURL'],
        'description': json['description'],
        'monthlyPrice': json['monthlyPrice'],
        'monthlyPayURL': json['monthlyPayURL'],
        'yearlyPrice': json['yearlyPrice'],
        'logoURL': json['logoURL'],
        'title': json['title'],
    };
}

export function PaymentSubscriptionResponseToJSON(json: any): PaymentSubscriptionResponse {
    return PaymentSubscriptionResponseToJSONTyped(json, false);
}

export function PaymentSubscriptionResponseToJSONTyped(value?: PaymentSubscriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'yearlyPayURL': value['yearlyPayURL'],
        'description': value['description'],
        'monthlyPrice': value['monthlyPrice'],
        'monthlyPayURL': value['monthlyPayURL'],
        'yearlyPrice': value['yearlyPrice'],
        'logoURL': value['logoURL'],
        'title': value['title'],
    };
}

