/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PhoneTypes = {
    whatsapp: 'whatsapp',
    message: 'message',
    call: 'call'
} as const;
export type PhoneTypes = typeof PhoneTypes[keyof typeof PhoneTypes];


export function instanceOfPhoneTypes(value: any): boolean {
    for (const key in PhoneTypes) {
        if (Object.prototype.hasOwnProperty.call(PhoneTypes, key)) {
            if (PhoneTypes[key as keyof typeof PhoneTypes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PhoneTypesFromJSON(json: any): PhoneTypes {
    return PhoneTypesFromJSONTyped(json, false);
}

export function PhoneTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneTypes {
    return json as PhoneTypes;
}

export function PhoneTypesToJSON(value?: PhoneTypes | null): any {
    return value as any;
}

export function PhoneTypesToJSONTyped(value: any, ignoreDiscriminator: boolean): PhoneTypes {
    return value as PhoneTypes;
}

