/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialsSet } from './CredentialsSet';
import {
    CredentialsSetFromJSON,
    CredentialsSetFromJSONTyped,
    CredentialsSetToJSON,
    CredentialsSetToJSONTyped,
} from './CredentialsSet';
import type { SalaryResponsesRulesFull } from './SalaryResponsesRulesFull';
import {
    SalaryResponsesRulesFullFromJSON,
    SalaryResponsesRulesFullFromJSONTyped,
    SalaryResponsesRulesFullToJSON,
    SalaryResponsesRulesFullToJSONTyped,
} from './SalaryResponsesRulesFull';

/**
 * 
 * @export
 * @interface PositionResponsesFull
 */
export interface PositionResponsesFull {
    /**
     * 
     * @type {boolean}
     * @memberof PositionResponsesFull
     */
    owner: boolean;
    /**
     * 
     * @type {string}
     * @memberof PositionResponsesFull
     */
    title: string;
    /**
     * 
     * @type {CredentialsSet}
     * @memberof PositionResponsesFull
     */
    creds: CredentialsSet;
    /**
     * 
     * @type {string}
     * @memberof PositionResponsesFull
     */
    id: string;
    /**
     * 
     * @type {SalaryResponsesRulesFull}
     * @memberof PositionResponsesFull
     */
    salary: SalaryResponsesRulesFull;
}

/**
 * Check if a given object implements the PositionResponsesFull interface.
 */
export function instanceOfPositionResponsesFull(value: object): value is PositionResponsesFull {
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('creds' in value) || value['creds'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('salary' in value) || value['salary'] === undefined) return false;
    return true;
}

export function PositionResponsesFullFromJSON(json: any): PositionResponsesFull {
    return PositionResponsesFullFromJSONTyped(json, false);
}

export function PositionResponsesFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionResponsesFull {
    if (json == null) {
        return json;
    }
    return {
        
        'owner': json['owner'],
        'title': json['title'],
        'creds': CredentialsSetFromJSON(json['creds']),
        'id': json['id'],
        'salary': SalaryResponsesRulesFullFromJSON(json['salary']),
    };
}

export function PositionResponsesFullToJSON(json: any): PositionResponsesFull {
    return PositionResponsesFullToJSONTyped(json, false);
}

export function PositionResponsesFullToJSONTyped(value?: PositionResponsesFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'owner': value['owner'],
        'title': value['title'],
        'creds': CredentialsSetToJSON(value['creds']),
        'id': value['id'],
        'salary': SalaryResponsesRulesFullToJSON(value['salary']),
    };
}

