/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PositionResponsesPartial
 */
export interface PositionResponsesPartial {
    /**
     * 
     * @type {string}
     * @memberof PositionResponsesPartial
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PositionResponsesPartial
     */
    id: string;
}

/**
 * Check if a given object implements the PositionResponsesPartial interface.
 */
export function instanceOfPositionResponsesPartial(value: object): value is PositionResponsesPartial {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PositionResponsesPartialFromJSON(json: any): PositionResponsesPartial {
    return PositionResponsesPartialFromJSONTyped(json, false);
}

export function PositionResponsesPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionResponsesPartial {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'id': json['id'],
    };
}

export function PositionResponsesPartialToJSON(json: any): PositionResponsesPartial {
    return PositionResponsesPartialToJSONTyped(json, false);
}

export function PositionResponsesPartialToJSONTyped(value?: PositionResponsesPartial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'id': value['id'],
    };
}

