/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialsSet } from './CredentialsSet';
import {
    CredentialsSetFromJSON,
    CredentialsSetFromJSONTyped,
    CredentialsSetToJSON,
    CredentialsSetToJSONTyped,
} from './CredentialsSet';
import type { SalaryParametersRulesCreate } from './SalaryParametersRulesCreate';
import {
    SalaryParametersRulesCreateFromJSON,
    SalaryParametersRulesCreateFromJSONTyped,
    SalaryParametersRulesCreateToJSON,
    SalaryParametersRulesCreateToJSONTyped,
} from './SalaryParametersRulesCreate';

/**
 * 
 * @export
 * @interface PositionParametersPatch
 */
export interface PositionParametersPatch {
    /**
     * 
     * @type {string}
     * @memberof PositionParametersPatch
     */
    title?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PositionParametersPatch
     */
    makeOwner?: boolean | null;
    /**
     * 
     * @type {CredentialsSet}
     * @memberof PositionParametersPatch
     */
    creds?: CredentialsSet;
    /**
     * 
     * @type {SalaryParametersRulesCreate}
     * @memberof PositionParametersPatch
     */
    salary?: SalaryParametersRulesCreate;
}

/**
 * Check if a given object implements the PositionParametersPatch interface.
 */
export function instanceOfPositionParametersPatch(value: object): value is PositionParametersPatch {
    return true;
}

export function PositionParametersPatchFromJSON(json: any): PositionParametersPatch {
    return PositionParametersPatchFromJSONTyped(json, false);
}

export function PositionParametersPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionParametersPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'makeOwner': json['makeOwner'] == null ? undefined : json['makeOwner'],
        'creds': json['creds'] == null ? undefined : CredentialsSetFromJSON(json['creds']),
        'salary': json['salary'] == null ? undefined : SalaryParametersRulesCreateFromJSON(json['salary']),
    };
}

export function PositionParametersPatchToJSON(json: any): PositionParametersPatch {
    return PositionParametersPatchToJSONTyped(json, false);
}

export function PositionParametersPatchToJSONTyped(value?: PositionParametersPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'makeOwner': value['makeOwner'],
        'creds': CredentialsSetToJSON(value['creds']),
        'salary': SalaryParametersRulesCreateToJSON(value['salary']),
    };
}

