/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialsSet } from './CredentialsSet';
import {
    CredentialsSetFromJSON,
    CredentialsSetFromJSONTyped,
    CredentialsSetToJSON,
    CredentialsSetToJSONTyped,
} from './CredentialsSet';
import type { SalaryParametersRulesCreate } from './SalaryParametersRulesCreate';
import {
    SalaryParametersRulesCreateFromJSON,
    SalaryParametersRulesCreateFromJSONTyped,
    SalaryParametersRulesCreateToJSON,
    SalaryParametersRulesCreateToJSONTyped,
} from './SalaryParametersRulesCreate';

/**
 * 
 * @export
 * @interface PositionParametersCreate
 */
export interface PositionParametersCreate {
    /**
     * 
     * @type {SalaryParametersRulesCreate}
     * @memberof PositionParametersCreate
     */
    salary: SalaryParametersRulesCreate;
    /**
     * 
     * @type {string}
     * @memberof PositionParametersCreate
     */
    title: string;
    /**
     * 
     * @type {CredentialsSet}
     * @memberof PositionParametersCreate
     */
    creds: CredentialsSet;
    /**
     * 
     * @type {boolean}
     * @memberof PositionParametersCreate
     */
    makeOwner: boolean;
}

/**
 * Check if a given object implements the PositionParametersCreate interface.
 */
export function instanceOfPositionParametersCreate(value: object): value is PositionParametersCreate {
    if (!('salary' in value) || value['salary'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('creds' in value) || value['creds'] === undefined) return false;
    if (!('makeOwner' in value) || value['makeOwner'] === undefined) return false;
    return true;
}

export function PositionParametersCreateFromJSON(json: any): PositionParametersCreate {
    return PositionParametersCreateFromJSONTyped(json, false);
}

export function PositionParametersCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionParametersCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'salary': SalaryParametersRulesCreateFromJSON(json['salary']),
        'title': json['title'],
        'creds': CredentialsSetFromJSON(json['creds']),
        'makeOwner': json['makeOwner'],
    };
}

export function PositionParametersCreateToJSON(json: any): PositionParametersCreate {
    return PositionParametersCreateToJSONTyped(json, false);
}

export function PositionParametersCreateToJSONTyped(value?: PositionParametersCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'salary': SalaryParametersRulesCreateToJSON(value['salary']),
        'title': value['title'],
        'creds': CredentialsSetToJSON(value['creds']),
        'makeOwner': value['makeOwner'],
    };
}

