/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimetableResponsesComplexSlots } from './TimetableResponsesComplexSlots';
import {
    instanceOfTimetableResponsesComplexSlots,
    TimetableResponsesComplexSlotsFromJSON,
    TimetableResponsesComplexSlotsFromJSONTyped,
    TimetableResponsesComplexSlotsToJSON,
} from './TimetableResponsesComplexSlots';
import type { TimetableResponsesProcedureSlots } from './TimetableResponsesProcedureSlots';
import {
    instanceOfTimetableResponsesProcedureSlots,
    TimetableResponsesProcedureSlotsFromJSON,
    TimetableResponsesProcedureSlotsFromJSONTyped,
    TimetableResponsesProcedureSlotsToJSON,
} from './TimetableResponsesProcedureSlots';

/**
 * @type PostTimetablesSearchSlots200Response
 * 
 * @export
 */
export type PostTimetablesSearchSlots200Response = TimetableResponsesComplexSlots | TimetableResponsesProcedureSlots;

export function PostTimetablesSearchSlots200ResponseFromJSON(json: any): PostTimetablesSearchSlots200Response {
    return PostTimetablesSearchSlots200ResponseFromJSONTyped(json, false);
}

export function PostTimetablesSearchSlots200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTimetablesSearchSlots200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfTimetableResponsesComplexSlots(json)) {
        return TimetableResponsesComplexSlotsFromJSONTyped(json, true);
    }
    if (instanceOfTimetableResponsesProcedureSlots(json)) {
        return TimetableResponsesProcedureSlotsFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PostTimetablesSearchSlots200ResponseToJSON(json: any): any {
    return PostTimetablesSearchSlots200ResponseToJSONTyped(json, false);
}

export function PostTimetablesSearchSlots200ResponseToJSONTyped(value?: PostTimetablesSearchSlots200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTimetableResponsesComplexSlots(value)) {
        return TimetableResponsesComplexSlotsToJSON(value as TimetableResponsesComplexSlots);
    }
    if (instanceOfTimetableResponsesProcedureSlots(value)) {
        return TimetableResponsesProcedureSlotsToJSON(value as TimetableResponsesProcedureSlots);
    }
    return {};
}

