/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimetableParametersSearchSlotComplex } from './TimetableParametersSearchSlotComplex';
import {
    instanceOfTimetableParametersSearchSlotComplex,
    TimetableParametersSearchSlotComplexFromJSON,
    TimetableParametersSearchSlotComplexFromJSONTyped,
    TimetableParametersSearchSlotComplexToJSON,
} from './TimetableParametersSearchSlotComplex';
import type { TimetableParametersSearchSlotProcedure } from './TimetableParametersSearchSlotProcedure';
import {
    instanceOfTimetableParametersSearchSlotProcedure,
    TimetableParametersSearchSlotProcedureFromJSON,
    TimetableParametersSearchSlotProcedureFromJSONTyped,
    TimetableParametersSearchSlotProcedureToJSON,
} from './TimetableParametersSearchSlotProcedure';

/**
 * @type PostTimetablesSearchSlotsRequest
 * 
 * @export
 */
export type PostTimetablesSearchSlotsRequest = TimetableParametersSearchSlotComplex | TimetableParametersSearchSlotProcedure;

export function PostTimetablesSearchSlotsRequestFromJSON(json: any): PostTimetablesSearchSlotsRequest {
    return PostTimetablesSearchSlotsRequestFromJSONTyped(json, false);
}

export function PostTimetablesSearchSlotsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTimetablesSearchSlotsRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfTimetableParametersSearchSlotComplex(json)) {
        return TimetableParametersSearchSlotComplexFromJSONTyped(json, true);
    }
    if (instanceOfTimetableParametersSearchSlotProcedure(json)) {
        return TimetableParametersSearchSlotProcedureFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PostTimetablesSearchSlotsRequestToJSON(json: any): any {
    return PostTimetablesSearchSlotsRequestToJSONTyped(json, false);
}

export function PostTimetablesSearchSlotsRequestToJSONTyped(value?: PostTimetablesSearchSlotsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTimetableParametersSearchSlotComplex(value)) {
        return TimetableParametersSearchSlotComplexToJSON(value as TimetableParametersSearchSlotComplex);
    }
    if (instanceOfTimetableParametersSearchSlotProcedure(value)) {
        return TimetableParametersSearchSlotProcedureToJSON(value as TimetableParametersSearchSlotProcedure);
    }
    return {};
}

