/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';
import type { UpdateString } from './UpdateString';
import {
    UpdateStringFromJSON,
    UpdateStringFromJSONTyped,
    UpdateStringToJSON,
    UpdateStringToJSONTyped,
} from './UpdateString';

/**
 * 
 * @export
 * @interface ProcedureParametersUpdate
 */
export interface ProcedureParametersUpdate {
    /**
     * 
     * @type {number}
     * @memberof ProcedureParametersUpdate
     */
    duration?: number | null;
    /**
     * 
     * @type {UpdateString}
     * @memberof ProcedureParametersUpdate
     */
    description?: UpdateString;
    /**
     * 
     * @type {Price}
     * @memberof ProcedureParametersUpdate
     */
    price?: Price;
    /**
     * 
     * @type {UpdateString}
     * @memberof ProcedureParametersUpdate
     */
    alias?: UpdateString;
}

/**
 * Check if a given object implements the ProcedureParametersUpdate interface.
 */
export function instanceOfProcedureParametersUpdate(value: object): value is ProcedureParametersUpdate {
    return true;
}

export function ProcedureParametersUpdateFromJSON(json: any): ProcedureParametersUpdate {
    return ProcedureParametersUpdateFromJSONTyped(json, false);
}

export function ProcedureParametersUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureParametersUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : json['duration'],
        'description': json['description'] == null ? undefined : UpdateStringFromJSON(json['description']),
        'price': json['price'] == null ? undefined : PriceFromJSON(json['price']),
        'alias': json['alias'] == null ? undefined : UpdateStringFromJSON(json['alias']),
    };
}

export function ProcedureParametersUpdateToJSON(json: any): ProcedureParametersUpdate {
    return ProcedureParametersUpdateToJSONTyped(json, false);
}

export function ProcedureParametersUpdateToJSONTyped(value?: ProcedureParametersUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
        'description': UpdateStringToJSON(value['description']),
        'price': PriceToJSON(value['price']),
        'alias': UpdateStringToJSON(value['alias']),
    };
}

