/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcedureHelpersAllProcedureResponse } from './ProcedureHelpersAllProcedureResponse';
import {
    ProcedureHelpersAllProcedureResponseFromJSON,
    ProcedureHelpersAllProcedureResponseFromJSONTyped,
    ProcedureHelpersAllProcedureResponseToJSON,
    ProcedureHelpersAllProcedureResponseToJSONTyped,
} from './ProcedureHelpersAllProcedureResponse';

/**
 * 
 * @export
 * @interface ProcedureResponsesAll
 */
export interface ProcedureResponsesAll {
    /**
     * 
     * @type {Array<ProcedureHelpersAllProcedureResponse>}
     * @memberof ProcedureResponsesAll
     */
    procedures: Array<ProcedureHelpersAllProcedureResponse>;
}

/**
 * Check if a given object implements the ProcedureResponsesAll interface.
 */
export function instanceOfProcedureResponsesAll(value: object): value is ProcedureResponsesAll {
    if (!('procedures' in value) || value['procedures'] === undefined) return false;
    return true;
}

export function ProcedureResponsesAllFromJSON(json: any): ProcedureResponsesAll {
    return ProcedureResponsesAllFromJSONTyped(json, false);
}

export function ProcedureResponsesAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureResponsesAll {
    if (json == null) {
        return json;
    }
    return {
        
        'procedures': ((json['procedures'] as Array<any>).map(ProcedureHelpersAllProcedureResponseFromJSON)),
    };
}

export function ProcedureResponsesAllToJSON(json: any): ProcedureResponsesAll {
    return ProcedureResponsesAllToJSONTyped(json, false);
}

export function ProcedureResponsesAllToJSONTyped(value?: ProcedureResponsesAll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'procedures': ((value['procedures'] as Array<any>).map(ProcedureHelpersAllProcedureResponseToJSON)),
    };
}

