/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcedureHelpersCasePrice } from './ProcedureHelpersCasePrice';
import {
    ProcedureHelpersCasePriceFromJSON,
    ProcedureHelpersCasePriceFromJSONTyped,
    ProcedureHelpersCasePriceToJSON,
    ProcedureHelpersCasePriceToJSONTyped,
} from './ProcedureHelpersCasePrice';
import type { ProcedureHelpersCaseDuration } from './ProcedureHelpersCaseDuration';
import {
    ProcedureHelpersCaseDurationFromJSON,
    ProcedureHelpersCaseDurationFromJSONTyped,
    ProcedureHelpersCaseDurationToJSON,
    ProcedureHelpersCaseDurationToJSONTyped,
} from './ProcedureHelpersCaseDuration';

/**
 * 
 * @export
 * @interface ProcedureHelpersCaseResponse
 */
export interface ProcedureHelpersCaseResponse {
    /**
     * 
     * @type {ProcedureHelpersCaseDuration}
     * @memberof ProcedureHelpersCaseResponse
     */
    duration?: ProcedureHelpersCaseDuration;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersCaseResponse
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ProcedureHelpersCaseResponse
     */
    id: number;
    /**
     * 
     * @type {ProcedureHelpersCasePrice}
     * @memberof ProcedureHelpersCaseResponse
     */
    price?: ProcedureHelpersCasePrice;
}

/**
 * Check if a given object implements the ProcedureHelpersCaseResponse interface.
 */
export function instanceOfProcedureHelpersCaseResponse(value: object): value is ProcedureHelpersCaseResponse {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ProcedureHelpersCaseResponseFromJSON(json: any): ProcedureHelpersCaseResponse {
    return ProcedureHelpersCaseResponseFromJSONTyped(json, false);
}

export function ProcedureHelpersCaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureHelpersCaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : ProcedureHelpersCaseDurationFromJSON(json['duration']),
        'title': json['title'],
        'id': json['id'],
        'price': json['price'] == null ? undefined : ProcedureHelpersCasePriceFromJSON(json['price']),
    };
}

export function ProcedureHelpersCaseResponseToJSON(json: any): ProcedureHelpersCaseResponse {
    return ProcedureHelpersCaseResponseToJSONTyped(json, false);
}

export function ProcedureHelpersCaseResponseToJSONTyped(value?: ProcedureHelpersCaseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': ProcedureHelpersCaseDurationToJSON(value['duration']),
        'title': value['title'],
        'id': value['id'],
        'price': ProcedureHelpersCasePriceToJSON(value['price']),
    };
}

