/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcedureHelpersCreateProcedureResponse } from './ProcedureHelpersCreateProcedureResponse';
import {
    ProcedureHelpersCreateProcedureResponseFromJSON,
    ProcedureHelpersCreateProcedureResponseFromJSONTyped,
    ProcedureHelpersCreateProcedureResponseToJSON,
    ProcedureHelpersCreateProcedureResponseToJSONTyped,
} from './ProcedureHelpersCreateProcedureResponse';

/**
 * 
 * @export
 * @interface ProcedureResponsesCreate
 */
export interface ProcedureResponsesCreate {
    /**
     * 
     * @type {Array<ProcedureHelpersCreateProcedureResponse>}
     * @memberof ProcedureResponsesCreate
     */
    procedures: Array<ProcedureHelpersCreateProcedureResponse>;
}

/**
 * Check if a given object implements the ProcedureResponsesCreate interface.
 */
export function instanceOfProcedureResponsesCreate(value: object): value is ProcedureResponsesCreate {
    if (!('procedures' in value) || value['procedures'] === undefined) return false;
    return true;
}

export function ProcedureResponsesCreateFromJSON(json: any): ProcedureResponsesCreate {
    return ProcedureResponsesCreateFromJSONTyped(json, false);
}

export function ProcedureResponsesCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureResponsesCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'procedures': ((json['procedures'] as Array<any>).map(ProcedureHelpersCreateProcedureResponseFromJSON)),
    };
}

export function ProcedureResponsesCreateToJSON(json: any): ProcedureResponsesCreate {
    return ProcedureResponsesCreateToJSONTyped(json, false);
}

export function ProcedureResponsesCreateToJSONTyped(value?: ProcedureResponsesCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'procedures': ((value['procedures'] as Array<any>).map(ProcedureHelpersCreateProcedureResponseToJSON)),
    };
}

