/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';
import type { TranslatedServiceTag } from './TranslatedServiceTag';
import {
    TranslatedServiceTagFromJSON,
    TranslatedServiceTagFromJSONTyped,
    TranslatedServiceTagToJSON,
    TranslatedServiceTagToJSONTyped,
} from './TranslatedServiceTag';
import type { ProcedureHelpersParameterResponse } from './ProcedureHelpersParameterResponse';
import {
    ProcedureHelpersParameterResponseFromJSON,
    ProcedureHelpersParameterResponseFromJSONTyped,
    ProcedureHelpersParameterResponseToJSON,
    ProcedureHelpersParameterResponseToJSONTyped,
} from './ProcedureHelpersParameterResponse';

/**
 * 
 * @export
 * @interface ProcedureHelpersAllProcedureResponse
 */
export interface ProcedureHelpersAllProcedureResponse {
    /**
     * 
     * @type {Price}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    price: Price;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    serviceTitle: string;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    masterId: string;
    /**
     * 
     * @type {Array<ProcedureHelpersParameterResponse>}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    parameters: Array<ProcedureHelpersParameterResponse>;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    masterNickname: string;
    /**
     * 
     * @type {number}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    alias?: string | null;
    /**
     * 
     * @type {Array<TranslatedServiceTag>}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    serviceTags: Array<TranslatedServiceTag>;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    serviceId: string;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    masterAvatar: string;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersAllProcedureResponse
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ProcedureHelpersAllProcedureResponse interface.
 */
export function instanceOfProcedureHelpersAllProcedureResponse(value: object): value is ProcedureHelpersAllProcedureResponse {
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('serviceTitle' in value) || value['serviceTitle'] === undefined) return false;
    if (!('masterId' in value) || value['masterId'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('masterNickname' in value) || value['masterNickname'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('serviceTags' in value) || value['serviceTags'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('masterAvatar' in value) || value['masterAvatar'] === undefined) return false;
    return true;
}

export function ProcedureHelpersAllProcedureResponseFromJSON(json: any): ProcedureHelpersAllProcedureResponse {
    return ProcedureHelpersAllProcedureResponseFromJSONTyped(json, false);
}

export function ProcedureHelpersAllProcedureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureHelpersAllProcedureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'price': PriceFromJSON(json['price']),
        'serviceTitle': json['serviceTitle'],
        'masterId': json['masterId'],
        'parameters': ((json['parameters'] as Array<any>).map(ProcedureHelpersParameterResponseFromJSON)),
        'masterNickname': json['masterNickname'],
        'duration': json['duration'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'serviceTags': ((json['serviceTags'] as Array<any>).map(TranslatedServiceTagFromJSON)),
        'id': json['id'],
        'serviceId': json['serviceId'],
        'masterAvatar': json['masterAvatar'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ProcedureHelpersAllProcedureResponseToJSON(json: any): ProcedureHelpersAllProcedureResponse {
    return ProcedureHelpersAllProcedureResponseToJSONTyped(json, false);
}

export function ProcedureHelpersAllProcedureResponseToJSONTyped(value?: ProcedureHelpersAllProcedureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price': PriceToJSON(value['price']),
        'serviceTitle': value['serviceTitle'],
        'masterId': value['masterId'],
        'parameters': ((value['parameters'] as Array<any>).map(ProcedureHelpersParameterResponseToJSON)),
        'masterNickname': value['masterNickname'],
        'duration': value['duration'],
        'alias': value['alias'],
        'serviceTags': ((value['serviceTags'] as Array<any>).map(TranslatedServiceTagToJSON)),
        'id': value['id'],
        'serviceId': value['serviceId'],
        'masterAvatar': value['masterAvatar'],
        'description': value['description'],
    };
}

