/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcedureHelpersCaseDuration
 */
export interface ProcedureHelpersCaseDuration {
    /**
     * 
     * @type {number}
     * @memberof ProcedureHelpersCaseDuration
     */
    fixedValue: number;
}

/**
 * Check if a given object implements the ProcedureHelpersCaseDuration interface.
 */
export function instanceOfProcedureHelpersCaseDuration(value: object): value is ProcedureHelpersCaseDuration {
    if (!('fixedValue' in value) || value['fixedValue'] === undefined) return false;
    return true;
}

export function ProcedureHelpersCaseDurationFromJSON(json: any): ProcedureHelpersCaseDuration {
    return ProcedureHelpersCaseDurationFromJSONTyped(json, false);
}

export function ProcedureHelpersCaseDurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureHelpersCaseDuration {
    if (json == null) {
        return json;
    }
    return {
        
        'fixedValue': json['fixedValue'],
    };
}

export function ProcedureHelpersCaseDurationToJSON(json: any): ProcedureHelpersCaseDuration {
    return ProcedureHelpersCaseDurationToJSONTyped(json, false);
}

export function ProcedureHelpersCaseDurationToJSONTyped(value?: ProcedureHelpersCaseDuration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fixedValue': value['fixedValue'],
    };
}

