/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcedureHelpersCasePrice } from './ProcedureHelpersCasePrice';
import {
    ProcedureHelpersCasePriceFromJSON,
    ProcedureHelpersCasePriceFromJSONTyped,
    ProcedureHelpersCasePriceToJSON,
    ProcedureHelpersCasePriceToJSONTyped,
} from './ProcedureHelpersCasePrice';
import type { ProcedureHelpersCaseDuration } from './ProcedureHelpersCaseDuration';
import {
    ProcedureHelpersCaseDurationFromJSON,
    ProcedureHelpersCaseDurationFromJSONTyped,
    ProcedureHelpersCaseDurationToJSON,
    ProcedureHelpersCaseDurationToJSONTyped,
} from './ProcedureHelpersCaseDuration';

/**
 * 
 * @export
 * @interface ProcedureHelpersCreateCaseRequest
 */
export interface ProcedureHelpersCreateCaseRequest {
    /**
     * 
     * @type {ProcedureHelpersCasePrice}
     * @memberof ProcedureHelpersCreateCaseRequest
     */
    casePrice?: ProcedureHelpersCasePrice;
    /**
     * 
     * @type {ProcedureHelpersCaseDuration}
     * @memberof ProcedureHelpersCreateCaseRequest
     */
    caseDuration?: ProcedureHelpersCaseDuration;
    /**
     * 
     * @type {number}
     * @memberof ProcedureHelpersCreateCaseRequest
     */
    id: number;
}

/**
 * Check if a given object implements the ProcedureHelpersCreateCaseRequest interface.
 */
export function instanceOfProcedureHelpersCreateCaseRequest(value: object): value is ProcedureHelpersCreateCaseRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ProcedureHelpersCreateCaseRequestFromJSON(json: any): ProcedureHelpersCreateCaseRequest {
    return ProcedureHelpersCreateCaseRequestFromJSONTyped(json, false);
}

export function ProcedureHelpersCreateCaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureHelpersCreateCaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'casePrice': json['casePrice'] == null ? undefined : ProcedureHelpersCasePriceFromJSON(json['casePrice']),
        'caseDuration': json['caseDuration'] == null ? undefined : ProcedureHelpersCaseDurationFromJSON(json['caseDuration']),
        'id': json['id'],
    };
}

export function ProcedureHelpersCreateCaseRequestToJSON(json: any): ProcedureHelpersCreateCaseRequest {
    return ProcedureHelpersCreateCaseRequestToJSONTyped(json, false);
}

export function ProcedureHelpersCreateCaseRequestToJSONTyped(value?: ProcedureHelpersCreateCaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'casePrice': ProcedureHelpersCasePriceToJSON(value['casePrice']),
        'caseDuration': ProcedureHelpersCaseDurationToJSON(value['caseDuration']),
        'id': value['id'],
    };
}

