/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcedureHelpersCaseResponse } from './ProcedureHelpersCaseResponse';
import {
    ProcedureHelpersCaseResponseFromJSON,
    ProcedureHelpersCaseResponseFromJSONTyped,
    ProcedureHelpersCaseResponseToJSON,
    ProcedureHelpersCaseResponseToJSONTyped,
} from './ProcedureHelpersCaseResponse';

/**
 * 
 * @export
 * @interface ProcedureHelpersParameterResponse
 */
export interface ProcedureHelpersParameterResponse {
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersParameterResponse
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProcedureHelpersParameterResponse
     */
    optional: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersParameterResponse
     */
    title: string;
    /**
     * 
     * @type {Array<ProcedureHelpersCaseResponse>}
     * @memberof ProcedureHelpersParameterResponse
     */
    cases: Array<ProcedureHelpersCaseResponse>;
}

/**
 * Check if a given object implements the ProcedureHelpersParameterResponse interface.
 */
export function instanceOfProcedureHelpersParameterResponse(value: object): value is ProcedureHelpersParameterResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('optional' in value) || value['optional'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('cases' in value) || value['cases'] === undefined) return false;
    return true;
}

export function ProcedureHelpersParameterResponseFromJSON(json: any): ProcedureHelpersParameterResponse {
    return ProcedureHelpersParameterResponseFromJSONTyped(json, false);
}

export function ProcedureHelpersParameterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureHelpersParameterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'optional': json['optional'],
        'title': json['title'],
        'cases': ((json['cases'] as Array<any>).map(ProcedureHelpersCaseResponseFromJSON)),
    };
}

export function ProcedureHelpersParameterResponseToJSON(json: any): ProcedureHelpersParameterResponse {
    return ProcedureHelpersParameterResponseToJSONTyped(json, false);
}

export function ProcedureHelpersParameterResponseToJSONTyped(value?: ProcedureHelpersParameterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'optional': value['optional'],
        'title': value['title'],
        'cases': ((value['cases'] as Array<any>).map(ProcedureHelpersCaseResponseToJSON)),
    };
}

