/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcedureHelpersCreateCaseRequest } from './ProcedureHelpersCreateCaseRequest';
import {
    ProcedureHelpersCreateCaseRequestFromJSON,
    ProcedureHelpersCreateCaseRequestFromJSONTyped,
    ProcedureHelpersCreateCaseRequestToJSON,
    ProcedureHelpersCreateCaseRequestToJSONTyped,
} from './ProcedureHelpersCreateCaseRequest';

/**
 * 
 * @export
 * @interface ProcedureHelpersCreateParameterRequest
 */
export interface ProcedureHelpersCreateParameterRequest {
    /**
     * 
     * @type {string}
     * @memberof ProcedureHelpersCreateParameterRequest
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProcedureHelpersCreateParameterRequest
     */
    optional: boolean;
    /**
     * 
     * @type {Array<ProcedureHelpersCreateCaseRequest>}
     * @memberof ProcedureHelpersCreateParameterRequest
     */
    cases: Array<ProcedureHelpersCreateCaseRequest>;
}

/**
 * Check if a given object implements the ProcedureHelpersCreateParameterRequest interface.
 */
export function instanceOfProcedureHelpersCreateParameterRequest(value: object): value is ProcedureHelpersCreateParameterRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('optional' in value) || value['optional'] === undefined) return false;
    if (!('cases' in value) || value['cases'] === undefined) return false;
    return true;
}

export function ProcedureHelpersCreateParameterRequestFromJSON(json: any): ProcedureHelpersCreateParameterRequest {
    return ProcedureHelpersCreateParameterRequestFromJSONTyped(json, false);
}

export function ProcedureHelpersCreateParameterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureHelpersCreateParameterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'optional': json['optional'],
        'cases': ((json['cases'] as Array<any>).map(ProcedureHelpersCreateCaseRequestFromJSON)),
    };
}

export function ProcedureHelpersCreateParameterRequestToJSON(json: any): ProcedureHelpersCreateParameterRequest {
    return ProcedureHelpersCreateParameterRequestToJSONTyped(json, false);
}

export function ProcedureHelpersCreateParameterRequestToJSONTyped(value?: ProcedureHelpersCreateParameterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'optional': value['optional'],
        'cases': ((value['cases'] as Array<any>).map(ProcedureHelpersCreateCaseRequestToJSON)),
    };
}

