/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcedureHelpersCasePrice
 */
export interface ProcedureHelpersCasePrice {
    /**
     * 
     * @type {number}
     * @memberof ProcedureHelpersCasePrice
     */
    fixedValue: number;
}

/**
 * Check if a given object implements the ProcedureHelpersCasePrice interface.
 */
export function instanceOfProcedureHelpersCasePrice(value: object): value is ProcedureHelpersCasePrice {
    if (!('fixedValue' in value) || value['fixedValue'] === undefined) return false;
    return true;
}

export function ProcedureHelpersCasePriceFromJSON(json: any): ProcedureHelpersCasePrice {
    return ProcedureHelpersCasePriceFromJSONTyped(json, false);
}

export function ProcedureHelpersCasePriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureHelpersCasePrice {
    if (json == null) {
        return json;
    }
    return {
        
        'fixedValue': json['fixedValue'],
    };
}

export function ProcedureHelpersCasePriceToJSON(json: any): ProcedureHelpersCasePrice {
    return ProcedureHelpersCasePriceToJSONTyped(json, false);
}

export function ProcedureHelpersCasePriceToJSONTyped(value?: ProcedureHelpersCasePrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fixedValue': value['fixedValue'],
    };
}

