/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcedureHelpersCreateParameterRequest } from './ProcedureHelpersCreateParameterRequest';
import {
    ProcedureHelpersCreateParameterRequestFromJSON,
    ProcedureHelpersCreateParameterRequestFromJSONTyped,
    ProcedureHelpersCreateParameterRequestToJSON,
    ProcedureHelpersCreateParameterRequestToJSONTyped,
} from './ProcedureHelpersCreateParameterRequest';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';

/**
 * 
 * @export
 * @interface ProcedureParametersCreate
 */
export interface ProcedureParametersCreate {
    /**
     * 
     * @type {Price}
     * @memberof ProcedureParametersCreate
     */
    price: Price;
    /**
     * 
     * @type {string}
     * @memberof ProcedureParametersCreate
     */
    alias?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcedureParametersCreate
     */
    serviceId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProcedureParametersCreate
     */
    employeeIds: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ProcedureParametersCreate
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ProcedureParametersCreate
     */
    description?: string | null;
    /**
     * 
     * @type {Array<ProcedureHelpersCreateParameterRequest>}
     * @memberof ProcedureParametersCreate
     */
    parameters: Array<ProcedureHelpersCreateParameterRequest>;
}

/**
 * Check if a given object implements the ProcedureParametersCreate interface.
 */
export function instanceOfProcedureParametersCreate(value: object): value is ProcedureParametersCreate {
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('employeeIds' in value) || value['employeeIds'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    return true;
}

export function ProcedureParametersCreateFromJSON(json: any): ProcedureParametersCreate {
    return ProcedureParametersCreateFromJSONTyped(json, false);
}

export function ProcedureParametersCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureParametersCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'price': PriceFromJSON(json['price']),
        'alias': json['alias'] == null ? undefined : json['alias'],
        'serviceId': json['serviceId'],
        'employeeIds': json['employeeIds'],
        'duration': json['duration'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': ((json['parameters'] as Array<any>).map(ProcedureHelpersCreateParameterRequestFromJSON)),
    };
}

export function ProcedureParametersCreateToJSON(json: any): ProcedureParametersCreate {
    return ProcedureParametersCreateToJSONTyped(json, false);
}

export function ProcedureParametersCreateToJSONTyped(value?: ProcedureParametersCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price': PriceToJSON(value['price']),
        'alias': value['alias'],
        'serviceId': value['serviceId'],
        'employeeIds': value['employeeIds'],
        'duration': value['duration'],
        'description': value['description'],
        'parameters': ((value['parameters'] as Array<any>).map(ProcedureHelpersCreateParameterRequestToJSON)),
    };
}

