/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SafeDateInterval
 */
export interface SafeDateInterval {
    /**
     * 
     * @type {Date}
     * @memberof SafeDateInterval
     */
    end: Date;
    /**
     * 
     * @type {Date}
     * @memberof SafeDateInterval
     */
    start: Date;
}

/**
 * Check if a given object implements the SafeDateInterval interface.
 */
export function instanceOfSafeDateInterval(value: object): value is SafeDateInterval {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function SafeDateIntervalFromJSON(json: any): SafeDateInterval {
    return SafeDateIntervalFromJSONTyped(json, false);
}

export function SafeDateIntervalFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeDateInterval {
    if (json == null) {
        return json;
    }
    return {
        
        'end': (new Date(json['end'])),
        'start': (new Date(json['start'])),
    };
}

export function SafeDateIntervalToJSON(json: any): SafeDateInterval {
    return SafeDateIntervalToJSONTyped(json, false);
}

export function SafeDateIntervalToJSONTyped(value?: SafeDateInterval | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end': value['end'].toISOString(),
        'start': value['start'].toISOString(),
    };
}

