/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalaryResponsesHelpersService } from './SalaryResponsesHelpersService';
import {
    SalaryResponsesHelpersServiceFromJSON,
    SalaryResponsesHelpersServiceFromJSONTyped,
    SalaryResponsesHelpersServiceToJSON,
    SalaryResponsesHelpersServiceToJSONTyped,
} from './SalaryResponsesHelpersService';
import type { SalaryPaymentType } from './SalaryPaymentType';
import {
    SalaryPaymentTypeFromJSON,
    SalaryPaymentTypeFromJSONTyped,
    SalaryPaymentTypeToJSON,
    SalaryPaymentTypeToJSONTyped,
} from './SalaryPaymentType';

/**
 * 
 * @export
 * @interface SalaryResponsesHelpersServiceWithPaymentType
 */
export interface SalaryResponsesHelpersServiceWithPaymentType {
    /**
     * 
     * @type {SalaryResponsesHelpersService}
     * @memberof SalaryResponsesHelpersServiceWithPaymentType
     */
    service: SalaryResponsesHelpersService;
    /**
     * 
     * @type {SalaryPaymentType}
     * @memberof SalaryResponsesHelpersServiceWithPaymentType
     */
    paymentType: SalaryPaymentType;
}

/**
 * Check if a given object implements the SalaryResponsesHelpersServiceWithPaymentType interface.
 */
export function instanceOfSalaryResponsesHelpersServiceWithPaymentType(value: object): value is SalaryResponsesHelpersServiceWithPaymentType {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('paymentType' in value) || value['paymentType'] === undefined) return false;
    return true;
}

export function SalaryResponsesHelpersServiceWithPaymentTypeFromJSON(json: any): SalaryResponsesHelpersServiceWithPaymentType {
    return SalaryResponsesHelpersServiceWithPaymentTypeFromJSONTyped(json, false);
}

export function SalaryResponsesHelpersServiceWithPaymentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalaryResponsesHelpersServiceWithPaymentType {
    if (json == null) {
        return json;
    }
    return {
        
        'service': SalaryResponsesHelpersServiceFromJSON(json['service']),
        'paymentType': SalaryPaymentTypeFromJSON(json['paymentType']),
    };
}

export function SalaryResponsesHelpersServiceWithPaymentTypeToJSON(json: any): SalaryResponsesHelpersServiceWithPaymentType {
    return SalaryResponsesHelpersServiceWithPaymentTypeToJSONTyped(json, false);
}

export function SalaryResponsesHelpersServiceWithPaymentTypeToJSONTyped(value?: SalaryResponsesHelpersServiceWithPaymentType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': SalaryResponsesHelpersServiceToJSON(value['service']),
        'paymentType': SalaryPaymentTypeToJSON(value['paymentType']),
    };
}

