/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceTags } from './ServiceTags';
import {
    ServiceTagsFromJSON,
    ServiceTagsFromJSONTyped,
    ServiceTagsToJSON,
    ServiceTagsToJSONTyped,
} from './ServiceTags';

/**
 * 
 * @export
 * @interface SalaryResponsesHelpersService
 */
export interface SalaryResponsesHelpersService {
    /**
     * 
     * @type {string}
     * @memberof SalaryResponsesHelpersService
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SalaryResponsesHelpersService
     */
    title: string;
    /**
     * 
     * @type {Array<ServiceTags>}
     * @memberof SalaryResponsesHelpersService
     */
    category: Array<ServiceTags>;
    /**
     * 
     * @type {string}
     * @memberof SalaryResponsesHelpersService
     */
    description: string;
}

/**
 * Check if a given object implements the SalaryResponsesHelpersService interface.
 */
export function instanceOfSalaryResponsesHelpersService(value: object): value is SalaryResponsesHelpersService {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SalaryResponsesHelpersServiceFromJSON(json: any): SalaryResponsesHelpersService {
    return SalaryResponsesHelpersServiceFromJSONTyped(json, false);
}

export function SalaryResponsesHelpersServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalaryResponsesHelpersService {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'category': ((json['category'] as Array<any>).map(ServiceTagsFromJSON)),
        'description': json['description'],
    };
}

export function SalaryResponsesHelpersServiceToJSON(json: any): SalaryResponsesHelpersService {
    return SalaryResponsesHelpersServiceToJSONTyped(json, false);
}

export function SalaryResponsesHelpersServiceToJSONTyped(value?: SalaryResponsesHelpersService | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'category': ((value['category'] as Array<any>).map(ServiceTagsToJSON)),
        'description': value['description'],
    };
}

