/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalaryPaymentType
 */
export interface SalaryPaymentType {
    /**
     * 
     * @type {number}
     * @memberof SalaryPaymentType
     */
    percent: number;
}

/**
 * Check if a given object implements the SalaryPaymentType interface.
 */
export function instanceOfSalaryPaymentType(value: object): value is SalaryPaymentType {
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function SalaryPaymentTypeFromJSON(json: any): SalaryPaymentType {
    return SalaryPaymentTypeFromJSONTyped(json, false);
}

export function SalaryPaymentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalaryPaymentType {
    if (json == null) {
        return json;
    }
    return {
        
        'percent': json['percent'],
    };
}

export function SalaryPaymentTypeToJSON(json: any): SalaryPaymentType {
    return SalaryPaymentTypeToJSONTyped(json, false);
}

export function SalaryPaymentTypeToJSONTyped(value?: SalaryPaymentType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percent': value['percent'],
    };
}

