/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Wage } from './Wage';
import {
    WageFromJSON,
    WageFromJSONTyped,
    WageToJSON,
    WageToJSONTyped,
} from './Wage';
import type { SalaryPaymentType } from './SalaryPaymentType';
import {
    SalaryPaymentTypeFromJSON,
    SalaryPaymentTypeFromJSONTyped,
    SalaryPaymentTypeToJSON,
    SalaryPaymentTypeToJSONTyped,
} from './SalaryPaymentType';

/**
 * 
 * @export
 * @interface SalaryParametersRulesCreate
 */
export interface SalaryParametersRulesCreate {
    /**
     * 
     * @type {Array<SalaryPaymentType>}
     * @memberof SalaryParametersRulesCreate
     */
    grid?: Array<SalaryPaymentType> | null;
    /**
     * 
     * @type {number}
     * @memberof SalaryParametersRulesCreate
     */
    percent?: number | null;
    /**
     * 
     * @type {Wage}
     * @memberof SalaryParametersRulesCreate
     */
    wage?: Wage;
}

/**
 * Check if a given object implements the SalaryParametersRulesCreate interface.
 */
export function instanceOfSalaryParametersRulesCreate(value: object): value is SalaryParametersRulesCreate {
    return true;
}

export function SalaryParametersRulesCreateFromJSON(json: any): SalaryParametersRulesCreate {
    return SalaryParametersRulesCreateFromJSONTyped(json, false);
}

export function SalaryParametersRulesCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalaryParametersRulesCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'grid': json['grid'] == null ? undefined : ((json['grid'] as Array<any>).map(SalaryPaymentTypeFromJSON)),
        'percent': json['percent'] == null ? undefined : json['percent'],
        'wage': json['wage'] == null ? undefined : WageFromJSON(json['wage']),
    };
}

export function SalaryParametersRulesCreateToJSON(json: any): SalaryParametersRulesCreate {
    return SalaryParametersRulesCreateToJSONTyped(json, false);
}

export function SalaryParametersRulesCreateToJSONTyped(value?: SalaryParametersRulesCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grid': value['grid'] == null ? undefined : ((value['grid'] as Array<any>).map(SalaryPaymentTypeToJSON)),
        'percent': value['percent'],
        'wage': WageToJSON(value['wage']),
    };
}

