/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Wage } from './Wage';
import {
    WageFromJSON,
    WageFromJSONTyped,
    WageToJSON,
    WageToJSONTyped,
} from './Wage';
import type { SalaryResponsesHelpersServiceWithPaymentType } from './SalaryResponsesHelpersServiceWithPaymentType';
import {
    SalaryResponsesHelpersServiceWithPaymentTypeFromJSON,
    SalaryResponsesHelpersServiceWithPaymentTypeFromJSONTyped,
    SalaryResponsesHelpersServiceWithPaymentTypeToJSON,
    SalaryResponsesHelpersServiceWithPaymentTypeToJSONTyped,
} from './SalaryResponsesHelpersServiceWithPaymentType';

/**
 * 
 * @export
 * @interface SalaryResponsesRulesFull
 */
export interface SalaryResponsesRulesFull {
    /**
     * 
     * @type {Wage}
     * @memberof SalaryResponsesRulesFull
     */
    wage?: Wage;
    /**
     * 
     * @type {number}
     * @memberof SalaryResponsesRulesFull
     */
    percent?: number | null;
    /**
     * 
     * @type {Array<SalaryResponsesHelpersServiceWithPaymentType>}
     * @memberof SalaryResponsesRulesFull
     */
    grid?: Array<SalaryResponsesHelpersServiceWithPaymentType> | null;
}

/**
 * Check if a given object implements the SalaryResponsesRulesFull interface.
 */
export function instanceOfSalaryResponsesRulesFull(value: object): value is SalaryResponsesRulesFull {
    return true;
}

export function SalaryResponsesRulesFullFromJSON(json: any): SalaryResponsesRulesFull {
    return SalaryResponsesRulesFullFromJSONTyped(json, false);
}

export function SalaryResponsesRulesFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalaryResponsesRulesFull {
    if (json == null) {
        return json;
    }
    return {
        
        'wage': json['wage'] == null ? undefined : WageFromJSON(json['wage']),
        'percent': json['percent'] == null ? undefined : json['percent'],
        'grid': json['grid'] == null ? undefined : ((json['grid'] as Array<any>).map(SalaryResponsesHelpersServiceWithPaymentTypeFromJSON)),
    };
}

export function SalaryResponsesRulesFullToJSON(json: any): SalaryResponsesRulesFull {
    return SalaryResponsesRulesFullToJSONTyped(json, false);
}

export function SalaryResponsesRulesFullToJSONTyped(value?: SalaryResponsesRulesFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wage': WageToJSON(value['wage']),
        'percent': value['percent'],
        'grid': value['grid'] == null ? undefined : ((value['grid'] as Array<any>).map(SalaryResponsesHelpersServiceWithPaymentTypeToJSON)),
    };
}

