/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SalonType = {
    individual: 'individual',
    chain: 'chain',
    master: 'master'
} as const;
export type SalonType = typeof SalonType[keyof typeof SalonType];


export function instanceOfSalonType(value: any): boolean {
    for (const key in SalonType) {
        if (Object.prototype.hasOwnProperty.call(SalonType, key)) {
            if (SalonType[key as keyof typeof SalonType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SalonTypeFromJSON(json: any): SalonType {
    return SalonTypeFromJSONTyped(json, false);
}

export function SalonTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalonType {
    return json as SalonType;
}

export function SalonTypeToJSON(value?: SalonType | null): any {
    return value as any;
}

export function SalonTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SalonType {
    return value as SalonType;
}

