/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleWeek } from './ScheduleWeek';
import {
    ScheduleWeekFromJSON,
    ScheduleWeekFromJSONTyped,
    ScheduleWeekToJSON,
    ScheduleWeekToJSONTyped,
} from './ScheduleWeek';

/**
 * 
 * @export
 * @interface SchedulePattern
 */
export interface SchedulePattern {
    /**
     * 
     * @type {ScheduleWeek}
     * @memberof SchedulePattern
     */
    weekly: ScheduleWeek;
}

/**
 * Check if a given object implements the SchedulePattern interface.
 */
export function instanceOfSchedulePattern(value: object): value is SchedulePattern {
    if (!('weekly' in value) || value['weekly'] === undefined) return false;
    return true;
}

export function SchedulePatternFromJSON(json: any): SchedulePattern {
    return SchedulePatternFromJSONTyped(json, false);
}

export function SchedulePatternFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulePattern {
    if (json == null) {
        return json;
    }
    return {
        
        'weekly': ScheduleWeekFromJSON(json['weekly']),
    };
}

export function SchedulePatternToJSON(json: any): SchedulePattern {
    return SchedulePatternToJSONTyped(json, false);
}

export function SchedulePatternToJSONTyped(value?: SchedulePattern | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weekly': ScheduleWeekToJSON(value['weekly']),
    };
}

