/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleDay } from './ScheduleDay';
import {
    ScheduleDayFromJSON,
    ScheduleDayFromJSONTyped,
    ScheduleDayToJSON,
    ScheduleDayToJSONTyped,
} from './ScheduleDay';

/**
 * 
 * @export
 * @interface ScheduleWeek
 */
export interface ScheduleWeek {
    /**
     * 
     * @type {ScheduleDay}
     * @memberof ScheduleWeek
     */
    sunday?: ScheduleDay;
    /**
     * 
     * @type {ScheduleDay}
     * @memberof ScheduleWeek
     */
    friday?: ScheduleDay;
    /**
     * 
     * @type {ScheduleDay}
     * @memberof ScheduleWeek
     */
    thursday?: ScheduleDay;
    /**
     * 
     * @type {ScheduleDay}
     * @memberof ScheduleWeek
     */
    tuesday?: ScheduleDay;
    /**
     * 
     * @type {ScheduleDay}
     * @memberof ScheduleWeek
     */
    monday?: ScheduleDay;
    /**
     * 
     * @type {ScheduleDay}
     * @memberof ScheduleWeek
     */
    saturday?: ScheduleDay;
    /**
     * 
     * @type {ScheduleDay}
     * @memberof ScheduleWeek
     */
    wednesday?: ScheduleDay;
}

/**
 * Check if a given object implements the ScheduleWeek interface.
 */
export function instanceOfScheduleWeek(value: object): value is ScheduleWeek {
    return true;
}

export function ScheduleWeekFromJSON(json: any): ScheduleWeek {
    return ScheduleWeekFromJSONTyped(json, false);
}

export function ScheduleWeekFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleWeek {
    if (json == null) {
        return json;
    }
    return {
        
        'sunday': json['sunday'] == null ? undefined : ScheduleDayFromJSON(json['sunday']),
        'friday': json['friday'] == null ? undefined : ScheduleDayFromJSON(json['friday']),
        'thursday': json['thursday'] == null ? undefined : ScheduleDayFromJSON(json['thursday']),
        'tuesday': json['tuesday'] == null ? undefined : ScheduleDayFromJSON(json['tuesday']),
        'monday': json['monday'] == null ? undefined : ScheduleDayFromJSON(json['monday']),
        'saturday': json['saturday'] == null ? undefined : ScheduleDayFromJSON(json['saturday']),
        'wednesday': json['wednesday'] == null ? undefined : ScheduleDayFromJSON(json['wednesday']),
    };
}

export function ScheduleWeekToJSON(json: any): ScheduleWeek {
    return ScheduleWeekToJSONTyped(json, false);
}

export function ScheduleWeekToJSONTyped(value?: ScheduleWeek | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sunday': ScheduleDayToJSON(value['sunday']),
        'friday': ScheduleDayToJSON(value['friday']),
        'thursday': ScheduleDayToJSON(value['thursday']),
        'tuesday': ScheduleDayToJSON(value['tuesday']),
        'monday': ScheduleDayToJSON(value['monday']),
        'saturday': ScheduleDayToJSON(value['saturday']),
        'wednesday': ScheduleDayToJSON(value['wednesday']),
    };
}

