/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleDay
 */
export interface ScheduleDay {
    /**
     * 
     * @type {string}
     * @memberof ScheduleDay
     */
    workTime: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScheduleDay
     */
    offTime: Array<string>;
}

/**
 * Check if a given object implements the ScheduleDay interface.
 */
export function instanceOfScheduleDay(value: object): value is ScheduleDay {
    if (!('workTime' in value) || value['workTime'] === undefined) return false;
    if (!('offTime' in value) || value['offTime'] === undefined) return false;
    return true;
}

export function ScheduleDayFromJSON(json: any): ScheduleDay {
    return ScheduleDayFromJSONTyped(json, false);
}

export function ScheduleDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleDay {
    if (json == null) {
        return json;
    }
    return {
        
        'workTime': json['workTime'],
        'offTime': json['offTime'],
    };
}

export function ScheduleDayToJSON(json: any): ScheduleDay {
    return ScheduleDayToJSONTyped(json, false);
}

export function ScheduleDayToJSONTyped(value?: ScheduleDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workTime': value['workTime'],
        'offTime': value['offTime'],
    };
}

