/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResponsesHelpersSuggest
 */
export interface SearchResponsesHelpersSuggest {
    /**
     * 
     * @type {string}
     * @memberof SearchResponsesHelpersSuggest
     */
    value: string;
}

/**
 * Check if a given object implements the SearchResponsesHelpersSuggest interface.
 */
export function instanceOfSearchResponsesHelpersSuggest(value: object): value is SearchResponsesHelpersSuggest {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SearchResponsesHelpersSuggestFromJSON(json: any): SearchResponsesHelpersSuggest {
    return SearchResponsesHelpersSuggestFromJSONTyped(json, false);
}

export function SearchResponsesHelpersSuggestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponsesHelpersSuggest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function SearchResponsesHelpersSuggestToJSON(json: any): SearchResponsesHelpersSuggest {
    return SearchResponsesHelpersSuggestToJSONTyped(json, false);
}

export function SearchResponsesHelpersSuggestToJSONTyped(value?: SearchResponsesHelpersSuggest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

