/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceTags } from './ServiceTags';
import {
    ServiceTagsFromJSON,
    ServiceTagsFromJSONTyped,
    ServiceTagsToJSON,
    ServiceTagsToJSONTyped,
} from './ServiceTags';

/**
 * 
 * @export
 * @interface ServiceParametersCreate
 */
export interface ServiceParametersCreate {
    /**
     * 
     * @type {string}
     * @memberof ServiceParametersCreate
     */
    title: string;
    /**
     * 
     * @type {Array<ServiceTags>}
     * @memberof ServiceParametersCreate
     */
    tags: Array<ServiceTags>;
}

/**
 * Check if a given object implements the ServiceParametersCreate interface.
 */
export function instanceOfServiceParametersCreate(value: object): value is ServiceParametersCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function ServiceParametersCreateFromJSON(json: any): ServiceParametersCreate {
    return ServiceParametersCreateFromJSONTyped(json, false);
}

export function ServiceParametersCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceParametersCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'tags': ((json['tags'] as Array<any>).map(ServiceTagsFromJSON)),
    };
}

export function ServiceParametersCreateToJSON(json: any): ServiceParametersCreate {
    return ServiceParametersCreateToJSONTyped(json, false);
}

export function ServiceParametersCreateToJSONTyped(value?: ServiceParametersCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'tags': ((value['tags'] as Array<any>).map(ServiceTagsToJSON)),
    };
}

