/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TranslatedServiceTag } from './TranslatedServiceTag';
import {
    TranslatedServiceTagFromJSON,
    TranslatedServiceTagFromJSONTyped,
    TranslatedServiceTagToJSON,
    TranslatedServiceTagToJSONTyped,
} from './TranslatedServiceTag';

/**
 * 
 * @export
 * @interface ServiceHelpersServiceResponse
 */
export interface ServiceHelpersServiceResponse {
    /**
     * 
     * @type {Array<TranslatedServiceTag>}
     * @memberof ServiceHelpersServiceResponse
     */
    tags: Array<TranslatedServiceTag>;
    /**
     * 
     * @type {string}
     * @memberof ServiceHelpersServiceResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceHelpersServiceResponse
     */
    id: string;
}

/**
 * Check if a given object implements the ServiceHelpersServiceResponse interface.
 */
export function instanceOfServiceHelpersServiceResponse(value: object): value is ServiceHelpersServiceResponse {
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ServiceHelpersServiceResponseFromJSON(json: any): ServiceHelpersServiceResponse {
    return ServiceHelpersServiceResponseFromJSONTyped(json, false);
}

export function ServiceHelpersServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceHelpersServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': ((json['tags'] as Array<any>).map(TranslatedServiceTagFromJSON)),
        'title': json['title'],
        'id': json['id'],
    };
}

export function ServiceHelpersServiceResponseToJSON(json: any): ServiceHelpersServiceResponse {
    return ServiceHelpersServiceResponseToJSONTyped(json, false);
}

export function ServiceHelpersServiceResponseToJSONTyped(value?: ServiceHelpersServiceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': ((value['tags'] as Array<any>).map(TranslatedServiceTagToJSON)),
        'title': value['title'],
        'id': value['id'],
    };
}

