/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceHelpersCase } from './ServiceHelpersCase';
import {
    ServiceHelpersCaseFromJSON,
    ServiceHelpersCaseFromJSONTyped,
    ServiceHelpersCaseToJSON,
    ServiceHelpersCaseToJSONTyped,
} from './ServiceHelpersCase';

/**
 * 
 * @export
 * @interface ServiceHelpersParameter
 */
export interface ServiceHelpersParameter {
    /**
     * 
     * @type {string}
     * @memberof ServiceHelpersParameter
     */
    title: string;
    /**
     * 
     * @type {Array<ServiceHelpersCase>}
     * @memberof ServiceHelpersParameter
     */
    cases: Array<ServiceHelpersCase>;
    /**
     * 
     * @type {string}
     * @memberof ServiceHelpersParameter
     */
    id: string;
}

/**
 * Check if a given object implements the ServiceHelpersParameter interface.
 */
export function instanceOfServiceHelpersParameter(value: object): value is ServiceHelpersParameter {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('cases' in value) || value['cases'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ServiceHelpersParameterFromJSON(json: any): ServiceHelpersParameter {
    return ServiceHelpersParameterFromJSONTyped(json, false);
}

export function ServiceHelpersParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceHelpersParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'cases': ((json['cases'] as Array<any>).map(ServiceHelpersCaseFromJSON)),
        'id': json['id'],
    };
}

export function ServiceHelpersParameterToJSON(json: any): ServiceHelpersParameter {
    return ServiceHelpersParameterToJSONTyped(json, false);
}

export function ServiceHelpersParameterToJSONTyped(value?: ServiceHelpersParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'cases': ((value['cases'] as Array<any>).map(ServiceHelpersCaseToJSON)),
        'id': value['id'],
    };
}

