/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceHelpersCase
 */
export interface ServiceHelpersCase {
    /**
     * 
     * @type {string}
     * @memberof ServiceHelpersCase
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceHelpersCase
     */
    id: number;
}

/**
 * Check if a given object implements the ServiceHelpersCase interface.
 */
export function instanceOfServiceHelpersCase(value: object): value is ServiceHelpersCase {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ServiceHelpersCaseFromJSON(json: any): ServiceHelpersCase {
    return ServiceHelpersCaseFromJSONTyped(json, false);
}

export function ServiceHelpersCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceHelpersCase {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'id': json['id'],
    };
}

export function ServiceHelpersCaseToJSON(json: any): ServiceHelpersCase {
    return ServiceHelpersCaseToJSONTyped(json, false);
}

export function ServiceHelpersCaseToJSONTyped(value?: ServiceHelpersCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'id': value['id'],
    };
}

