/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TranslatedServiceTag } from './TranslatedServiceTag';
import {
    TranslatedServiceTagFromJSON,
    TranslatedServiceTagFromJSONTyped,
    TranslatedServiceTagToJSON,
    TranslatedServiceTagToJSONTyped,
} from './TranslatedServiceTag';

/**
 * 
 * @export
 * @interface ServiceResponsesCreate
 */
export interface ServiceResponsesCreate {
    /**
     * 
     * @type {Array<TranslatedServiceTag>}
     * @memberof ServiceResponsesCreate
     */
    tags: Array<TranslatedServiceTag>;
    /**
     * 
     * @type {string}
     * @memberof ServiceResponsesCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResponsesCreate
     */
    id: string;
}

/**
 * Check if a given object implements the ServiceResponsesCreate interface.
 */
export function instanceOfServiceResponsesCreate(value: object): value is ServiceResponsesCreate {
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ServiceResponsesCreateFromJSON(json: any): ServiceResponsesCreate {
    return ServiceResponsesCreateFromJSONTyped(json, false);
}

export function ServiceResponsesCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResponsesCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': ((json['tags'] as Array<any>).map(TranslatedServiceTagFromJSON)),
        'title': json['title'],
        'id': json['id'],
    };
}

export function ServiceResponsesCreateToJSON(json: any): ServiceResponsesCreate {
    return ServiceResponsesCreateToJSONTyped(json, false);
}

export function ServiceResponsesCreateToJSONTyped(value?: ServiceResponsesCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': ((value['tags'] as Array<any>).map(TranslatedServiceTagToJSON)),
        'title': value['title'],
        'id': value['id'],
    };
}

