/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceHelpersServiceResponse } from './ServiceHelpersServiceResponse';
import {
    ServiceHelpersServiceResponseFromJSON,
    ServiceHelpersServiceResponseFromJSONTyped,
    ServiceHelpersServiceResponseToJSON,
    ServiceHelpersServiceResponseToJSONTyped,
} from './ServiceHelpersServiceResponse';

/**
 * 
 * @export
 * @interface ServiceResponsesAll
 */
export interface ServiceResponsesAll {
    /**
     * 
     * @type {Array<ServiceHelpersServiceResponse>}
     * @memberof ServiceResponsesAll
     */
    services: Array<ServiceHelpersServiceResponse>;
}

/**
 * Check if a given object implements the ServiceResponsesAll interface.
 */
export function instanceOfServiceResponsesAll(value: object): value is ServiceResponsesAll {
    if (!('services' in value) || value['services'] === undefined) return false;
    return true;
}

export function ServiceResponsesAllFromJSON(json: any): ServiceResponsesAll {
    return ServiceResponsesAllFromJSONTyped(json, false);
}

export function ServiceResponsesAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResponsesAll {
    if (json == null) {
        return json;
    }
    return {
        
        'services': ((json['services'] as Array<any>).map(ServiceHelpersServiceResponseFromJSON)),
    };
}

export function ServiceResponsesAllToJSON(json: any): ServiceResponsesAll {
    return ServiceResponsesAllToJSONTyped(json, false);
}

export function ServiceResponsesAllToJSONTyped(value?: ServiceResponsesAll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'services': ((value['services'] as Array<any>).map(ServiceHelpersServiceResponseToJSON)),
    };
}

