/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TranslatedServiceTag } from './TranslatedServiceTag';
import {
    TranslatedServiceTagFromJSON,
    TranslatedServiceTagFromJSONTyped,
    TranslatedServiceTagToJSON,
    TranslatedServiceTagToJSONTyped,
} from './TranslatedServiceTag';
import type { ServiceHelpersParameter } from './ServiceHelpersParameter';
import {
    ServiceHelpersParameterFromJSON,
    ServiceHelpersParameterFromJSONTyped,
    ServiceHelpersParameterToJSON,
    ServiceHelpersParameterToJSONTyped,
} from './ServiceHelpersParameter';

/**
 * 
 * @export
 * @interface ServiceResponsesRetrieve
 */
export interface ServiceResponsesRetrieve {
    /**
     * 
     * @type {string}
     * @memberof ServiceResponsesRetrieve
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResponsesRetrieve
     */
    id: string;
    /**
     * 
     * @type {Array<TranslatedServiceTag>}
     * @memberof ServiceResponsesRetrieve
     */
    tags: Array<TranslatedServiceTag>;
    /**
     * 
     * @type {Array<ServiceHelpersParameter>}
     * @memberof ServiceResponsesRetrieve
     */
    parameters: Array<ServiceHelpersParameter>;
}

/**
 * Check if a given object implements the ServiceResponsesRetrieve interface.
 */
export function instanceOfServiceResponsesRetrieve(value: object): value is ServiceResponsesRetrieve {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    return true;
}

export function ServiceResponsesRetrieveFromJSON(json: any): ServiceResponsesRetrieve {
    return ServiceResponsesRetrieveFromJSONTyped(json, false);
}

export function ServiceResponsesRetrieveFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResponsesRetrieve {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'id': json['id'],
        'tags': ((json['tags'] as Array<any>).map(TranslatedServiceTagFromJSON)),
        'parameters': ((json['parameters'] as Array<any>).map(ServiceHelpersParameterFromJSON)),
    };
}

export function ServiceResponsesRetrieveToJSON(json: any): ServiceResponsesRetrieve {
    return ServiceResponsesRetrieveToJSONTyped(json, false);
}

export function ServiceResponsesRetrieveToJSONTyped(value?: ServiceResponsesRetrieve | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'id': value['id'],
        'tags': ((value['tags'] as Array<any>).map(TranslatedServiceTagToJSON)),
        'parameters': ((value['parameters'] as Array<any>).map(ServiceHelpersParameterToJSON)),
    };
}

