/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * • barbershop → barbershop
 * • nails → nails
 * • massage → massage
 * • spa → spa
 * • cosmetology → cosmetology
 * • hairdressing → hairdressing
 * • epilation → epilation
 * • permanent makeup → permanentMakeup
 * • piercing → piercing
 * • makeup → makeup
 * • brows → brows
 * • lashes → lashes
 * @export
 */
export const ServiceTags = {
    barbershop: 'barbershop',
    nails: 'nails',
    massage: 'massage',
    spa: 'spa',
    cosmetology: 'cosmetology',
    hairdressing: 'hairdressing',
    epilation: 'epilation',
    permanent_makeup: 'permanent makeup',
    piercing: 'piercing',
    makeup: 'makeup',
    brows: 'brows',
    lashes: 'lashes'
} as const;
export type ServiceTags = typeof ServiceTags[keyof typeof ServiceTags];


export function instanceOfServiceTags(value: any): boolean {
    for (const key in ServiceTags) {
        if (Object.prototype.hasOwnProperty.call(ServiceTags, key)) {
            if (ServiceTags[key as keyof typeof ServiceTags] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServiceTagsFromJSON(json: any): ServiceTags {
    return ServiceTagsFromJSONTyped(json, false);
}

export function ServiceTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceTags {
    return json as ServiceTags;
}

export function ServiceTagsToJSON(value?: ServiceTags | null): any {
    return value as any;
}

export function ServiceTagsToJSONTyped(value: any, ignoreDiscriminator: boolean): ServiceTags {
    return value as ServiceTags;
}

