/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';

/**
 * 
 * @export
 * @interface SubscriptionResponse
 */
export interface SubscriptionResponse {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    stripeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    id: string;
    /**
     * 
     * @type {Price}
     * @memberof SubscriptionResponse
     */
    price: Price;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponse
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponse
     */
    endDate: Date;
}

/**
 * Check if a given object implements the SubscriptionResponse interface.
 */
export function instanceOfSubscriptionResponse(value: object): value is SubscriptionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function SubscriptionResponseFromJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseFromJSONTyped(json, false);
}

export function SubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'stripeId': json['stripeId'] == null ? undefined : json['stripeId'],
        'id': json['id'],
        'price': PriceFromJSON(json['price']),
        'title': json['title'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
    };
}

export function SubscriptionResponseToJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseToJSONTyped(json, false);
}

export function SubscriptionResponseToJSONTyped(value?: SubscriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stripeId': value['stripeId'],
        'id': value['id'],
        'price': PriceToJSON(value['price']),
        'title': value['title'],
        'startDate': value['startDate'].toISOString(),
        'endDate': value['endDate'].toISOString(),
    };
}

