/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimetableParametersSearchSlotProcedure
 */
export interface TimetableParametersSearchSlotProcedure {
    /**
     * 
     * @type {string}
     * @memberof TimetableParametersSearchSlotProcedure
     */
    id: string;
}

/**
 * Check if a given object implements the TimetableParametersSearchSlotProcedure interface.
 */
export function instanceOfTimetableParametersSearchSlotProcedure(value: object): value is TimetableParametersSearchSlotProcedure {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TimetableParametersSearchSlotProcedureFromJSON(json: any): TimetableParametersSearchSlotProcedure {
    return TimetableParametersSearchSlotProcedureFromJSONTyped(json, false);
}

export function TimetableParametersSearchSlotProcedureFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableParametersSearchSlotProcedure {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function TimetableParametersSearchSlotProcedureToJSON(json: any): TimetableParametersSearchSlotProcedure {
    return TimetableParametersSearchSlotProcedureToJSONTyped(json, false);
}

export function TimetableParametersSearchSlotProcedureToJSONTyped(value?: TimetableParametersSearchSlotProcedure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

