/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimetableResponsesComplexSlotsSlot } from './TimetableResponsesComplexSlotsSlot';
import {
    TimetableResponsesComplexSlotsSlotFromJSON,
    TimetableResponsesComplexSlotsSlotFromJSONTyped,
    TimetableResponsesComplexSlotsSlotToJSON,
    TimetableResponsesComplexSlotsSlotToJSONTyped,
} from './TimetableResponsesComplexSlotsSlot';

/**
 * 
 * @export
 * @interface TimetableResponsesComplexSlots
 */
export interface TimetableResponsesComplexSlots {
    /**
     * 
     * @type {string}
     * @memberof TimetableResponsesComplexSlots
     */
    timeZoneId: string;
    /**
     * 
     * @type {Array<TimetableResponsesComplexSlotsSlot>}
     * @memberof TimetableResponsesComplexSlots
     */
    slots: Array<TimetableResponsesComplexSlotsSlot>;
}

/**
 * Check if a given object implements the TimetableResponsesComplexSlots interface.
 */
export function instanceOfTimetableResponsesComplexSlots(value: object): value is TimetableResponsesComplexSlots {
    if (!('timeZoneId' in value) || value['timeZoneId'] === undefined) return false;
    if (!('slots' in value) || value['slots'] === undefined) return false;
    return true;
}

export function TimetableResponsesComplexSlotsFromJSON(json: any): TimetableResponsesComplexSlots {
    return TimetableResponsesComplexSlotsFromJSONTyped(json, false);
}

export function TimetableResponsesComplexSlotsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableResponsesComplexSlots {
    if (json == null) {
        return json;
    }
    return {
        
        'timeZoneId': json['timeZoneId'],
        'slots': ((json['slots'] as Array<any>).map(TimetableResponsesComplexSlotsSlotFromJSON)),
    };
}

export function TimetableResponsesComplexSlotsToJSON(json: any): TimetableResponsesComplexSlots {
    return TimetableResponsesComplexSlotsToJSONTyped(json, false);
}

export function TimetableResponsesComplexSlotsToJSONTyped(value?: TimetableResponsesComplexSlots | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeZoneId': value['timeZoneId'],
        'slots': ((value['slots'] as Array<any>).map(TimetableResponsesComplexSlotsSlotToJSON)),
    };
}

