/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeDateInterval } from './SafeDateInterval';
import {
    SafeDateIntervalFromJSON,
    SafeDateIntervalFromJSONTyped,
    SafeDateIntervalToJSON,
    SafeDateIntervalToJSONTyped,
} from './SafeDateInterval';

/**
 * 
 * @export
 * @interface TimetableResponsesComplexSlotsSlotChunk
 */
export interface TimetableResponsesComplexSlotsSlotChunk {
    /**
     * 
     * @type {string}
     * @memberof TimetableResponsesComplexSlotsSlotChunk
     */
    procedureId: string;
    /**
     * 
     * @type {SafeDateInterval}
     * @memberof TimetableResponsesComplexSlotsSlotChunk
     */
    time: SafeDateInterval;
    /**
     * 
     * @type {string}
     * @memberof TimetableResponsesComplexSlotsSlotChunk
     */
    id: string;
}

/**
 * Check if a given object implements the TimetableResponsesComplexSlotsSlotChunk interface.
 */
export function instanceOfTimetableResponsesComplexSlotsSlotChunk(value: object): value is TimetableResponsesComplexSlotsSlotChunk {
    if (!('procedureId' in value) || value['procedureId'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TimetableResponsesComplexSlotsSlotChunkFromJSON(json: any): TimetableResponsesComplexSlotsSlotChunk {
    return TimetableResponsesComplexSlotsSlotChunkFromJSONTyped(json, false);
}

export function TimetableResponsesComplexSlotsSlotChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableResponsesComplexSlotsSlotChunk {
    if (json == null) {
        return json;
    }
    return {
        
        'procedureId': json['procedureId'],
        'time': SafeDateIntervalFromJSON(json['time']),
        'id': json['id'],
    };
}

export function TimetableResponsesComplexSlotsSlotChunkToJSON(json: any): TimetableResponsesComplexSlotsSlotChunk {
    return TimetableResponsesComplexSlotsSlotChunkToJSONTyped(json, false);
}

export function TimetableResponsesComplexSlotsSlotChunkToJSONTyped(value?: TimetableResponsesComplexSlotsSlotChunk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'procedureId': value['procedureId'],
        'time': SafeDateIntervalToJSON(value['time']),
        'id': value['id'],
    };
}

