/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchedulePattern } from './SchedulePattern';
import {
    SchedulePatternFromJSON,
    SchedulePatternFromJSONTyped,
    SchedulePatternToJSON,
    SchedulePatternToJSONTyped,
} from './SchedulePattern';

/**
 * 
 * @export
 * @interface TimetableParametersCreatePattern
 */
export interface TimetableParametersCreatePattern {
    /**
     * 
     * @type {Date}
     * @memberof TimetableParametersCreatePattern
     */
    startAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimetableParametersCreatePattern
     */
    endAt?: Date | null;
    /**
     * 
     * @type {SchedulePattern}
     * @memberof TimetableParametersCreatePattern
     */
    schedule: SchedulePattern;
}

/**
 * Check if a given object implements the TimetableParametersCreatePattern interface.
 */
export function instanceOfTimetableParametersCreatePattern(value: object): value is TimetableParametersCreatePattern {
    if (!('startAt' in value) || value['startAt'] === undefined) return false;
    if (!('schedule' in value) || value['schedule'] === undefined) return false;
    return true;
}

export function TimetableParametersCreatePatternFromJSON(json: any): TimetableParametersCreatePattern {
    return TimetableParametersCreatePatternFromJSONTyped(json, false);
}

export function TimetableParametersCreatePatternFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableParametersCreatePattern {
    if (json == null) {
        return json;
    }
    return {
        
        'startAt': (new Date(json['startAt'])),
        'endAt': json['endAt'] == null ? undefined : (new Date(json['endAt'])),
        'schedule': SchedulePatternFromJSON(json['schedule']),
    };
}

export function TimetableParametersCreatePatternToJSON(json: any): TimetableParametersCreatePattern {
    return TimetableParametersCreatePatternToJSONTyped(json, false);
}

export function TimetableParametersCreatePatternToJSONTyped(value?: TimetableParametersCreatePattern | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startAt': value['startAt'].toISOString(),
        'endAt': value['endAt'] == null ? value['endAt'] : value['endAt'].toISOString(),
        'schedule': SchedulePatternToJSON(value['schedule']),
    };
}

