/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeDateInterval } from './SafeDateInterval';
import {
    SafeDateIntervalFromJSON,
    SafeDateIntervalFromJSONTyped,
    SafeDateIntervalToJSON,
    SafeDateIntervalToJSONTyped,
} from './SafeDateInterval';

/**
 * 
 * @export
 * @interface TimetableResponsesSchedule
 */
export interface TimetableResponsesSchedule {
    /**
     * 
     * @type {string}
     * @memberof TimetableResponsesSchedule
     */
    timeZoneId: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableResponsesSchedule
     */
    owner: string;
    /**
     * 
     * @type {Array<SafeDateInterval>}
     * @memberof TimetableResponsesSchedule
     */
    intervals: Array<SafeDateInterval>;
}

/**
 * Check if a given object implements the TimetableResponsesSchedule interface.
 */
export function instanceOfTimetableResponsesSchedule(value: object): value is TimetableResponsesSchedule {
    if (!('timeZoneId' in value) || value['timeZoneId'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('intervals' in value) || value['intervals'] === undefined) return false;
    return true;
}

export function TimetableResponsesScheduleFromJSON(json: any): TimetableResponsesSchedule {
    return TimetableResponsesScheduleFromJSONTyped(json, false);
}

export function TimetableResponsesScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableResponsesSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'timeZoneId': json['timeZoneId'],
        'owner': json['owner'],
        'intervals': ((json['intervals'] as Array<any>).map(SafeDateIntervalFromJSON)),
    };
}

export function TimetableResponsesScheduleToJSON(json: any): TimetableResponsesSchedule {
    return TimetableResponsesScheduleToJSONTyped(json, false);
}

export function TimetableResponsesScheduleToJSONTyped(value?: TimetableResponsesSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeZoneId': value['timeZoneId'],
        'owner': value['owner'],
        'intervals': ((value['intervals'] as Array<any>).map(SafeDateIntervalToJSON)),
    };
}

