/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeDateInterval } from './SafeDateInterval';
import {
    SafeDateIntervalFromJSON,
    SafeDateIntervalFromJSONTyped,
    SafeDateIntervalToJSON,
    SafeDateIntervalToJSONTyped,
} from './SafeDateInterval';
import type { TimetableResponsesComplexSlotsSlotChunk } from './TimetableResponsesComplexSlotsSlotChunk';
import {
    TimetableResponsesComplexSlotsSlotChunkFromJSON,
    TimetableResponsesComplexSlotsSlotChunkFromJSONTyped,
    TimetableResponsesComplexSlotsSlotChunkToJSON,
    TimetableResponsesComplexSlotsSlotChunkToJSONTyped,
} from './TimetableResponsesComplexSlotsSlotChunk';

/**
 * 
 * @export
 * @interface TimetableResponsesComplexSlotsSlot
 */
export interface TimetableResponsesComplexSlotsSlot {
    /**
     * 
     * @type {SafeDateInterval}
     * @memberof TimetableResponsesComplexSlotsSlot
     */
    total: SafeDateInterval;
    /**
     * 
     * @type {Array<TimetableResponsesComplexSlotsSlotChunk>}
     * @memberof TimetableResponsesComplexSlotsSlot
     */
    chunks: Array<TimetableResponsesComplexSlotsSlotChunk>;
}

/**
 * Check if a given object implements the TimetableResponsesComplexSlotsSlot interface.
 */
export function instanceOfTimetableResponsesComplexSlotsSlot(value: object): value is TimetableResponsesComplexSlotsSlot {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('chunks' in value) || value['chunks'] === undefined) return false;
    return true;
}

export function TimetableResponsesComplexSlotsSlotFromJSON(json: any): TimetableResponsesComplexSlotsSlot {
    return TimetableResponsesComplexSlotsSlotFromJSONTyped(json, false);
}

export function TimetableResponsesComplexSlotsSlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableResponsesComplexSlotsSlot {
    if (json == null) {
        return json;
    }
    return {
        
        'total': SafeDateIntervalFromJSON(json['total']),
        'chunks': ((json['chunks'] as Array<any>).map(TimetableResponsesComplexSlotsSlotChunkFromJSON)),
    };
}

export function TimetableResponsesComplexSlotsSlotToJSON(json: any): TimetableResponsesComplexSlotsSlot {
    return TimetableResponsesComplexSlotsSlotToJSONTyped(json, false);
}

export function TimetableResponsesComplexSlotsSlotToJSONTyped(value?: TimetableResponsesComplexSlotsSlot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': SafeDateIntervalToJSON(value['total']),
        'chunks': ((value['chunks'] as Array<any>).map(TimetableResponsesComplexSlotsSlotChunkToJSON)),
    };
}

