/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimetableParametersSearchSlotComplex
 */
export interface TimetableParametersSearchSlotComplex {
    /**
     * 
     * @type {string}
     * @memberof TimetableParametersSearchSlotComplex
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TimetableParametersSearchSlotComplex
     */
    chunks: Array<string>;
}

/**
 * Check if a given object implements the TimetableParametersSearchSlotComplex interface.
 */
export function instanceOfTimetableParametersSearchSlotComplex(value: object): value is TimetableParametersSearchSlotComplex {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('chunks' in value) || value['chunks'] === undefined) return false;
    return true;
}

export function TimetableParametersSearchSlotComplexFromJSON(json: any): TimetableParametersSearchSlotComplex {
    return TimetableParametersSearchSlotComplexFromJSONTyped(json, false);
}

export function TimetableParametersSearchSlotComplexFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableParametersSearchSlotComplex {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chunks': json['chunks'],
    };
}

export function TimetableParametersSearchSlotComplexToJSON(json: any): TimetableParametersSearchSlotComplex {
    return TimetableParametersSearchSlotComplexToJSONTyped(json, false);
}

export function TimetableParametersSearchSlotComplexToJSONTyped(value?: TimetableParametersSearchSlotComplex | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chunks': value['chunks'],
    };
}

