/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeDateInterval } from './SafeDateInterval';
import {
    SafeDateIntervalFromJSON,
    SafeDateIntervalFromJSONTyped,
    SafeDateIntervalToJSON,
    SafeDateIntervalToJSONTyped,
} from './SafeDateInterval';

/**
 * 
 * @export
 * @interface TimetableResponsesProcedureSlots
 */
export interface TimetableResponsesProcedureSlots {
    /**
     * 
     * @type {string}
     * @memberof TimetableResponsesProcedureSlots
     */
    timeZoneId: string;
    /**
     * 
     * @type {Array<SafeDateInterval>}
     * @memberof TimetableResponsesProcedureSlots
     */
    intervals: Array<SafeDateInterval>;
}

/**
 * Check if a given object implements the TimetableResponsesProcedureSlots interface.
 */
export function instanceOfTimetableResponsesProcedureSlots(value: object): value is TimetableResponsesProcedureSlots {
    if (!('timeZoneId' in value) || value['timeZoneId'] === undefined) return false;
    if (!('intervals' in value) || value['intervals'] === undefined) return false;
    return true;
}

export function TimetableResponsesProcedureSlotsFromJSON(json: any): TimetableResponsesProcedureSlots {
    return TimetableResponsesProcedureSlotsFromJSONTyped(json, false);
}

export function TimetableResponsesProcedureSlotsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableResponsesProcedureSlots {
    if (json == null) {
        return json;
    }
    return {
        
        'timeZoneId': json['timeZoneId'],
        'intervals': ((json['intervals'] as Array<any>).map(SafeDateIntervalFromJSON)),
    };
}

export function TimetableResponsesProcedureSlotsToJSON(json: any): TimetableResponsesProcedureSlots {
    return TimetableResponsesProcedureSlotsToJSONTyped(json, false);
}

export function TimetableResponsesProcedureSlotsToJSONTyped(value?: TimetableResponsesProcedureSlots | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeZoneId': value['timeZoneId'],
        'intervals': ((value['intervals'] as Array<any>).map(SafeDateIntervalToJSON)),
    };
}

