/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceTags } from './ServiceTags';
import {
    ServiceTagsFromJSON,
    ServiceTagsFromJSONTyped,
    ServiceTagsToJSON,
    ServiceTagsToJSONTyped,
} from './ServiceTags';

/**
 * 
 * @export
 * @interface TranslatedServiceTag
 */
export interface TranslatedServiceTag {
    /**
     * 
     * @type {ServiceTags}
     * @memberof TranslatedServiceTag
     */
    tag: ServiceTags;
    /**
     * 
     * @type {string}
     * @memberof TranslatedServiceTag
     */
    translate: string;
}



/**
 * Check if a given object implements the TranslatedServiceTag interface.
 */
export function instanceOfTranslatedServiceTag(value: object): value is TranslatedServiceTag {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('translate' in value) || value['translate'] === undefined) return false;
    return true;
}

export function TranslatedServiceTagFromJSON(json: any): TranslatedServiceTag {
    return TranslatedServiceTagFromJSONTyped(json, false);
}

export function TranslatedServiceTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslatedServiceTag {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': ServiceTagsFromJSON(json['tag']),
        'translate': json['translate'],
    };
}

export function TranslatedServiceTagToJSON(json: any): TranslatedServiceTag {
    return TranslatedServiceTagToJSONTyped(json, false);
}

export function TranslatedServiceTagToJSONTyped(value?: TranslatedServiceTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': ServiceTagsToJSON(value['tag']),
        'translate': value['translate'],
    };
}

