/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateString
 */
export interface UpdateString {
    /**
     * 
     * @type {string}
     * @memberof UpdateString
     */
    value?: string | null;
}

/**
 * Check if a given object implements the UpdateString interface.
 */
export function instanceOfUpdateString(value: object): value is UpdateString {
    return true;
}

export function UpdateStringFromJSON(json: any): UpdateString {
    return UpdateStringFromJSONTyped(json, false);
}

export function UpdateStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateString {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function UpdateStringToJSON(json: any): UpdateString {
    return UpdateStringToJSONTyped(json, false);
}

export function UpdateStringToJSONTyped(value?: UpdateString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

