/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadRouterV1Input
 */
export interface UploadRouterV1Input {
    /**
     * 
     * @type {any}
     * @memberof UploadRouterV1Input
     */
    image: any;
}

/**
 * Check if a given object implements the UploadRouterV1Input interface.
 */
export function instanceOfUploadRouterV1Input(value: object): value is UploadRouterV1Input {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function UploadRouterV1InputFromJSON(json: any): UploadRouterV1Input {
    return UploadRouterV1InputFromJSONTyped(json, false);
}

export function UploadRouterV1InputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadRouterV1Input {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function UploadRouterV1InputToJSON(json: any): UploadRouterV1Input {
    return UploadRouterV1InputToJSONTyped(json, false);
}

export function UploadRouterV1InputToJSONTyped(value?: UploadRouterV1Input | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
    };
}

