/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserParametersPatch
 */
export interface UserParametersPatch {
    /**
     * 
     * @type {string}
     * @memberof UserParametersPatch
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserParametersPatch
     */
    nickname?: string | null;
}

/**
 * Check if a given object implements the UserParametersPatch interface.
 */
export function instanceOfUserParametersPatch(value: object): value is UserParametersPatch {
    return true;
}

export function UserParametersPatchFromJSON(json: any): UserParametersPatch {
    return UserParametersPatchFromJSONTyped(json, false);
}

export function UserParametersPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserParametersPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
    };
}

export function UserParametersPatchToJSON(json: any): UserParametersPatch {
    return UserParametersPatchToJSONTyped(json, false);
}

export function UserParametersPatchToJSONTyped(value?: UserParametersPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'nickname': value['nickname'],
    };
}

