/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponsesUserInfo
 */
export interface UserResponsesUserInfo {
    /**
     * 
     * @type {string}
     * @memberof UserResponsesUserInfo
     */
    avatar: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponsesUserInfo
     */
    haveCustomer: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponsesUserInfo
     */
    haveEmployee: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserResponsesUserInfo
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponsesUserInfo
     */
    id: string;
}

/**
 * Check if a given object implements the UserResponsesUserInfo interface.
 */
export function instanceOfUserResponsesUserInfo(value: object): value is UserResponsesUserInfo {
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('haveCustomer' in value) || value['haveCustomer'] === undefined) return false;
    if (!('haveEmployee' in value) || value['haveEmployee'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserResponsesUserInfoFromJSON(json: any): UserResponsesUserInfo {
    return UserResponsesUserInfoFromJSONTyped(json, false);
}

export function UserResponsesUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponsesUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'],
        'haveCustomer': json['haveCustomer'],
        'haveEmployee': json['haveEmployee'],
        'nickname': json['nickname'],
        'id': json['id'],
    };
}

export function UserResponsesUserInfoToJSON(json: any): UserResponsesUserInfo {
    return UserResponsesUserInfoToJSONTyped(json, false);
}

export function UserResponsesUserInfoToJSONTyped(value?: UserResponsesUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'haveCustomer': value['haveCustomer'],
        'haveEmployee': value['haveEmployee'],
        'nickname': value['nickname'],
        'id': value['id'],
    };
}

