/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VersionType = {
    latest: 'latest',
    stable: 'stable',
    unsupported: 'unsupported'
} as const;
export type VersionType = typeof VersionType[keyof typeof VersionType];


export function instanceOfVersionType(value: any): boolean {
    for (const key in VersionType) {
        if (Object.prototype.hasOwnProperty.call(VersionType, key)) {
            if (VersionType[key as keyof typeof VersionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VersionTypeFromJSON(json: any): VersionType {
    return VersionTypeFromJSONTyped(json, false);
}

export function VersionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionType {
    return json as VersionType;
}

export function VersionTypeToJSON(value?: VersionType | null): any {
    return value as any;
}

export function VersionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): VersionType {
    return value as VersionType;
}

