/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';

/**
 * 
 * @export
 * @interface Wage
 */
export interface Wage {
    /**
     * 
     * @type {Price}
     * @memberof Wage
     */
    price: Price;
    /**
     * 
     * @type {string}
     * @memberof Wage
     */
    period: string;
}

/**
 * Check if a given object implements the Wage interface.
 */
export function instanceOfWage(value: object): value is Wage {
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    return true;
}

export function WageFromJSON(json: any): Wage {
    return WageFromJSONTyped(json, false);
}

export function WageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wage {
    if (json == null) {
        return json;
    }
    return {
        
        'price': PriceFromJSON(json['price']),
        'period': json['period'],
    };
}

export function WageToJSON(json: any): Wage {
    return WageToJSONTyped(json, false);
}

export function WageToJSONTyped(value?: Wage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price': PriceToJSON(value['price']),
        'period': value['period'],
    };
}

