/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinatePoint } from './CoordinatePoint';
import {
    CoordinatePointFromJSON,
    CoordinatePointFromJSONTyped,
    CoordinatePointToJSON,
    CoordinatePointToJSONTyped,
} from './CoordinatePoint';
import type { WorkspaceInternalContact } from './WorkspaceInternalContact';
import {
    WorkspaceInternalContactFromJSON,
    WorkspaceInternalContactFromJSONTyped,
    WorkspaceInternalContactToJSON,
    WorkspaceInternalContactToJSONTyped,
} from './WorkspaceInternalContact';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { SalonType } from './SalonType';
import {
    SalonTypeFromJSON,
    SalonTypeFromJSONTyped,
    SalonTypeToJSON,
    SalonTypeToJSONTyped,
} from './SalonType';
import type { TimetableParametersCreatePattern } from './TimetableParametersCreatePattern';
import {
    TimetableParametersCreatePatternFromJSON,
    TimetableParametersCreatePatternFromJSONTyped,
    TimetableParametersCreatePatternToJSON,
    TimetableParametersCreatePatternToJSONTyped,
} from './TimetableParametersCreatePattern';

/**
 * 
 * @export
 * @interface WorkspaceParametersCreate
 */
export interface WorkspaceParametersCreate {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersCreate
     */
    timeZoneId: string;
    /**
     * 
     * @type {TimetableParametersCreatePattern}
     * @memberof WorkspaceParametersCreate
     */
    timetable?: TimetableParametersCreatePattern;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersCreate
     */
    localeId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersCreate
     */
    logo?: string | null;
    /**
     * 
     * @type {WorkspaceInternalContact}
     * @memberof WorkspaceParametersCreate
     */
    contact?: WorkspaceInternalContact;
    /**
     * 
     * @type {Address}
     * @memberof WorkspaceParametersCreate
     */
    address: Address;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersCreate
     */
    description?: string | null;
    /**
     * 
     * @type {SalonType}
     * @memberof WorkspaceParametersCreate
     */
    type: SalonType;
    /**
     * 
     * @type {CoordinatePoint}
     * @memberof WorkspaceParametersCreate
     */
    point: CoordinatePoint;
}



/**
 * Check if a given object implements the WorkspaceParametersCreate interface.
 */
export function instanceOfWorkspaceParametersCreate(value: object): value is WorkspaceParametersCreate {
    if (!('timeZoneId' in value) || value['timeZoneId'] === undefined) return false;
    if (!('localeId' in value) || value['localeId'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('point' in value) || value['point'] === undefined) return false;
    return true;
}

export function WorkspaceParametersCreateFromJSON(json: any): WorkspaceParametersCreate {
    return WorkspaceParametersCreateFromJSONTyped(json, false);
}

export function WorkspaceParametersCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceParametersCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'timeZoneId': json['timeZoneId'],
        'timetable': json['timetable'] == null ? undefined : TimetableParametersCreatePatternFromJSON(json['timetable']),
        'localeId': json['localeId'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'contact': json['contact'] == null ? undefined : WorkspaceInternalContactFromJSON(json['contact']),
        'address': AddressFromJSON(json['address']),
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': SalonTypeFromJSON(json['type']),
        'point': CoordinatePointFromJSON(json['point']),
    };
}

export function WorkspaceParametersCreateToJSON(json: any): WorkspaceParametersCreate {
    return WorkspaceParametersCreateToJSONTyped(json, false);
}

export function WorkspaceParametersCreateToJSONTyped(value?: WorkspaceParametersCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeZoneId': value['timeZoneId'],
        'timetable': TimetableParametersCreatePatternToJSON(value['timetable']),
        'localeId': value['localeId'],
        'logo': value['logo'],
        'contact': WorkspaceInternalContactToJSON(value['contact']),
        'address': AddressToJSON(value['address']),
        'name': value['name'],
        'description': value['description'],
        'type': SalonTypeToJSON(value['type']),
        'point': CoordinatePointToJSON(value['point']),
    };
}

