/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactType } from './ContactType';
import {
    ContactTypeFromJSON,
    ContactTypeFromJSONTyped,
    ContactTypeToJSON,
    ContactTypeToJSONTyped,
} from './ContactType';

/**
 * 
 * @export
 * @interface WorkspaceInternalContact
 */
export interface WorkspaceInternalContact {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceInternalContact
     */
    value: string;
    /**
     * 
     * @type {ContactType}
     * @memberof WorkspaceInternalContact
     */
    type: ContactType;
}



/**
 * Check if a given object implements the WorkspaceInternalContact interface.
 */
export function instanceOfWorkspaceInternalContact(value: object): value is WorkspaceInternalContact {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WorkspaceInternalContactFromJSON(json: any): WorkspaceInternalContact {
    return WorkspaceInternalContactFromJSONTyped(json, false);
}

export function WorkspaceInternalContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceInternalContact {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'type': ContactTypeFromJSON(json['type']),
    };
}

export function WorkspaceInternalContactToJSON(json: any): WorkspaceInternalContact {
    return WorkspaceInternalContactToJSONTyped(json, false);
}

export function WorkspaceInternalContactToJSONTyped(value?: WorkspaceInternalContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'type': ContactTypeToJSON(value['type']),
    };
}

