/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalonType } from './SalonType';
import {
    SalonTypeFromJSON,
    SalonTypeFromJSONTyped,
    SalonTypeToJSON,
    SalonTypeToJSONTyped,
} from './SalonType';

/**
 * 
 * @export
 * @interface WorkspaceParametersPatch
 */
export interface WorkspaceParametersPatch {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersPatch
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersPatch
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceParametersPatch
     */
    logo?: string | null;
    /**
     * 
     * @type {SalonType}
     * @memberof WorkspaceParametersPatch
     */
    type?: SalonType;
}



/**
 * Check if a given object implements the WorkspaceParametersPatch interface.
 */
export function instanceOfWorkspaceParametersPatch(value: object): value is WorkspaceParametersPatch {
    return true;
}

export function WorkspaceParametersPatchFromJSON(json: any): WorkspaceParametersPatch {
    return WorkspaceParametersPatchFromJSONTyped(json, false);
}

export function WorkspaceParametersPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceParametersPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'type': json['type'] == null ? undefined : SalonTypeFromJSON(json['type']),
    };
}

export function WorkspaceParametersPatchToJSON(json: any): WorkspaceParametersPatch {
    return WorkspaceParametersPatchToJSONTyped(json, false);
}

export function WorkspaceParametersPatchToJSONTyped(value?: WorkspaceParametersPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'logo': value['logo'],
        'type': SalonTypeToJSON(value['type']),
    };
}

