/* tslint:disable */
/* eslint-disable */
/**
 * Maetry API
 * Generated from current registered RouteCollection methods and shared DTO schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinatePoint } from './CoordinatePoint';
import {
    CoordinatePointFromJSON,
    CoordinatePointFromJSONTyped,
    CoordinatePointToJSON,
    CoordinatePointToJSONTyped,
} from './CoordinatePoint';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { SalonType } from './SalonType';
import {
    SalonTypeFromJSON,
    SalonTypeFromJSONTyped,
    SalonTypeToJSON,
    SalonTypeToJSONTyped,
} from './SalonType';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface WorkspaceResponsesFull
 */
export interface WorkspaceResponsesFull {
    /**
     * 
     * @type {Address}
     * @memberof WorkspaceResponsesFull
     */
    address: Address;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceResponsesFull
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponsesFull
     */
    timeZoneId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponsesFull
     */
    description?: string | null;
    /**
     * 
     * @type {CoordinatePoint}
     * @memberof WorkspaceResponsesFull
     */
    point: CoordinatePoint;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponsesFull
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponsesFull
     */
    localeId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponsesFull
     */
    id: string;
    /**
     * 
     * @type {Token}
     * @memberof WorkspaceResponsesFull
     */
    employeeToken: Token;
    /**
     * 
     * @type {SalonType}
     * @memberof WorkspaceResponsesFull
     */
    type: SalonType;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponsesFull
     */
    logo: string;
}



/**
 * Check if a given object implements the WorkspaceResponsesFull interface.
 */
export function instanceOfWorkspaceResponsesFull(value: object): value is WorkspaceResponsesFull {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('timeZoneId' in value) || value['timeZoneId'] === undefined) return false;
    if (!('point' in value) || value['point'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('localeId' in value) || value['localeId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('employeeToken' in value) || value['employeeToken'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('logo' in value) || value['logo'] === undefined) return false;
    return true;
}

export function WorkspaceResponsesFullFromJSON(json: any): WorkspaceResponsesFull {
    return WorkspaceResponsesFullFromJSONTyped(json, false);
}

export function WorkspaceResponsesFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceResponsesFull {
    if (json == null) {
        return json;
    }
    return {
        
        'address': AddressFromJSON(json['address']),
        'isActive': json['isActive'],
        'timeZoneId': json['timeZoneId'],
        'description': json['description'] == null ? undefined : json['description'],
        'point': CoordinatePointFromJSON(json['point']),
        'name': json['name'],
        'localeId': json['localeId'],
        'id': json['id'],
        'employeeToken': TokenFromJSON(json['employeeToken']),
        'type': SalonTypeFromJSON(json['type']),
        'logo': json['logo'],
    };
}

export function WorkspaceResponsesFullToJSON(json: any): WorkspaceResponsesFull {
    return WorkspaceResponsesFullToJSONTyped(json, false);
}

export function WorkspaceResponsesFullToJSONTyped(value?: WorkspaceResponsesFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': AddressToJSON(value['address']),
        'isActive': value['isActive'],
        'timeZoneId': value['timeZoneId'],
        'description': value['description'],
        'point': CoordinatePointToJSON(value['point']),
        'name': value['name'],
        'localeId': value['localeId'],
        'id': value['id'],
        'employeeToken': TokenToJSON(value['employeeToken']),
        'type': SalonTypeToJSON(value['type']),
        'logo': value['logo'],
    };
}

